-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fn_item_higher_ranked]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace fn_item_higher_ranked

/-- [core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2519:8-2519:47
    Name pattern: [core::cmp::impls::{core::cmp::Ord<&'0 @A>}::cmp]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::Ord<&'0 @A>}::cmp"]
axiom Shared0A.Insts.CoreCmpOrd.cmp
  {A : Type} (OrdInst : core.cmp.Ord A) : A → A → Result Ordering

/-- [core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::{impl core::ops::function::FnMut<(&'_1 &'_0 A, &'_2 &'_0 A), core::cmp::Ordering> for core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::cmp<'static, 'static, 'static, A>[TraitClause0]}::call_mut]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2519:8-2519:47
    Name pattern: [core::cmp::impls::{core::cmp::Ord<&'0 @A>}::{core::ops::function::FnMut<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>}::call_mut]
    Visibility: public -/
@[rust_fun
  "core::cmp::impls::{core::cmp::Ord<&'0 @A>}::{core::ops::function::FnMut<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>}::call_mut"]
axiom
  core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnMutPairShared1Shared0AShared2Shared0AOrdering.call_mut
  {A : Type} (OrdInst : core.cmp.Ord A) :
  (A → A → Result Ordering) → (A × A) → Result (Ordering × (A → A
    → Result Ordering))

/-- [core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::{impl core::ops::function::FnOnce<(&'_1 &'_0 A, &'_2 &'_0 A), core::cmp::Ordering> for core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::cmp<'static, 'static, 'static, A>[TraitClause0]}::call_once]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2519:8-2519:47
    Name pattern: [core::cmp::impls::{core::cmp::Ord<&'0 @A>}::{core::ops::function::FnOnce<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>}::call_once]
    Visibility: public -/
@[rust_fun
  "core::cmp::impls::{core::cmp::Ord<&'0 @A>}::{core::ops::function::FnOnce<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>}::call_once"]
axiom
  core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnOncePairShared1Shared0AShared2Shared0AOrdering.call_once
  {A : Type} (OrdInst : core.cmp.Ord A) :
  (A → A → Result Ordering) → (A × A) → Result Ordering

/-- Trait implementation: [core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::{impl core::ops::function::FnOnce<(&'_1 &'_0 A, &'_2 &'_0 A), core::cmp::Ordering> for core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::cmp<'static, 'static, 'static, A>[TraitClause0]}]
    Source: '/rustc/library/core/src/cmp.rs', lines 2519:8-2519:47
    Name pattern: [core::ops::function::FnOnce<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnOnce<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>"]
def
  core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnOncePairShared1Shared0AShared2Shared0AOrdering
  {A : Type} (OrdInst : core.cmp.Ord A) : core.ops.function.FnOnce (A → A →
  Result Ordering) (A × A) Ordering := {
  call_once :=
    core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnOncePairShared1Shared0AShared2Shared0AOrdering.call_once
    OrdInst
}

/-- Trait implementation: [core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::{impl core::ops::function::FnMut<(&'_1 &'_0 A, &'_2 &'_0 A), core::cmp::Ordering> for core::cmp::impls::{impl core::cmp::Ord for &'_0 A}::cmp<'static, 'static, 'static, A>[TraitClause0]}]
    Source: '/rustc/library/core/src/cmp.rs', lines 2519:8-2519:47
    Name pattern: [core::ops::function::FnMut<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnMut<@, (&'1 &'0 @A, &'2 &'0 @A), core::cmp::Ordering>"]
def
  core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnMutPairShared1Shared0AShared2Shared0AOrdering
  {A : Type} (OrdInst : core.cmp.Ord A) : core.ops.function.FnMut (A → A →
  Result Ordering) (A × A) Ordering := {
  FnOnceInst :=
    core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnOncePairShared1Shared0AShared2Shared0AOrdering
    OrdInst
  call_mut :=
    core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnMutPairShared1Shared0AShared2Shared0AOrdering.call_mut
    OrdInst
}

/-- [core::iter::traits::iterator::Iterator::max_by]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 3352:4-3356:82
    Name pattern: [core::iter::traits::iterator::Iterator::max_by]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::max_by"]
axiom core.iter.traits.iterator.Iterator.max_by.default
  {Self : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFPairSharedClause0_ItemSharedClause0_ItemOrderingInst :
  core.ops.function.FnMut F (Clause0_Item × Clause0_Item) Ordering) :
  Self → F → Result (Option Clause0_Item)

/-- [fn_item_higher_ranked::longest]:
    Source: 'tests/src/fn-item-higher-ranked.rs', lines 6:0-8:1
    Visibility: public -/
def longest (lens : Slice Std.Usize) : Result (Option Std.Usize) := do
  let i ← core.slice.Slice.iter lens
  core.iter.traits.iterator.Iterator.max_by.default
    (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
    (core.cmp.impls.OrdShared0A.cmp.Insts.CoreOpsFunctionFnMutPairShared1Shared0AShared2Shared0AOrdering
    core.cmp.OrdUsize) i (Shared0A.Insts.CoreCmpOrd.cmp core.cmp.OrdUsize)

end fn_item_higher_ranked
