-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_mut_capture_nested]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace closure_mut_capture_nested

/-- Trait declaration: [core::alloc::AllocatorClone]
    Source: '/rustc/library/core/src/alloc/mod.rs', lines 541:0-541:50
    Name pattern: [core::alloc::AllocatorClone]
    Visibility: public -/
@[rust_trait "core::alloc::AllocatorClone"
  (parentClauses := ["cloneCloneInst"])]
structure core.alloc.AllocatorClone (Self : Type) where
  cloneCloneInst : core.clone.Clone Self

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- [core::borrow::{impl core::borrow::Borrow<T> for T}::borrow]:
    Source: '/rustc/library/core/src/borrow.rs', lines 214:4-214:26
    Name pattern: [core::borrow::{core::borrow::Borrow<@T, @T>}::borrow]
    Visibility: public -/
@[rust_fun "core::borrow::{core::borrow::Borrow<@T, @T>}::borrow"]
axiom core.borrow.Borrow.Blanket.borrow {T : Type} : T → Result T

/-- Trait implementation: [core::borrow::{impl core::borrow::Borrow<T> for T}]
    Source: '/rustc/library/core/src/borrow.rs', lines 212:0-212:37
    Name pattern: [core::borrow::Borrow<@T, @T>] -/
@[reducible, rust_trait_impl "core::borrow::Borrow<@T, @T>"]
def core.borrow.Borrow.Blanket (T : Type) : core.borrow.Borrow T T := {
  borrow := core.borrow.Borrow.Blanket.borrow
}

/-- [core::iter::adapters::chain::Chain]
    Source: '/rustc/library/core/src/iter/adapters/chain.rs', lines 23:0-23:22
    Name pattern: [core::iter::adapters::chain::Chain]
    Visibility: public -/
@[rust_type "core::iter::adapters::chain::Chain"]
axiom core.iter.adapters.chain.Chain (A : Type) (B : Type) : Type

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 845:4-848:34
    Name pattern: [core::iter::traits::iterator::Iterator::map]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::traits::iterator::Iterator::chain]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 524:4-527:51
    Name pattern: [core::iter::traits::iterator::Iterator::chain]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::chain"]
axiom core.iter.traits.iterator.Iterator.chain.default
  {Self : Type} {U : Type} {Clause0_Item : Type} {Clause1_IntoIter : Type}
  (IteratorInst : core.iter.traits.iterator.Iterator Self Clause0_Item)
  (collectIntoIteratorInst : core.iter.traits.collect.IntoIterator U
  Clause0_Item Clause1_IntoIter) :
  Self → U → Result (core.iter.adapters.chain.Chain Self Clause1_IntoIter)

/-- [core::iter::adapters::enumerate::{impl core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}::fold]:
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 129:4-131:44
    Name pattern: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::fold]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>}::fold"]
axiom
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.fold
  {I : Type} {Acc : Type} {Fold : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFoldPairAccPairUsizeClause0_ItemAccInst :
  core.ops.function.FnMut Fold (Acc × (Std.Usize × Clause0_Item)) Acc) :
  core.iter.adapters.enumerate.Enumerate I → Acc → Fold → Result Acc

/-- [core::iter::adapters::map::{impl core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::fold]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 124:4-126:41
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::fold]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::fold"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.fold
  {B : Type} {I : Type} {F : Type} {Acc : Type} {G : Type} {Clause0_Item :
  Type} (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) (opsfunctionFnMutGPairAccInst :
  core.ops.function.FnMut G (Acc × B) Acc) :
  core.iter.adapters.map.Map I F → Acc → G → Result Acc

/-- [core::iter::adapters::map::{impl core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 106:4-106:35
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::next]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::next"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
  {B : Type} {I : Type} {F : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) :
  core.iter.adapters.map.Map I F → Result ((Option B) ×
    (core.iter.adapters.map.Map I F))

/-- Trait implementation: [core::iter::adapters::map::{impl core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}]
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>"]
impl_def core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator {B :
  Type} {I : Type} {F : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst
  : core.iter.traits.iterator.Iterator I Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) : core.iter.traits.iterator.Iterator
  (core.iter.adapters.map.Map I F) B := {
  next := core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst
  chain := fun {U : Type} {Clause0_IntoIter : Type} (collectIntoIteratorInst :
    core.iter.traits.collect.IntoIterator U B Clause0_IntoIter) =>
    core.iter.traits.iterator.Iterator.chain.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst)
    collectIntoIteratorInst
  map := fun {B1 : Type} {F1 : Type} (opsfunctionFnMutPTupleBPInst :
    core.ops.function.FnMut F1 B B1) =>
    core.iter.traits.iterator.Iterator.map.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst)
    opsfunctionFnMutPTupleBPInst
  enumerate := core.iter.traits.iterator.Iterator.enumerate.trait_default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst)
  collect := fun {B1 : Type} (collectFromIteratorInst :
    core.iter.traits.collect.FromIterator B1 B) =>
    core.iter.traits.iterator.Iterator.collect.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst)
    collectFromIteratorInst
  fold := fun {B1 : Type} {F1 : Type} (opsfunctionFnMutPPairPInst :
    core.ops.function.FnMut F1 (B1 × B) B1) =>
    core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.fold
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst
    opsfunctionFnMutPPairPInst
}

/-- [core::iter::sources::once::Once]
    Source: '/rustc/library/core/src/iter/sources/once.rs', lines 66:0-66:18
    Name pattern: [core::iter::sources::once::Once]
    Visibility: public -/
@[rust_type "core::iter::sources::once::Once"]
axiom core.iter.sources.once.Once (T : Type) : Type

/-- [core::iter::sources::once::once]:
    Source: '/rustc/library/core/src/iter/sources/once.rs', lines 56:0-56:35
    Name pattern: [core::iter::sources::once::once]
    Visibility: public -/
@[rust_fun "core::iter::sources::once::once"]
axiom core.iter.sources.once.once
  {T : Type} : T → Result (core.iter.sources.once.Once T)

/-- [core::iter::traits::iterator::Iterator::fold]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 2674:4-2677:64
    Name pattern: [core::iter::traits::iterator::Iterator::fold]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::fold"]
axiom core.iter.traits.iterator.Iterator.fold.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFPairBInst : core.ops.function.FnMut F (B × Clause0_Item)
  B) :
  Self → B → F → Result B

/-- [core::iter::sources::once::{impl core::iter::traits::iterator::Iterator<T> for core::iter::sources::once::Once<T>}::next]:
    Source: '/rustc/library/core/src/iter/sources/once.rs', lines 74:4-74:35
    Name pattern: [core::iter::sources::once::{core::iter::traits::iterator::Iterator<core::iter::sources::once::Once<@T>, @T>}::next]
    Visibility: public -/
@[rust_fun
  "core::iter::sources::once::{core::iter::traits::iterator::Iterator<core::iter::sources::once::Once<@T>, @T>}::next"]
axiom core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} :
  core.iter.sources.once.Once T → Result ((Option T) ×
    (core.iter.sources.once.Once T))

/-- Trait implementation: [core::iter::sources::once::{impl core::iter::traits::iterator::Iterator<T> for core::iter::sources::once::Once<T>}]
    Source: '/rustc/library/core/src/iter/sources/once.rs', lines 71:0-71:28
    Name pattern: [core::iter::traits::iterator::Iterator<core::iter::sources::once::Once<@T>, @T>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<core::iter::sources::once::Once<@T>, @T>"]
impl_def core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator (T :
  Type) : core.iter.traits.iterator.Iterator (core.iter.sources.once.Once T) T
  := {
  next := core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator.next
  chain := fun {U : Type} {Clause0_IntoIter : Type} (collectIntoIteratorInst :
    core.iter.traits.collect.IntoIterator U T Clause0_IntoIter) =>
    core.iter.traits.iterator.Iterator.chain.default
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator T)
    collectIntoIteratorInst
  map := fun {B : Type} {F : Type} (opsfunctionFnMutPTupleBPInst :
    core.ops.function.FnMut F T B) =>
    core.iter.traits.iterator.Iterator.map.default
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator T)
    opsfunctionFnMutPTupleBPInst
  enumerate := core.iter.traits.iterator.Iterator.enumerate.trait_default
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator T)
  collect := fun {B : Type} (collectFromIteratorInst :
    core.iter.traits.collect.FromIterator B T) =>
    core.iter.traits.iterator.Iterator.collect.default
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator T)
    collectFromIteratorInst
  fold := fun {B : Type} {F : Type} (opsfunctionFnMutPPairPInst :
    core.ops.function.FnMut F (B × T) B) =>
    core.iter.traits.iterator.Iterator.fold.default
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator T)
    opsfunctionFnMutPPairPInst
}

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- [core::option::{core::option::Option<T>}::unwrap_or_default]:
    Source: '/rustc/library/core/src/option.rs', lines 1093:4-1095:27
    Name pattern: [core::option::{core::option::Option<@T>}::unwrap_or_default]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::unwrap_or_default"]
axiom core.option.Option.unwrap_or_default
  {T : Type} (defaultDefaultInst : core.default.Default T) :
  Option T → Result T

/-- [core::option::{core::option::Option<&'_0 T>}::copied]:
    Source: '/rustc/library/core/src/option.rs', lines 2135:4-2137:16
    Name pattern: [core::option::{core::option::Option<&'0 @T>}::copied]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
axiom core.option.OptionShared0T.copied
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  Option T → Result (Option T)

/-- [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a T> for core::slice::iter::Iter<'a, T>}::fold]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 254:12-256:49
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::fold]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::fold"]
axiom core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.fold
  {T : Type} {B : Type} {F : Type} (opsfunctionFnMutFPairBSharedATBInst :
  core.ops.function.FnMut F (B × T) B) :
  core.slice.iter.Iter T → B → F → Result B

/-- Trait implementation: [alloc::alloc::{impl core::alloc::AllocatorClone for alloc::alloc::Global}]
    Source: '/rustc/library/alloc/src/alloc.rs', lines 62:0-62:50
    Name pattern: [core::alloc::AllocatorClone<alloc::alloc::Global>] -/
@[reducible, rust_trait_impl
  "core::alloc::AllocatorClone<alloc::alloc::Global>"]
def alloc.alloc.Global.Insts.CoreAllocAllocatorClone :
  core.alloc.AllocatorClone Global := {
  cloneCloneInst := core.clone.CloneGlobal
}

/-- [alloc::collections::btree::map::BTreeMap]
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 189:0-193:1
    Name pattern: [alloc::collections::btree::map::BTreeMap]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::BTreeMap"]
axiom alloc.collections.btree.map.BTreeMap (K : Type) (V : Type) (A : Type) :
  Type

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, A>}::get]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 719:4-722:15
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::get]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, @A>}::get"]
axiom alloc.collections.btree.map.BTreeMap.get
  {K : Type} {V : Type} {A : Type} {Q : Type} (coreallocAllocatorCloneInst :
  core.alloc.AllocatorClone A) (coreborrowBorrowInst : core.borrow.Borrow K Q)
  (corecmpOrdInst : core.cmp.Ord K) (corecmpOrdInst1 : core.cmp.Ord Q) :
  alloc.collections.btree.map.BTreeMap K V A → Q → Result (Option V)

/-- [alloc::vec::into_iter::{impl core::iter::traits::iterator::Iterator<T> for alloc::vec::into_iter::IntoIter<T, A>}::fold]:
    Source: '/rustc/library/alloc/src/vec/into_iter.rs', lines 367:4-369:37
    Name pattern: [alloc::vec::into_iter::{core::iter::traits::iterator::Iterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::fold]
    Visibility: public -/
@[rust_fun
  "alloc::vec::into_iter::{core::iter::traits::iterator::Iterator<alloc::vec::into_iter::IntoIter<@T, @A>, @T>}::fold"]
axiom alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.fold
  {T : Type} {A : Type} {B : Type} {F : Type} (coreopsfunctionFnMutFPairBInst :
  core.ops.function.FnMut F (B × T) B) :
  alloc.vec.into_iter.IntoIter T → B → F → Result B

/-- [closure_mut_capture_nested::helpers::{closure}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:19-17:85 -/
@[reducible]
def helpers.closure (F : Type) := F

/-- [closure_mut_capture_nested::helpers::{closure#1}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 22:13-26:9 -/
@[reducible]
def helpers.closure_1 (F : Type) :=
  alloc.collections.btree.map.BTreeMap Std.Usize F Global × F ×
  helpers.closure F

/-- [closure_mut_capture_nested::helpers::{closure}::{closure}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:59-17:84 -/
@[reducible]
def helpers.closure.closure (F : Type) := F

/-- [closure_mut_capture_nested::helpers::{closure}::{impl core::ops::function::FnMut<(F, &'_1 F), F> for closure_mut_capture_nested::helpers::{closure}::{closure}<'_0, F>}::call_mut]:
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:59-17:84 -/
def helpers.closure.closure.Insts.CoreOpsFunctionFnMutPairFShared1FF.call_mut
  {F : Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst
  : core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F)
  (c : helpers.closure.closure F) (tupled_args : (F × F)) :
  Result (F × (helpers.closure.closure F))
  := do
  let (acc, x) := tupled_args
  let t ← coreopsarithMulInst.mul acc c
  let t1 ← coreopsarithAddInst.add t x
  ok (t1, c)

/-- [closure_mut_capture_nested::helpers::{closure}::{impl core::ops::function::FnOnce<(F, &'_1 F), F> for closure_mut_capture_nested::helpers::{closure}::{closure}<'_0, F>}::call_once]:
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:59-17:84 -/
def helpers.closure.closure.Insts.CoreOpsFunctionFnOncePairFShared1FF.call_once
  {F : Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst
  : core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F)
  (c : helpers.closure.closure F) (p : (F × F)) :
  Result F
  := do
  let (t, _) ←
    helpers.closure.closure.Insts.CoreOpsFunctionFnMutPairFShared1FF.call_mut
      coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
      coreopsarithMulInst c p
  ok t

/-- Trait implementation: [closure_mut_capture_nested::helpers::{closure}::{impl core::ops::function::FnOnce<(F, &'_1 F), F> for closure_mut_capture_nested::helpers::{closure}::{closure}<'_0, F>}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:59-17:84 -/
@[reducible]
def helpers.closure.closure.Insts.CoreOpsFunctionFnOncePairFShared1FF {F :
  Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst :
  core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) : core.ops.function.FnOnce
  (helpers.closure.closure F) (F × F) F := {
  call_once :=
    helpers.closure.closure.Insts.CoreOpsFunctionFnOncePairFShared1FF.call_once
    coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
    coreopsarithMulInst
}

/-- Trait implementation: [closure_mut_capture_nested::helpers::{closure}::{impl core::ops::function::FnMut<(F, &'_1 F), F> for closure_mut_capture_nested::helpers::{closure}::{closure}<'_0, F>}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:59-17:84 -/
@[reducible]
def helpers.closure.closure.Insts.CoreOpsFunctionFnMutPairFShared1FF {F : Type}
  (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst :
  core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) : core.ops.function.FnMut
  (helpers.closure.closure F) (F × F) F := {
  FnOnceInst :=
    helpers.closure.closure.Insts.CoreOpsFunctionFnOncePairFShared1FF
    coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
    coreopsarithMulInst
  call_mut :=
    helpers.closure.closure.Insts.CoreOpsFunctionFnMutPairFShared1FF.call_mut
    coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
    coreopsarithMulInst
}

/-- [closure_mut_capture_nested::helpers::{impl core::ops::function::Fn<(&'_1 [F],), F> for closure_mut_capture_nested::helpers::{closure}<'_0, F>}::call]:
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 17:19-17:85 -/
def helpers.closure.Insts.CoreOpsFunctionFnTupleShared1SliceF.call
  {F : Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst
  : core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) (c : helpers.closure F)
  (tupled_args : Slice F) :
  Result F
  := do
  let i ← core.slice.Slice.iter tupled_args
  let t ← coredefaultDefaultInst.default
  core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.fold
    (helpers.closure.closure.Insts.CoreOpsFunctionFnMutPairFShared1FF
    coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
    coreopsarithMulInst) i t c

/-- [closure_mut_capture_nested::helpers::{impl core::ops::function::FnMut<((usize, &'_4 alloc::vec::Vec<F>),), F> for closure_mut_capture_nested::helpers::{closure#1}<'_0, '_1, '_2, '_3, F>}::call_mut]:
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 22:13-26:9 -/
def
  helpers.closure_1.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared4VecF.call_mut
  {F : Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst
  : core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) (c : helpers.closure_1 F)
  (tupled_args : (Std.Usize × (alloc.vec.Vec F))) :
  Result (F × (helpers.closure_1 F) × (helpers.closure_1 F →
    helpers.closure_1 F))
  := do
  let (bm, t, c1) := c
  let (j, chunk) := tupled_args
  let o ←
    alloc.collections.btree.map.BTreeMap.get
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone
      (core.borrow.Borrow.Blanket Std.Usize) core.cmp.OrdUsize
      core.cmp.OrdUsize bm j
  let o1 ← core.option.OptionShared0T.copied coremarkerCopyInst o
  let h ← core.option.Option.unwrap_or_default coredefaultDefaultInst o1
  let t1 ← coreopsarithAddInst.add t h
  let s := alloc.vec.Vec.deref chunk
  let t2 ←
    helpers.closure.Insts.CoreOpsFunctionFnTupleShared1SliceF.call
      coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
      coreopsarithMulInst c1 s
  let t3 ← coreopsarithMulInst.mul h t2
  let back := fun c2 => let (_, t4, _) := c2
                        (bm, t4, c1)
  ok (t3, (bm, t1, c1), back)

/-- [closure_mut_capture_nested::helpers::{impl core::ops::function::FnOnce<((usize, &'_4 alloc::vec::Vec<F>),), F> for closure_mut_capture_nested::helpers::{closure#1}<'_0, '_1, '_2, '_3, F>}::call_once]:
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 22:13-26:9 -/
def
  helpers.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared4VecF.call_once
  {F : Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst
  : core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) (c : helpers.closure_1 F)
  (p : (Std.Usize × (alloc.vec.Vec F))) :
  Result (F × (helpers.closure_1 F))
  := do
  let (bm, t, c1) := c
  let (t1, c2, call_mut_back) ←
    helpers.closure_1.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared4VecF.call_mut
      coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
      coreopsarithMulInst (bm, t, c1) p
  let (_, t2, _) := call_mut_back c2
  ok (t1, (bm, t2, c1))

/-- Trait implementation: [closure_mut_capture_nested::helpers::{impl core::ops::function::FnOnce<((usize, &'_4 alloc::vec::Vec<F>),), F> for closure_mut_capture_nested::helpers::{closure#1}<'_0, '_1, '_2, '_3, F>}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 22:13-26:9 -/
@[reducible]
def helpers.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared4VecF {F :
  Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst :
  core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) : core.ops.function.FnOnce
  (helpers.closure_1 F) (Std.Usize × (alloc.vec.Vec F)) (F ×
  (helpers.closure_1 F)) := {
  call_once := fun x0 x1 =>
    Bind.bind ((helpers.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared4VecF.call_once
    coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
    coreopsarithMulInst) x0 x1) (fun (out, b0) => ok (out, b0))
}

/-- Trait implementation: [closure_mut_capture_nested::helpers::{impl core::ops::function::FnMut<((usize, &'_4 alloc::vec::Vec<F>),), F> for closure_mut_capture_nested::helpers::{closure#1}<'_0, '_1, '_2, '_3, F>}]
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 22:13-26:9 -/
@[reducible]
def helpers.closure_1.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared4VecF {F :
  Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst :
  core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F) : core.ops.function.FnMut
  (helpers.closure_1 F) (Std.Usize × (alloc.vec.Vec F)) F := {
  FnOnceInst :=
    helpers.closure_1.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared4VecF
    coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
    coreopsarithMulInst
  call_mut := fun _ _ => Result.fail Error.undef
}

/-- [closure_mut_capture_nested::helpers]:
    Source: 'tests/src/closure-mut-capture-nested.rs', lines 12:0-29:1
    Visibility: public -/
def helpers
  {F : Type} (coremarkerCopyInst : core.marker.Copy F) (coredefaultDefaultInst
  : core.default.Default F) (coreopsarithAddInst : core.ops.arith.Add F F F)
  (coreopsarithMulInst : core.ops.arith.Mul F F F)
  (chunks : Slice (alloc.vec.Vec F))
  (evals : alloc.collections.btree.map.BTreeMap Std.Usize F Global) (theta : F)
  :
  Result (core.iter.adapters.chain.Chain (core.iter.sources.once.Once F)
    (alloc.vec.into_iter.IntoIter F))
  := do
  let sum ← coredefaultDefaultInst.default
  let i ← core.slice.Slice.iter chunks
  let e ←
    core.iter.traits.iterator.Iterator.enumerate.trait_default
      (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec F)) i
  let (m, map_back) ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec F)))
      (helpers.closure_1.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared4VecF
      coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
      coreopsarithMulInst) e (evals, sum, theta)
  let (out, m1) ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec F)))
      (helpers.closure_1.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared4VecF
      coremarkerCopyInst coredefaultDefaultInst coreopsarithAddInst
      coreopsarithMulInst)) (core.iter.traits.collect.FromIteratorVec F) m
  let (_, sum1, _) := map_back m1
  let o ← core.iter.sources.once.once sum1
  core.iter.traits.iterator.Iterator.chain.default
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator F)
    (core.iter.traits.collect.IntoIteratorVec F) o out

end closure_mut_capture_nested
