-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ctor_closure_adapter]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace ctor_closure_adapter

/-- [ctor_closure_adapter::Label]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 9:0-12:1
    Visibility: public -/
@[discriminant isize]
inductive Label where
| Fixed : Std.Usize → Label
| NoLabel : Label

/-- [ctor_closure_adapter::Label::Fixed]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 10:4-10:16 -/
def Label.Fixed.constructor (i : Std.Usize) : Result Label := do
  ok (Label.Fixed i)

/-- [ctor_closure_adapter::Label::{impl core::ops::function::FnMut<(usize,), ctor_closure_adapter::Label> for ctor_closure_adapter::Label::Fixed}::call_mut]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 10:4-10:16 -/
def Label.Fixed.Insts.CoreOpsFunctionFnMutTupleUsizeLabel.call_mut
  (state : Std.Usize → Result Label) (args : Std.Usize) :
  Result (Label × (Std.Usize → Result Label))
  := do
  let l ← Label.Fixed.constructor args
  ok (l, state)

/-- [ctor_closure_adapter::Label::{impl core::ops::function::FnOnce<(usize,), ctor_closure_adapter::Label> for ctor_closure_adapter::Label::Fixed}::call_once]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 10:4-10:16 -/
def Label.Fixed.Insts.CoreOpsFunctionFnOnceTupleUsizeLabel.call_once
  (state : Std.Usize → Result Label) (args : Std.Usize) : Result Label := do
  Label.Fixed.constructor args

/-- Trait implementation: [ctor_closure_adapter::Label::{impl core::ops::function::FnOnce<(usize,), ctor_closure_adapter::Label> for ctor_closure_adapter::Label::Fixed}]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 10:4-10:16 -/
@[reducible]
def Label.Fixed.Insts.CoreOpsFunctionFnOnceTupleUsizeLabel :
  core.ops.function.FnOnce (Std.Usize → Result Label) Std.Usize Label := {
  call_once := Label.Fixed.Insts.CoreOpsFunctionFnOnceTupleUsizeLabel.call_once
}

/-- Trait implementation: [ctor_closure_adapter::Label::{impl core::ops::function::FnMut<(usize,), ctor_closure_adapter::Label> for ctor_closure_adapter::Label::Fixed}]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 10:4-10:16 -/
@[reducible]
def Label.Fixed.Insts.CoreOpsFunctionFnMutTupleUsizeLabel :
  core.ops.function.FnMut (Std.Usize → Result Label) Std.Usize Label := {
  FnOnceInst := Label.Fixed.Insts.CoreOpsFunctionFnOnceTupleUsizeLabel
  call_mut := Label.Fixed.Insts.CoreOpsFunctionFnMutTupleUsizeLabel.call_mut
}

/-- [ctor_closure_adapter::Columns]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 14:0-17:1
    Visibility: public -/
structure Columns where
  n : Std.Usize
  simple : alloc.vec.Vec Std.Usize

/-- [ctor_closure_adapter::{ctor_closure_adapter::Columns}::is_simple]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 20:4-22:5 -/
def Columns.is_simple (self : Columns) (i : Std.Usize) : Result Bool := do
  let i1 := alloc.vec.Vec.len (Columns.simple self)
  ok (i1 > i)

/-- [ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{closure}]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 25:27-25:50 -/
@[reducible]
def Columns.first_fixed.closure := Columns

/-- [ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{impl core::ops::function::FnMut<(&'_1 usize,), bool> for ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{closure}<'_0>}::call_mut]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 25:27-25:50 -/
def
  Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool.call_mut
  (c : Columns.first_fixed.closure) (tupled_args : Std.Usize) :
  Result (Bool × Columns.first_fixed.closure)
  := do
  let b ← Columns.is_simple c tupled_args
  ok (¬ b, c)

/-- [ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{impl core::ops::function::FnOnce<(&'_1 usize,), bool> for ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{closure}<'_0>}::call_once]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 25:27-25:50 -/
def
  Columns.first_fixed.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizeBool.call_once
  (c : Columns.first_fixed.closure) (i : Std.Usize) : Result Bool := do
  let (b, _) ←
    Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool.call_mut
      c i
  ok b

/-- Trait implementation: [ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{impl core::ops::function::FnOnce<(&'_1 usize,), bool> for ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{closure}<'_0>}]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 25:27-25:50 -/
@[reducible]
def
  Columns.first_fixed.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizeBool
  : core.ops.function.FnOnce Columns.first_fixed.closure Std.Usize Bool := {
  call_once :=
    Columns.first_fixed.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizeBool.call_once
}

/-- Trait implementation: [ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{impl core::ops::function::FnMut<(&'_1 usize,), bool> for ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed::{closure}<'_0>}]
    Source: 'tests/src/ctor-closure-adapter.rs', lines 25:27-25:50 -/
@[reducible]
def Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool
  : core.ops.function.FnMut Columns.first_fixed.closure Std.Usize Bool := {
  FnOnceInst :=
    Columns.first_fixed.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizeBool
  call_mut :=
    Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool.call_mut
}

/-- [ctor_closure_adapter::{ctor_closure_adapter::Columns}::first_fixed]:
    Source: 'tests/src/ctor-closure-adapter.rs', lines 24:4-26:5
    Visibility: public -/
def Columns.first_fixed (self : Columns) : Result (Option Label) := do
  let f ←
    core.iter.traits.iterator.Iterator.filter.default
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepUsize)
      Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool
      { start := 0#usize, «end» := (Columns.n self) } self
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.adapters.filter.Filter.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepUsize)
      Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool)
      Label.Fixed.Insts.CoreOpsFunctionFnMutTupleUsizeLabel f
      (Label.Fixed.constructor)
  let (o, _) ←
    core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
      (core.iter.adapters.filter.Filter.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepUsize)
      Columns.first_fixed.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizeBool)
      Label.Fixed.Insts.CoreOpsFunctionFnMutTupleUsizeLabel m
  ok o

end ctor_closure_adapter
