-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_mut_args]: function definitions
module
public import Aeneas
public import ClosureMutArgs.Types
public import ClosureMutArgs.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace closure_mut_args

/-- [closure_mut_args::incr::{impl core::ops::function::FnMut<(&'_0 mut u32,), ()> for closure_mut_args::incr::{closure}}::call_mut]:
    Source: 'tests/src/closure-mut-args.rs', lines 16:12-16:38 -/
def incr.closure.Insts.CoreOpsFunctionFnMutTupleMut0U32Tuple.call_mut
  (c : incr.closure) (tupled_args : Std.U32) :
  Result (Std.U32 × incr.closure)
  := do
  let x ← lift (core.num.U32.wrapping_add tupled_args 1#u32)
  ok (x, c)

/-- [closure_mut_args::incr::{impl core::ops::function::FnOnce<(&'_0 mut u32,), ()> for closure_mut_args::incr::{closure}}::call_once]:
    Source: 'tests/src/closure-mut-args.rs', lines 16:12-16:38 -/
def incr.closure.Insts.CoreOpsFunctionFnOnceTupleMut0U32Tuple.call_once
  (c : incr.closure) (i : Std.U32) : Result Std.U32 := do
  let (i1, _) ←
    incr.closure.Insts.CoreOpsFunctionFnMutTupleMut0U32Tuple.call_mut c i
  ok i1

/-- Trait implementation: [closure_mut_args::incr::{impl core::ops::function::FnOnce<(&'_0 mut u32,), ()> for closure_mut_args::incr::{closure}}]
    Source: 'tests/src/closure-mut-args.rs', lines 16:12-16:38 -/
@[reducible]
def incr.closure.Insts.CoreOpsFunctionFnOnceTupleMut0U32Tuple :
  core.ops.function.FnOnce incr.closure Std.U32 (Unit × Std.U32) := {
  call_once := fun x0 x1 =>
    Bind.bind ((incr.closure.Insts.CoreOpsFunctionFnOnceTupleMut0U32Tuple.call_once) x0 x1)
    (fun b0 => ok ((), b0))
}

/-- Trait implementation: [closure_mut_args::incr::{impl core::ops::function::FnMut<(&'_0 mut u32,), ()> for closure_mut_args::incr::{closure}}]
    Source: 'tests/src/closure-mut-args.rs', lines 16:12-16:38 -/
@[reducible]
def incr.closure.Insts.CoreOpsFunctionFnMutTupleMut0U32Tuple :
  core.ops.function.FnMut incr.closure Std.U32 (Unit × Std.U32) := {
  FnOnceInst := incr.closure.Insts.CoreOpsFunctionFnOnceTupleMut0U32Tuple
  call_mut := fun x0 x1 =>
    Bind.bind ((incr.closure.Insts.CoreOpsFunctionFnMutTupleMut0U32Tuple.call_mut) x0 x1)
    (fun (b0, self') => ok (((), b0), self'))
}

/-- [closure_mut_args::incr]:
    Source: 'tests/src/closure-mut-args.rs', lines 15:0-17:1
    Visibility: public -/
def incr (s : Slice Std.U32) : Result (Slice Std.U32) := do
  each incr.closure.Insts.CoreOpsFunctionFnMutTupleMut0U32Tuple s ()

end closure_mut_args
