-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_mut_args]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
module
public import Aeneas
public import ClosureMutArgs.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open closure_mut_args

/-- [closure_mut_args::each]:
    Source: 'tests/src/closure-mut-args.rs', lines 9:0-13:1
    Visibility: public -/
axiom each
  {F : Type} (coreopsfunctionFnMutFTupleMut0U32TupleInst :
  core.ops.function.FnMut F Std.U32 Unit) :
  Slice Std.U32 → F → Result (Slice Std.U32)

