-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_mut_args]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closure_mut_args

/-- [closure_mut_args::incr::{closure}]
    Source: 'tests/src/closure-mut-args.rs', lines 16:12-16:38 -/
@[reducible]
def incr.closure := Unit

end closure_mut_args
