-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [slice_iter_find]: function definitions
module
public import Aeneas
public import SliceIterFind.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace slice_iter_find

/-- [slice_iter_find::find_even::{impl core::ops::function::FnMut<(&'_0 &'_1 u32,), bool> for slice_iter_find::find_even::{closure}}::call_mut]:
    Source: 'tests/src/slice-iter-find.rs', lines 10:18-10:34 -/
def
  find_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
  (c : find_even.closure) (tupled_args : Std.U32) :
  Result (Bool × find_even.closure)
  := do
  let i ← tupled_args % 2#u32
  ok (i = 0#u32, c)

/-- [slice_iter_find::find_even::{impl core::ops::function::FnOnce<(&'_0 &'_1 u32,), bool> for slice_iter_find::find_even::{closure}}::call_once]:
    Source: 'tests/src/slice-iter-find.rs', lines 10:18-10:34 -/
def
  find_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool.call_once
  (c : find_even.closure) (i : Std.U32) : Result Bool := do
  let (b, _) ←
    find_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
      c i
  ok b

/-- Trait implementation: [slice_iter_find::find_even::{impl core::ops::function::FnOnce<(&'_0 &'_1 u32,), bool> for slice_iter_find::find_even::{closure}}]
    Source: 'tests/src/slice-iter-find.rs', lines 10:18-10:34 -/
@[reducible]
def find_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool :
  core.ops.function.FnOnce find_even.closure Std.U32 Bool := {
  call_once :=
    find_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool.call_once
}

/-- Trait implementation: [slice_iter_find::find_even::{impl core::ops::function::FnMut<(&'_0 &'_1 u32,), bool> for slice_iter_find::find_even::{closure}}]
    Source: 'tests/src/slice-iter-find.rs', lines 10:18-10:34 -/
@[reducible]
def find_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool :
  core.ops.function.FnMut find_even.closure Std.U32 Bool := {
  FnOnceInst :=
    find_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool
  call_mut :=
    find_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
}

/-- [slice_iter_find::find_even]:
    Source: 'tests/src/slice-iter-find.rs', lines 9:0-11:1
    Visibility: public -/
def find_even (s : Slice Std.U32) : Result (Option Std.U32) := do
  let i ← core.slice.Slice.iter s
  let (o, _) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.find
      find_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool i
      ()
  core.option.OptionShared0T.copied core.marker.CopyU32 o

/-- [slice_iter_find::bump_first_even::{impl core::ops::function::FnMut<(&'_0 &'_1 mut u32,), bool> for slice_iter_find::bump_first_even::{closure}}::call_mut]:
    Source: 'tests/src/slice-iter-find.rs', lines 14:39-14:55 -/
def
  bump_first_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Mut1U32Bool.call_mut
  (c : bump_first_even.closure) (tupled_args : Std.U32) :
  Result (Bool × bump_first_even.closure)
  := do
  let i ← tupled_args % 2#u32
  ok (i = 0#u32, c)

/-- [slice_iter_find::bump_first_even::{impl core::ops::function::FnOnce<(&'_0 &'_1 mut u32,), bool> for slice_iter_find::bump_first_even::{closure}}::call_once]:
    Source: 'tests/src/slice-iter-find.rs', lines 14:39-14:55 -/
def
  bump_first_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Mut1U32Bool.call_once
  (c : bump_first_even.closure) (i : Std.U32) : Result Bool := do
  let (b, _) ←
    bump_first_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Mut1U32Bool.call_mut
      c i
  ok b

/-- Trait implementation: [slice_iter_find::bump_first_even::{impl core::ops::function::FnOnce<(&'_0 &'_1 mut u32,), bool> for slice_iter_find::bump_first_even::{closure}}]
    Source: 'tests/src/slice-iter-find.rs', lines 14:39-14:55 -/
@[reducible]
def bump_first_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Mut1U32Bool
  : core.ops.function.FnOnce bump_first_even.closure Std.U32 Bool := {
  call_once :=
    bump_first_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Mut1U32Bool.call_once
}

/-- Trait implementation: [slice_iter_find::bump_first_even::{impl core::ops::function::FnMut<(&'_0 &'_1 mut u32,), bool> for slice_iter_find::bump_first_even::{closure}}]
    Source: 'tests/src/slice-iter-find.rs', lines 14:39-14:55 -/
@[reducible]
def bump_first_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Mut1U32Bool :
  core.ops.function.FnMut bump_first_even.closure Std.U32 Bool := {
  FnOnceInst :=
    bump_first_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Mut1U32Bool
  call_mut :=
    bump_first_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Mut1U32Bool.call_mut
}

/-- [slice_iter_find::bump_first_even]:
    Source: 'tests/src/slice-iter-find.rs', lines 13:0-17:1
    Visibility: public -/
def bump_first_even (s : Slice Std.U32) : Result (Slice Std.U32) := do
  let (im, iter_mut_back) ← core.slice.Slice.iter_mut s
  let (o, im1, find_back) ←
    core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT.find
      bump_first_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Mut1U32Bool
      im ()
  match o with
  | none => let im2 := find_back im1 none
            ok (iter_mut_back im2)
  | some x =>
    let x1 ← x + 1#u32
    let im2 := find_back im1 (some x1)
    ok (iter_mut_back im2)

end slice_iter_find
