-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [assoc_type_constraint]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace assoc_type_constraint

/-- Trait declaration: [assoc_type_constraint::Proj]
    Source: 'tests/src/assoc-type-constraint.rs', lines 8:0-11:1
    Visibility: public -/
structure Proj (Self : Type) (Self_Scalar : Type) (Self_Affine : Type) where
  coremarkerCopyInst : core.marker.Copy Self_Scalar

/-- Trait declaration: [assoc_type_constraint::Affine]
    Source: 'tests/src/assoc-type-constraint.rs', lines 13:0-18:1
    Visibility: public -/
structure Affine (Self : Type) (Self_ScalarA : Type) (Self_ProjA : Type) where
  coremarkerCopyInst : core.marker.Copy Self_ScalarA
  ProjInst : Proj Self_ProjA Self_ScalarA Self
  get : Self → Result Self_ScalarA

/-- [assoc_type_constraint::scalar]:
    Source: 'tests/src/assoc-type-constraint.rs', lines 20:0-22:1
    Visibility: public -/
def scalar
  {F : Type} {A : Type} {Clause1_ProjA : Type} (coremarkerCopyInst :
  core.marker.Copy F) (AffineInst : Affine A F Clause1_ProjA) (a : A) :
  Result F
  := do
  AffineInst.get a

end assoc_type_constraint
