-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [assoc_type_diamond]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace assoc_type_diamond

/-- Trait declaration: [assoc_type_diamond::Base]
    Source: 'tests/src/assoc-type-diamond.rs', lines 4:0-6:1
    Visibility: public -/
structure Base (Self : Type) (Self_Repr : Type) where
  coremarkerCopyInst : core.marker.Copy Self_Repr

/-- Trait declaration: [assoc_type_diamond::Left]
    Source: 'tests/src/assoc-type-diamond.rs', lines 7:0-7:23
    Visibility: public -/
structure Left (Self : Type) (Self_Clause0_Repr : Type) where
  BaseInst : Base Self Self_Clause0_Repr

/-- Trait declaration: [assoc_type_diamond::Right]
    Source: 'tests/src/assoc-type-diamond.rs', lines 8:0-8:24
    Visibility: public -/
structure Right (Self : Type) (Self_Clause0_Repr : Type) where
  BaseInst : Base Self Self_Clause0_Repr

/-- [assoc_type_diamond::via_left]:
    Source: 'tests/src/assoc-type-diamond.rs', lines 10:0-12:1
    Visibility: public -/
def via_left
  {F : Type} {Clause0_Clause0_Repr : Type} (LeftInst : Left F
  Clause0_Clause0_Repr) (r : Clause0_Clause0_Repr) :
  Result Clause0_Clause0_Repr
  := do
  ok r

/-- [assoc_type_diamond::via_right]:
    Source: 'tests/src/assoc-type-diamond.rs', lines 14:0-16:1
    Visibility: public -/
def via_right
  {F : Type} {Clause0_Clause0_Repr : Type} (RightInst : Right F
  Clause0_Clause0_Repr) (r : Clause0_Clause0_Repr) :
  Result Clause0_Clause0_Repr
  := do
  ok r

/-- [assoc_type_diamond::both]:
    Source: 'tests/src/assoc-type-diamond.rs', lines 19:0-21:1
    Visibility: public -/
def both
  {F : Type} {Clause0_Clause0_Repr : Type} (Clause1_Clause0_Repr : Type)
  (LeftInst : Left F Clause0_Clause0_Repr) (RightInst : Right F
  Clause0_Clause0_Repr) (r : Clause0_Clause0_Repr) :
  Result Clause0_Clause0_Repr
  := do
  let t ← via_left LeftInst r
  via_right RightInst t

end assoc_type_diamond
