-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [btree]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace btree

/-- Trait implementation: [core::cmp::impls::{impl core::cmp::Eq for &'_0 A}]
    Source: '/rustc/library/core/src/cmp.rs', lines 2525:4-2525:61
    Name pattern: [core::cmp::Eq<&'0 @A>] -/
@[reducible, rust_trait_impl "core::cmp::Eq<&'0 @A>"]
def Shared0A.Insts.CoreCmpEq {A : Type} (EqInst : core.cmp.Eq A) : core.cmp.Eq
  A := {
  partialEqInst := core.cmp.PartialEqShared EqInst.partialEqInst
}

/-- Trait implementation: [core::cmp::impls::{impl core::cmp::Ord for &'_0 A}]
    Source: '/rustc/library/core/src/cmp.rs', lines 2514:4-2516:23
    Name pattern: [core::cmp::Ord<&'0 @A>] -/
@[reducible, rust_trait_impl "core::cmp::Ord<&'0 @A>"]
def Shared0A.Insts.CoreCmpOrd {A : Type} (OrdInst : core.cmp.Ord A) :
  core.cmp.Ord A := {
  eqInst := Shared0A.Insts.CoreCmpEq OrdInst.eqInst
  partialOrdInst := core.cmp.PartialOrdShared OrdInst.partialOrdInst
  cmp := core.cmp.impls.OrdShared.cmp OrdInst
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 28:12-28:74
    Name pattern: [core::cmp::PartialEq<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialEqPair {U : Type} {T : Type} (cmpPartialEqInst :
  core.cmp.PartialEq U U) (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (U × T) (U × T) := {
  eq := Pair.Insts.CoreCmpPartialEqPair.eq cmpPartialEqInst cmpPartialEqInst1
}

/-- Trait implementation: [core::tuple::{impl core::cmp::Eq for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 44:12-44:60
    Name pattern: [core::cmp::Eq<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::Eq<(@U, @T)>"]
def Pair.Insts.CoreCmpEq {U : Type} {T : Type} (cmpEqInst : core.cmp.Eq U)
  (cmpEqInst1 : core.cmp.Eq T) : core.cmp.Eq (U × T) := {
  partialEqInst := Pair.Insts.CoreCmpPartialEqPair cmpEqInst.partialEqInst
    cmpEqInst1.partialEqInst
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialOrd<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 66:12-66:76
    Name pattern: [core::cmp::PartialOrd<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialOrd<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialOrdPair {U : Type} {T : Type} (cmpPartialOrdInst :
  core.cmp.PartialOrd U U) (cmpPartialOrdInst1 : core.cmp.PartialOrd T T) :
  core.cmp.PartialOrd (U × T) (U × T) := {
  partialEqInst := Pair.Insts.CoreCmpPartialEqPair
    cmpPartialOrdInst.partialEqInst cmpPartialOrdInst1.partialEqInst
  partial_cmp := Pair.Insts.CoreCmpPartialOrdPair.partial_cmp cmpPartialOrdInst
    cmpPartialOrdInst1
}

/-- Trait implementation: [core::tuple::{impl core::cmp::Ord for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 111:12-111:62
    Name pattern: [core::cmp::Ord<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::Ord<(@U, @T)>"]
def Pair.Insts.CoreCmpOrd {U : Type} {T : Type} (cmpOrdInst : core.cmp.Ord U)
  (cmpOrdInst1 : core.cmp.Ord T) : core.cmp.Ord (U × T) := {
  eqInst := Pair.Insts.CoreCmpEq cmpOrdInst.eqInst cmpOrdInst1.eqInst
  partialOrdInst := Pair.Insts.CoreCmpPartialOrdPair cmpOrdInst.partialOrdInst
    cmpOrdInst1.partialOrdInst
  cmp := Pair.Insts.CoreCmpOrd.cmp cmpOrdInst cmpOrdInst1
}

/-- [btree::insert_twice]:
    Source: 'tests/src/btree.rs', lines 9:0-14:1
    Visibility: public -/
def insert_twice
  (k : Std.U32) :
  Result ((Option Std.U32) × (Option Std.U32) × (Option Std.U32))
  := do
  let m ← alloc.collections.btree.map.BTreeMapKVGlobal.new Std.U32 Std.U32
  let (a, m1) ←
    alloc.collections.btree.map.BTreeMap.insert
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone core.cmp.OrdU32 m k
      1#u32
  let (b, m2) ←
    alloc.collections.btree.map.BTreeMap.insert
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone core.cmp.OrdU32 m1 k
      2#u32
  let o ←
    alloc.collections.btree.map.BTreeMap.get
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone
      (core.borrow.Borrow.Blanket Std.U32) core.cmp.OrdU32 core.cmp.OrdU32 m2 k
  let o1 ← core.option.OptionShared0T.copied core.marker.CopyU32 o
  ok (a, b, o1)

/-- [btree::lookup]:
    Source: 'tests/src/btree.rs', lines 16:0-18:1
    Visibility: public -/
def lookup
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global)
  (k : Std.U32) :
  Result (Option Std.U32)
  := do
  let o ←
    alloc.collections.btree.map.BTreeMap.get
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone
      (core.borrow.Borrow.Blanket Std.U32) core.cmp.OrdU32 core.cmp.OrdU32 m k
  core.option.OptionShared0T.copied core.marker.CopyU32 o

/-- [btree::index]:
    Source: 'tests/src/btree.rs', lines 20:0-22:1
    Visibility: public -/
def index
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global)
  (k : Std.U32) :
  Result Std.U32
  := do
  alloc.collections.btree.map.BTreeMap.Insts.CoreOpsIndexIndexShared0QV.index
    alloc.alloc.Global.Insts.CoreAllocAllocatorClone
    (core.borrow.Borrow.Blanket Std.U32) core.cmp.OrdU32 core.cmp.OrdU32 m k

/-- [btree::histogram]: loop body 0:
    Source: 'tests/src/btree.rs', lines 27:4-29:5
    Visibility: public -/
@[rust_loop_body]
def histogram_loop.body
  (iter : core.slice.iter.Iter Std.U32)
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U32) ×
    (alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global))
    (alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done m)
  | some x =>
    let (e, entry_back) ←
      alloc.collections.btree.map.BTreeMap.entry
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone core.cmp.OrdU32 m x
    let (i, or_insert_back) ←
      alloc.collections.btree.map.entry.Entry.or_insert core.cmp.OrdU32
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone e 0#u32
    let i1 ← i + 1#u32
    let e1 := or_insert_back i1
    let bm := entry_back e1
    ok (cont (iter1, bm))

/-- [btree::histogram]: loop 0:
    Source: 'tests/src/btree.rs', lines 27:4-29:5
    Visibility: public -/
@[rust_loop]
def histogram_loop
  (iter : core.slice.iter.Iter Std.U32)
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global) :
  Result (alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global)
  := do
  loop
    (fun (iter1, m1) => histogram_loop.body iter1 m1)
    (iter, m)

/-- [btree::histogram]:
    Source: 'tests/src/btree.rs', lines 25:0-31:1
    Visibility: public -/
def histogram
  (v : Slice Std.U32) :
  Result (alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global)
  := do
  let m ← alloc.collections.btree.map.BTreeMapKVGlobal.new Std.U32 Std.U32
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter v
  histogram_loop iter m

/-- [btree::flatten]: loop body 0:
    Source: 'tests/src/btree.rs', lines 36:4-39:5
    Visibility: public -/
@[rust_loop_body]
def flatten_loop.body
  (iter : alloc.collections.btree.map.IntoIter Std.U32 Std.U32 Global)
  (out : alloc.vec.Vec Std.U32) :
  Result (ControlFlow ((alloc.collections.btree.map.IntoIter Std.U32 Std.U32
    Global) × (alloc.vec.Vec Std.U32)) (alloc.vec.Vec Std.U32))
  := do
  let (o, iter1) ←
    alloc.collections.btree.map.IntoIter.Insts.CoreIterTraitsIteratorIteratorPair.next
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone iter
  match o with
  | none => ok (done out)
  | some p =>
    let (k, v) := p
    let out1 ← alloc.vec.Vec.push out k
    let out2 ← alloc.vec.Vec.push out1 v
    ok (cont (iter1, out2))

/-- [btree::flatten]: loop 0:
    Source: 'tests/src/btree.rs', lines 36:4-39:5
    Visibility: public -/
@[rust_loop]
def flatten_loop
  (iter : alloc.collections.btree.map.IntoIter Std.U32 Std.U32 Global)
  (out : alloc.vec.Vec Std.U32) :
  Result (alloc.vec.Vec Std.U32)
  := do
  loop
    (fun (iter1, out1) => flatten_loop.body iter1 out1)
    (iter, out)

/-- [btree::flatten]:
    Source: 'tests/src/btree.rs', lines 34:0-41:1
    Visibility: public -/
def flatten
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global) :
  Result (alloc.vec.Vec Std.U32)
  := do
  let iter ←
    alloc.collections.btree.map.BTreeMap.Insts.CoreIterTraitsCollectIntoIteratorPairIntoIter.into_iter
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone m
  flatten_loop iter (alloc.vec.Vec.new Std.U32)

/-- [btree::largest::{closure}]
    Source: 'tests/src/btree.rs', lines 44:23-44:40 -/
@[reducible]
def largest.closure := Unit

/-- [btree::largest::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 u32),), (u32, u32)> for btree::largest::{closure}}::call_once]:
    Source: 'tests/src/btree.rs', lines 44:23-44:40 -/
def
  largest.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32.call_once
  (c : largest.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × Std.U32)
  := do
  ok tupled_args

/-- Trait implementation: [btree::largest::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 u32),), (u32, u32)> for btree::largest::{closure}}]
    Source: 'tests/src/btree.rs', lines 44:23-44:40 -/
@[reducible]
def
  largest.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32
  : core.ops.function.FnOnce largest.closure (Std.U32 × Std.U32) (Std.U32 ×
  Std.U32) := {
  call_once :=
    largest.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32.call_once
}

/-- [btree::largest]:
    Source: 'tests/src/btree.rs', lines 43:0-45:1
    Visibility: public -/
def largest
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global) :
  Result (Option (Std.U32 × Std.U32))
  := do
  let i ←
    alloc.collections.btree.map.BTreeMap.iter
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone m
  let o ←
    alloc.collections.btree.map.Iter.Insts.CoreIterTraitsIteratorIteratorPairSharedAKSharedAV.max
      (Pair.Insts.CoreCmpOrd (Shared0A.Insts.CoreCmpOrd core.cmp.OrdU32)
      (Shared0A.Insts.CoreCmpOrd core.cmp.OrdU32)) i
  core.option.Option.map
    largest.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32
    o ()

/-- [btree::from_pairs::{closure}]
    Source: 'tests/src/btree.rs', lines 48:17-48:23 -/
@[reducible]
def from_pairs.closure := Unit

/-- [btree::from_pairs::{impl core::ops::function::FnMut<(&'_0 (u32, u32),), (u32, u32)> for btree::from_pairs::{closure}}::call_mut]:
    Source: 'tests/src/btree.rs', lines 48:17-48:23 -/
def
  from_pairs.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU32U32PairU32U32.call_mut
  (c : from_pairs.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result ((Std.U32 × Std.U32) × from_pairs.closure)
  := do
  ok (tupled_args, c)

/-- [btree::from_pairs::{impl core::ops::function::FnOnce<(&'_0 (u32, u32),), (u32, u32)> for btree::from_pairs::{closure}}::call_once]:
    Source: 'tests/src/btree.rs', lines 48:17-48:23 -/
def
  from_pairs.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU32U32PairU32U32.call_once
  (c : from_pairs.closure) (p : (Std.U32 × Std.U32)) :
  Result (Std.U32 × Std.U32)
  := do
  let (p1, _) ←
    from_pairs.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU32U32PairU32U32.call_mut
      c p
  ok p1

/-- Trait implementation: [btree::from_pairs::{impl core::ops::function::FnOnce<(&'_0 (u32, u32),), (u32, u32)> for btree::from_pairs::{closure}}]
    Source: 'tests/src/btree.rs', lines 48:17-48:23 -/
@[reducible]
def
  from_pairs.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU32U32PairU32U32
  : core.ops.function.FnOnce from_pairs.closure (Std.U32 × Std.U32) (Std.U32
  × Std.U32) := {
  call_once :=
    from_pairs.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU32U32PairU32U32.call_once
}

/-- Trait implementation: [btree::from_pairs::{impl core::ops::function::FnMut<(&'_0 (u32, u32),), (u32, u32)> for btree::from_pairs::{closure}}]
    Source: 'tests/src/btree.rs', lines 48:17-48:23 -/
@[reducible]
def
  from_pairs.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU32U32PairU32U32
  : core.ops.function.FnMut from_pairs.closure (Std.U32 × Std.U32) (Std.U32 ×
  Std.U32) := {
  FnOnceInst :=
    from_pairs.closure.Insts.CoreOpsFunctionFnOnceTupleShared0PairU32U32PairU32U32
  call_mut :=
    from_pairs.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU32U32PairU32U32.call_mut
}

/-- [btree::from_pairs]:
    Source: 'tests/src/btree.rs', lines 47:0-49:1
    Visibility: public -/
def from_pairs
  (v : Slice (Std.U32 × Std.U32)) :
  Result (alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global)
  := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter (Std.U32 × Std.U32))
      from_pairs.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU32U32PairU32U32
      i ()
  core.iter.traits.iterator.Iterator.collect.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter (Std.U32 × Std.U32))
    from_pairs.closure.Insts.CoreOpsFunctionFnMutTupleShared0PairU32U32PairU32U32)
    (alloc.collections.btree.map.BTreeMapKVGlobal.Insts.CoreIterTraitsCollectFromIteratorPair
    Std.U32 core.cmp.OrdU32) m

/-- [btree::sorted_unique::{closure}]
    Source: 'tests/src/btree.rs', lines 52:40-52:46 -/
@[reducible]
def sorted_unique.closure := Unit

/-- [btree::sorted_unique::{impl core::ops::function::FnMut<(&'_0 u32,), u32> for btree::sorted_unique::{closure}}::call_mut]:
    Source: 'tests/src/btree.rs', lines 52:40-52:46 -/
def sorted_unique.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
  (c : sorted_unique.closure) (tupled_args : Std.U32) :
  Result (Std.U32 × sorted_unique.closure)
  := do
  ok (tupled_args, c)

/-- [btree::sorted_unique::{impl core::ops::function::FnOnce<(&'_0 u32,), u32> for btree::sorted_unique::{closure}}::call_once]:
    Source: 'tests/src/btree.rs', lines 52:40-52:46 -/
def
  sorted_unique.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32.call_once
  (c : sorted_unique.closure) (i : Std.U32) : Result Std.U32 := do
  let (i1, _) ←
    sorted_unique.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
      c i
  ok i1

/-- Trait implementation: [btree::sorted_unique::{impl core::ops::function::FnOnce<(&'_0 u32,), u32> for btree::sorted_unique::{closure}}]
    Source: 'tests/src/btree.rs', lines 52:40-52:46 -/
@[reducible]
def sorted_unique.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32 :
  core.ops.function.FnOnce sorted_unique.closure Std.U32 Std.U32 := {
  call_once :=
    sorted_unique.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32.call_once
}

/-- Trait implementation: [btree::sorted_unique::{impl core::ops::function::FnMut<(&'_0 u32,), u32> for btree::sorted_unique::{closure}}]
    Source: 'tests/src/btree.rs', lines 52:40-52:46 -/
@[reducible]
def sorted_unique.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 :
  core.ops.function.FnMut sorted_unique.closure Std.U32 Std.U32 := {
  FnOnceInst :=
    sorted_unique.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32
  call_mut :=
    sorted_unique.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
}

/-- [btree::sorted_unique]: loop body 0:
    Source: 'tests/src/btree.rs', lines 54:4-56:5
    Visibility: public -/
@[rust_loop_body]
def sorted_unique_loop.body
  (iter : alloc.collections.btree.set.IntoIter Std.U32 Global)
  (out : alloc.vec.Vec Std.U32) :
  Result (ControlFlow ((alloc.collections.btree.set.IntoIter Std.U32 Global) ×
    (alloc.vec.Vec Std.U32)) (alloc.vec.Vec Std.U32))
  := do
  let (o, iter1) ←
    alloc.collections.btree.set.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone iter
  match o with
  | none => ok (done out)
  | some x => let out1 ← alloc.vec.Vec.push out x
              ok (cont (iter1, out1))

/-- [btree::sorted_unique]: loop 0:
    Source: 'tests/src/btree.rs', lines 54:4-56:5
    Visibility: public -/
@[rust_loop]
def sorted_unique_loop
  (iter : alloc.collections.btree.set.IntoIter Std.U32 Global)
  (out : alloc.vec.Vec Std.U32) :
  Result (alloc.vec.Vec Std.U32)
  := do
  loop
    (fun (iter1, out1) => sorted_unique_loop.body iter1 out1)
    (iter, out)

/-- [btree::sorted_unique]:
    Source: 'tests/src/btree.rs', lines 51:0-58:1
    Visibility: public -/
def sorted_unique (v : Slice Std.U32) : Result (alloc.vec.Vec Std.U32) := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      sorted_unique.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 i ()
  let s ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      sorted_unique.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32)
      (alloc.collections.btree.set.BTreeSetTGlobal.Insts.CoreIterTraitsCollectFromIterator
      core.cmp.OrdU32) m
  let iter ←
    alloc.collections.btree.set.BTreeSet.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone s
  sorted_unique_loop iter (alloc.vec.Vec.new Std.U32)

end btree
