-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [btree_into_iter_fold]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace btree_into_iter_fold

/-- [btree_into_iter_fold::sum_map::{closure}]
    Source: 'tests/src/btree-into-iter-fold.rs', lines 8:26-8:71 -/
@[reducible]
def sum_map.closure := Unit

/-- [btree_into_iter_fold::sum_map::{impl core::ops::function::FnMut<(u32, (u32, u32)), u32> for btree_into_iter_fold::sum_map::{closure}}::call_mut]:
    Source: 'tests/src/btree-into-iter-fold.rs', lines 8:26-8:71 -/
def sum_map.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32U32U32.call_mut
  (c : sum_map.closure) (tupled_args : (Std.U32 × (Std.U32 × Std.U32))) :
  Result (Std.U32 × sum_map.closure)
  := do
  let (a, (k, v)) := tupled_args
  let i ← lift (core.num.U32.wrapping_add a k)
  let i1 ← lift (core.num.U32.wrapping_add i v)
  ok (i1, c)

/-- [btree_into_iter_fold::sum_map::{impl core::ops::function::FnOnce<(u32, (u32, u32)), u32> for btree_into_iter_fold::sum_map::{closure}}::call_once]:
    Source: 'tests/src/btree-into-iter-fold.rs', lines 8:26-8:71 -/
def sum_map.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32U32U32.call_once
  (c : sum_map.closure) (p : (Std.U32 × (Std.U32 × Std.U32))) :
  Result Std.U32
  := do
  let (i, _) ←
    sum_map.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [btree_into_iter_fold::sum_map::{impl core::ops::function::FnOnce<(u32, (u32, u32)), u32> for btree_into_iter_fold::sum_map::{closure}}]
    Source: 'tests/src/btree-into-iter-fold.rs', lines 8:26-8:71 -/
@[reducible]
def sum_map.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32U32U32 :
  core.ops.function.FnOnce sum_map.closure (Std.U32 × (Std.U32 × Std.U32))
  Std.U32 := {
  call_once :=
    sum_map.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32U32U32.call_once
}

/-- Trait implementation: [btree_into_iter_fold::sum_map::{impl core::ops::function::FnMut<(u32, (u32, u32)), u32> for btree_into_iter_fold::sum_map::{closure}}]
    Source: 'tests/src/btree-into-iter-fold.rs', lines 8:26-8:71 -/
@[reducible]
def sum_map.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32U32U32 :
  core.ops.function.FnMut sum_map.closure (Std.U32 × (Std.U32 × Std.U32))
  Std.U32 := {
  FnOnceInst := sum_map.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32U32U32
  call_mut :=
    sum_map.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32U32U32.call_mut
}

/-- [btree_into_iter_fold::sum_map]:
    Source: 'tests/src/btree-into-iter-fold.rs', lines 7:0-9:1
    Visibility: public -/
def sum_map
  (m : alloc.collections.btree.map.BTreeMap Std.U32 Std.U32 Global) :
  Result Std.U32
  := do
  let ii ←
    alloc.collections.btree.map.BTreeMap.Insts.CoreIterTraitsCollectIntoIteratorPairIntoIter.into_iter
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone m
  core.iter.traits.iterator.Iterator.fold.default
    (alloc.collections.btree.map.IntoIter.Insts.CoreIterTraitsIteratorIteratorPair
    Std.U32 Std.U32 alloc.alloc.Global.Insts.CoreAllocAllocatorClone)
    sum_map.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32U32U32 ii 0#u32 ()

/-- [btree_into_iter_fold::sum_set::{closure}]
    Source: 'tests/src/btree-into-iter-fold.rs', lines 12:26-12:50 -/
@[reducible]
def sum_set.closure := Unit

/-- [btree_into_iter_fold::sum_set::{impl core::ops::function::FnMut<(u32, u32), u32> for btree_into_iter_fold::sum_set::{closure}}::call_mut]:
    Source: 'tests/src/btree-into-iter-fold.rs', lines 12:26-12:50 -/
def sum_set.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : sum_set.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × sum_set.closure)
  := do
  let (a, x) := tupled_args
  let i ← lift (core.num.U32.wrapping_add a x)
  ok (i, c)

/-- [btree_into_iter_fold::sum_set::{impl core::ops::function::FnOnce<(u32, u32), u32> for btree_into_iter_fold::sum_set::{closure}}::call_once]:
    Source: 'tests/src/btree-into-iter-fold.rs', lines 12:26-12:50 -/
def sum_set.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : sum_set.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    sum_set.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [btree_into_iter_fold::sum_set::{impl core::ops::function::FnOnce<(u32, u32), u32> for btree_into_iter_fold::sum_set::{closure}}]
    Source: 'tests/src/btree-into-iter-fold.rs', lines 12:26-12:50 -/
@[reducible]
def sum_set.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce sum_set.closure (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    sum_set.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [btree_into_iter_fold::sum_set::{impl core::ops::function::FnMut<(u32, u32), u32> for btree_into_iter_fold::sum_set::{closure}}]
    Source: 'tests/src/btree-into-iter-fold.rs', lines 12:26-12:50 -/
@[reducible]
def sum_set.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut sum_set.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := sum_set.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut := sum_set.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [btree_into_iter_fold::sum_set]:
    Source: 'tests/src/btree-into-iter-fold.rs', lines 11:0-13:1
    Visibility: public -/
def sum_set
  (s : alloc.collections.btree.set.BTreeSet Std.U32 Global) :
  Result Std.U32
  := do
  let ii ←
    alloc.collections.btree.set.BTreeSet.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
      alloc.alloc.Global.Insts.CoreAllocAllocatorClone s
  core.iter.traits.iterator.Iterator.fold.default
    (alloc.collections.btree.set.IntoIter.Insts.CoreIterTraitsIteratorIterator
    Std.U32 alloc.alloc.Global.Insts.CoreAllocAllocatorClone)
    sum_set.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 ii 0#u32 ()

end btree_into_iter_fold
