-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_nested_borrows]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closure_nested_borrows

/-- Trait declaration: [closure_nested_borrows::Pcs]
    Source: 'tests/src/closure-nested-borrows.rs', lines 5:0-7:1
    Visibility: public -/
structure Pcs (Self : Type) (Self_Commitment : Type) where

/-- [closure_nested_borrows::Evaluated]
    Source: 'tests/src/closure-nested-borrows.rs', lines 9:0-12:1
    Visibility: public -/
structure Evaluated (F : Type) (C : Type) (Clause0_Commitment : Type) where
  evals : alloc.vec.Vec (Std.U32 × (alloc.vec.Vec F))
  commitment : Clause0_Commitment

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::first::{closure}::{closure}]
    Source: 'tests/src/closure-nested-borrows.rs', lines 19:49-19:95 -/
@[reducible]
def Evaluated.first.closure.closure (F : Type) (C : Type) (Clause1_Commitment :
  Type) :=
  Std.U32 × Evaluated F C Clause1_Commitment

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::first::{closure}::{impl core::ops::function::Fn<(&'_2 F,), (u32, F, &'_ Clause1_Commitment)> for closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C>[TraitClause1]}::first::{closure}::{closure}<'_0, '_1, F, C, Clause1_Commitment>}::call]:
    Source: 'tests/src/closure-nested-borrows.rs', lines 19:49-19:95 -/
def
  Evaluated.first.closure.closure.Insts.CoreOpsFunctionFnTupleShared2FTupleU32FSharedClause1_Commitment.call
  {F : Type} {C : Type} {Clause1_Commitment : Type} (coremarkerCopyInst :
  core.marker.Copy F) (PcsInst : Pcs C Clause1_Commitment)
  (c : Evaluated.first.closure.closure F C Clause1_Commitment)
  (tupled_args : F) :
  Result (Std.U32 × F × Clause1_Commitment)
  := do
  let (i, e) := c
  ok (i, tupled_args, Evaluated.commitment e)

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::first::{closure}]
    Source: 'tests/src/closure-nested-borrows.rs', lines 19:12-19:95 -/
@[reducible]
def Evaluated.first.closure (F : Type) (C : Type) (Clause1_Commitment : Type)
  :=
  Evaluated F C Clause1_Commitment

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::first::{impl core::ops::function::Fn<(&'_1 (u32, alloc::vec::Vec<F>),), closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C>[TraitClause1]}::first::{closure}::{closure}<'_, '_, F, C, Clause1_Commitment>> for closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C>[TraitClause1]}::first::{closure}<'_0, F, C, Clause1_Commitment>}::call]:
    Source: 'tests/src/closure-nested-borrows.rs', lines 19:12-19:95 -/
def
  Evaluated.first.closure.Insts.CoreOpsFunctionFnTupleShared1PairU32Vecclosure.call
  {F : Type} {C : Type} {Clause1_Commitment : Type} (coremarkerCopyInst :
  core.marker.Copy F) (PcsInst : Pcs C Clause1_Commitment)
  (c : Evaluated.first.closure F C Clause1_Commitment)
  (tupled_args : (Std.U32 × (alloc.vec.Vec F))) :
  Result (Evaluated.first.closure.closure F C Clause1_Commitment)
  := do
  let (label, _) := tupled_args
  ok (label, c)

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::first]:
    Source: 'tests/src/closure-nested-borrows.rs', lines 17:4-22:5
    Visibility: public -/
def Evaluated.first
  {F : Type} {C : Type} {Clause1_Commitment : Type} (coremarkerCopyInst :
  core.marker.Copy F) (PcsInst : Pcs C Clause1_Commitment)
  (self : Evaluated F C Clause1_Commitment) :
  Result (Std.U32 × F × Clause1_Commitment)
  := do
  let p ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U32 ×
      (alloc.vec.Vec F))) (Evaluated.evals self) 0#usize
  let inner ←
    Evaluated.first.closure.Insts.CoreOpsFunctionFnTupleShared1PairU32Vecclosure.call
      coremarkerCopyInst PcsInst self p
  let (_, v) := p
  let t ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice F) v 0#usize
  Evaluated.first.closure.closure.Insts.CoreOpsFunctionFnTupleShared2FTupleU32FSharedClause1_Commitment.call
    coremarkerCopyInst PcsInst inner t

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::query::{closure}]
    Source: 'tests/src/closure-nested-borrows.rs', lines 27:8-27:46 -/
@[reducible]
def Evaluated.query.closure (F : Type) (C : Type) (Clause1_Commitment : Type)
  :=
  Std.U32 × Evaluated F C Clause1_Commitment

/-- [closure_nested_borrows::{closure_nested_borrows::Evaluated<F, C, Clause1_Commitment>}::query]:
    Source: 'tests/src/closure-nested-borrows.rs', lines 25:4-28:5
    Visibility: public -/
def Evaluated.query
  {F : Type} {C : Type} {Clause1_Commitment : Type} (coremarkerCopyInst :
  core.marker.Copy F) (PcsInst : Pcs C Clause1_Commitment)
  (self : Evaluated F C Clause1_Commitment) :
  Result (Evaluated.query.closure F C Clause1_Commitment)
  := do
  let (label, _) ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U32 ×
      (alloc.vec.Vec F))) (Evaluated.evals self) 0#usize
  ok (label, self)

end closure_nested_borrows
