-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_assoc_type_diamond]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closure_assoc_type_diamond

/-- Trait declaration: [closure_assoc_type_diamond::Prime]
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 8:0-11:1
    Visibility: public -/
structure Prime (Self : Type) (Self_Repr : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  double : Self → Result Self

/-- Trait declaration: [closure_assoc_type_diamond::Small]
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 13:0-13:25
    Visibility: public -/
structure Small (Self : Type) (Self_Clause0_Repr : Type) where
  PrimeInst : Prime Self Self_Clause0_Repr

/-- Trait declaration: [closure_assoc_type_diamond::Uniform]
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 15:0-15:27
    Visibility: public -/
structure Uniform (Self : Type) (Self_Clause0_Repr : Type) where
  PrimeInst : Prime Self Self_Clause0_Repr

/-- [closure_assoc_type_diamond::doubles::{closure}]
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 18:18-18:32 -/
@[reducible]
def doubles.closure (F : Type) (Clause0_Clause0_Repr : Type)
  (Clause1_Clause0_Repr : Type) :=
Unit

/-- [closure_assoc_type_diamond::doubles::{impl core::ops::function::FnMut<(&'_0 F,), F> for closure_assoc_type_diamond::doubles::{closure}<F, Clause0_Clause0_Repr, Clause0_Clause0_Repr>}::call_mut]:
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 18:18-18:32 -/
def doubles.closure.Insts.CoreOpsFunctionFnMutTupleShared0FF.call_mut
  {F : Type} {Clause0_Clause0_Repr : Type} (Clause1_Clause0_Repr : Type)
  (SmallInst : Small F Clause0_Clause0_Repr) (UniformInst : Uniform F
  Clause0_Clause0_Repr)
  (c : doubles.closure F Clause0_Clause0_Repr Clause0_Clause0_Repr)
  (tupled_args : F) :
  Result (F × (doubles.closure F Clause0_Clause0_Repr Clause0_Clause0_Repr))
  := do
  let t ← SmallInst.PrimeInst.double tupled_args
  ok (t, c)

/-- [closure_assoc_type_diamond::doubles::{impl core::ops::function::FnOnce<(&'_0 F,), F> for closure_assoc_type_diamond::doubles::{closure}<F, Clause0_Clause0_Repr, Clause0_Clause0_Repr>}::call_once]:
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 18:18-18:32 -/
def doubles.closure.Insts.CoreOpsFunctionFnOnceTupleShared0FF.call_once
  {F : Type} {Clause0_Clause0_Repr : Type} (Clause1_Clause0_Repr : Type)
  (SmallInst : Small F Clause0_Clause0_Repr) (UniformInst : Uniform F
  Clause0_Clause0_Repr)
  (c : doubles.closure F Clause0_Clause0_Repr Clause0_Clause0_Repr) (t : F) :
  Result F
  := do
  let (t1, _) ←
    doubles.closure.Insts.CoreOpsFunctionFnMutTupleShared0FF.call_mut
      Clause0_Clause0_Repr SmallInst UniformInst c t
  ok t1

/-- Trait implementation: [closure_assoc_type_diamond::doubles::{impl core::ops::function::FnOnce<(&'_0 F,), F> for closure_assoc_type_diamond::doubles::{closure}<F, Clause0_Clause0_Repr, Clause0_Clause0_Repr>}]
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 18:18-18:32 -/
@[reducible]
def doubles.closure.Insts.CoreOpsFunctionFnOnceTupleShared0FF {F : Type}
  {Clause0_Clause0_Repr : Type} (Clause1_Clause0_Repr : Type) (SmallInst :
  Small F Clause0_Clause0_Repr) (UniformInst : Uniform F Clause0_Clause0_Repr)
  : core.ops.function.FnOnce (doubles.closure F Clause0_Clause0_Repr
  Clause0_Clause0_Repr) F F := {
  call_once :=
    doubles.closure.Insts.CoreOpsFunctionFnOnceTupleShared0FF.call_once
    Clause0_Clause0_Repr SmallInst UniformInst
}

/-- Trait implementation: [closure_assoc_type_diamond::doubles::{impl core::ops::function::FnMut<(&'_0 F,), F> for closure_assoc_type_diamond::doubles::{closure}<F, Clause0_Clause0_Repr, Clause0_Clause0_Repr>}]
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 18:18-18:32 -/
@[reducible]
def doubles.closure.Insts.CoreOpsFunctionFnMutTupleShared0FF {F : Type}
  {Clause0_Clause0_Repr : Type} (Clause1_Clause0_Repr : Type) (SmallInst :
  Small F Clause0_Clause0_Repr) (UniformInst : Uniform F Clause0_Clause0_Repr)
  : core.ops.function.FnMut (doubles.closure F Clause0_Clause0_Repr
  Clause0_Clause0_Repr) F F := {
  FnOnceInst := doubles.closure.Insts.CoreOpsFunctionFnOnceTupleShared0FF
    Clause0_Clause0_Repr SmallInst UniformInst
  call_mut := doubles.closure.Insts.CoreOpsFunctionFnMutTupleShared0FF.call_mut
    Clause0_Clause0_Repr SmallInst UniformInst
}

/-- [closure_assoc_type_diamond::doubles]:
    Source: 'tests/src/closure-assoc-type-diamond.rs', lines 17:0-19:1
    Visibility: public -/
def doubles
  {F : Type} {Clause0_Clause0_Repr : Type} (Clause1_Clause0_Repr : Type)
  (SmallInst : Small F Clause0_Clause0_Repr) (UniformInst : Uniform F
  Clause0_Clause0_Repr) (xs : Slice F) :
  Result (alloc.vec.Vec F)
  := do
  let i ← core.slice.Slice.iter xs
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter F)
      (doubles.closure.Insts.CoreOpsFunctionFnMutTupleShared0FF
      Clause0_Clause0_Repr SmallInst UniformInst) i ()
  core.iter.traits.iterator.Iterator.collect.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter F)
    (doubles.closure.Insts.CoreOpsFunctionFnMutTupleShared0FF
    Clause0_Clause0_Repr SmallInst UniformInst))
    (core.iter.traits.collect.FromIteratorVec F) m

end closure_assoc_type_diamond
