-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [derive_debug_recursive]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace derive_debug_recursive

/-- [derive_debug_recursive::Label]
    Source: 'tests/src/derive-debug-recursive.rs', lines 5:0-10:1
    Visibility: public -/
@[discriminant isize]
inductive Label where
| Fixed : Std.Usize → Label
| Collection : alloc.vec.Vec Label → Label
| Helper : Std.Usize → alloc.vec.Vec Label → Label
| Named : alloc.vec.Vec Label → Label

/-- [derive_debug_recursive::{impl core::fmt::Debug for derive_debug_recursive::Label}::fmt]:
    Source: 'tests/src/derive-debug-recursive.rs', lines 4:9-4:14
    Visibility: public -/
def Label.Insts.CoreFmtDebug.fmt
  (self : Label) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Label.Fixed __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Fixed") __self_01
  | Label.Collection __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
        ({ fmt := (Label.Insts.CoreFmtDebug.fmt) } : core.fmt.Debug Label)))
        __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Collection")
      __self_01
  | Label.Helper __self_0 __self_1 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 :=
      Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
        ({ fmt := (Label.Insts.CoreFmtDebug.fmt) } : core.fmt.Debug Label)))
        __self_1
    core.fmt.Formatter.debug_tuple_field2_finish f (toStr "Helper") __self_01
      __self_11
  | Label.Named __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec
        ({ fmt := (Label.Insts.CoreFmtDebug.fmt) } : core.fmt.Debug Label)))
        __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "Named") (toStr
      "inner") __self_01
partial_fixpoint monotonicity by aeneas_monotonicity []

/-- Trait implementation: [derive_debug_recursive::{impl core::fmt::Debug for derive_debug_recursive::Label}]
    Source: 'tests/src/derive-debug-recursive.rs', lines 4:9-4:14 -/
@[reducible]
def Label.Insts.CoreFmtDebug : core.fmt.Debug Label := {
  fmt := Label.Insts.CoreFmtDebug.fmt
}

end derive_debug_recursive
