-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [enum_cyclic_trait_param]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace enum_cyclic_trait_param

/-- Trait declaration: [enum_cyclic_trait_param::Field]
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 7:0-9:1
    Visibility: public -/
structure Field (Self : Type) (Self_Repr : Type) where
  coremarkerCopyInst : core.marker.Copy Self

/-- Trait declaration: [enum_cyclic_trait_param::Group]
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 11:0-13:1
    Visibility: public -/
structure Group (Self : Type) (Self_Scalar : Type) (Self_Clause0_Repr : Type)
  where
  FieldInst : Field Self_Scalar Self_Clause0_Repr

/-- Trait declaration: [enum_cyclic_trait_param::Proj]
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 15:0-17:1
    Visibility: public -/
structure Proj (Self : Type) (Self_Affine : Type) (Self_Clause0_Scalar : Type)
  (Self_Clause0_Clause0_Repr : Type) (Self_Clause1_Clause0_Clause0_Scalar :
  Type) (Self_Clause1_Clause0_Clause0_Clause0_Repr : Type) where
  GroupInst : Group Self Self_Clause0_Scalar Self_Clause0_Clause0_Repr

/-- Trait declaration: [enum_cyclic_trait_param::Affine]
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 19:0-21:1
    Visibility: public -/
structure Affine (Self : Type) (Self_Proj : Type) (Self_Clause0_Clause0_Scalar
  : Type) (Self_Clause0_Clause0_Clause0_Repr : Type) where
  Self_Clause0_Clause1_Clause0_Clause0_Scalar : Type
  Self_Clause0_Clause1_Clause0_Clause0_Clause0_Repr : Type
  ProjSelf_ProjSelfSelf_Clause0_Clause0_ScalarSelf_Clause0_Clause0_Clause0_ReprSelf_Clause0_Clause1_Clause0_Clause0_ScalarSelf_Clause0_Clause1_Clause0_Clause0_Clause0_ReprInst
    : Proj Self_Proj Self Self_Clause0_Clause0_Scalar
    Self_Clause0_Clause0_Clause0_Repr
    Self_Clause0_Clause1_Clause0_Clause0_Scalar
    Self_Clause0_Clause1_Clause0_Clause0_Clause0_Repr

/-- [enum_cyclic_trait_param::Commitment]
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 23:0-26:1
    Visibility: public -/
@[discriminant isize]
inductive Commitment {A : Type} {Clause0_Proj : Type}
  {Clause0_Clause0_Clause0_Scalar : Type} {Clause0_Clause0_Clause0_Clause0_Repr
  : Type} (AffineInst : Affine A Clause0_Proj Clause0_Clause0_Clause0_Scalar
  Clause0_Clause0_Clause0_Clause0_Repr) where
| Simple : A → Commitment AffineInst
| Linear :
  alloc.vec.Vec A →
  alloc.vec.Vec Clause0_Clause0_Clause0_Scalar →
  Commitment AffineInst

/-- [enum_cyclic_trait_param::count]:
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 28:0-33:1
    Visibility: public -/
def count
  {A : Type} {Clause0_Proj : Type} {Clause0_Clause0_Clause0_Scalar : Type}
  {Clause0_Clause0_Clause0_Clause0_Repr : Type} (AffineInst : Affine A
  Clause0_Proj Clause0_Clause0_Clause0_Scalar
  Clause0_Clause0_Clause0_Clause0_Repr) (c : Commitment AffineInst) :
  Result Std.Usize
  := do
  match c with
  | Commitment.Simple _ => ok 1#usize
  | Commitment.Linear ps _ => ok (alloc.vec.Vec.len ps)

/-- [enum_cyclic_trait_param::count_first::{closure}]
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 38:18-38:36 -/
@[reducible]
def count_first.closure {A : Type} {Clause0_Proj : Type}
  {Clause0_Clause0_Clause0_Scalar : Type} {Clause0_Clause0_Clause0_Clause0_Repr
  : Type} (AffineInst : Affine A Clause0_Proj Clause0_Clause0_Clause0_Scalar
  Clause0_Clause0_Clause0_Clause0_Repr) :=
  Std.Usize

instance {A : Type} {Clause0_Proj : Type} {Clause0_Clause0_Clause0_Scalar :
  Type} {Clause0_Clause0_Clause0_Clause0_Repr : Type} {AffineInst : Affine A
  Clause0_Proj Clause0_Clause0_Clause0_Scalar
  Clause0_Clause0_Clause0_Clause0_Repr} : Aeneas.Std.GivesBack
  (count_first.closure AffineInst) := ⟨⟩

/-- [enum_cyclic_trait_param::count_first::{impl core::ops::function::FnMut<(&'_1 enum_cyclic_trait_param::Commitment<A, Clause0_Proj, Clause0_Clause0_Clause0_Scalar, Clause0_Clause0_Clause0_Clause0_Repr>[TraitClause0],), ()> for enum_cyclic_trait_param::count_first::{closure}<'_0, A, Clause0_Proj, Clause0_Clause0_Clause0_Scalar, Clause0_Clause0_Clause0_Clause0_Repr>[TraitClause0]}::call_mut]:
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 38:18-38:36 -/
def
  count_first.closure.Insts.CoreOpsFunctionFnMutTupleShared1CommitmentTuple.call_mut
  {A : Type} {Clause0_Proj : Type} {Clause0_Clause0_Clause0_Scalar : Type}
  {Clause0_Clause0_Clause0_Clause0_Repr : Type} (AffineInst : Affine A
  Clause0_Proj Clause0_Clause0_Clause0_Scalar
  Clause0_Clause0_Clause0_Clause0_Repr) (c : count_first.closure AffineInst)
  (tupled_args : Commitment AffineInst) :
  Result ((count_first.closure AffineInst) × (count_first.closure AffineInst
    → count_first.closure AffineInst))
  := do
  let i ← count AffineInst tupled_args
  let i1 ← c + i
  let back := fun c1 => c1
  ok (i1, back)

/-- [enum_cyclic_trait_param::count_first]:
    Source: 'tests/src/enum-cyclic-trait-param.rs', lines 37:0-40:1
    Visibility: public -/
def count_first
  {A : Type} {Clause0_Proj : Type} {Clause0_Clause0_Clause0_Scalar : Type}
  {Clause0_Clause0_Clause0_Clause0_Repr : Type} (AffineInst : Affine A
  Clause0_Proj Clause0_Clause0_Clause0_Scalar
  Clause0_Clause0_Clause0_Clause0_Repr) (cs : Slice (Commitment AffineInst))
  (n : Std.Usize) :
  Result Std.Usize
  := do
  let c ← Slice.index_usize cs 0#usize
  let (add, call_mut_back) ←
    count_first.closure.Insts.CoreOpsFunctionFnMutTupleShared1CommitmentTuple.call_mut
      AffineInst n c
  let n1 := call_mut_back add
  ok n1

end enum_cyclic_trait_param
