-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [excluded_trait_method]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace excluded_trait_method

/-- Trait declaration: [excluded_trait_method::Params]
    Source: 'tests/src/excluded-trait-method.rs', lines 11:0-17:1
    Visibility: public -/
structure Params (Self : Type) where
  k : Self → Result Std.U32

/-- [excluded_trait_method::Srs]
    Source: 'tests/src/excluded-trait-method.rs', lines 19:0-21:1
    Visibility: public -/
structure Srs where
  k : Std.U32

/-- [excluded_trait_method::{impl excluded_trait_method::Params for excluded_trait_method::Srs}::k]:
    Source: 'tests/src/excluded-trait-method.rs', lines 24:4-26:5
    Visibility: public -/
def Srs.Insts.Excluded_trait_methodParams.k (self : Srs) : Result Std.U32 := do
  ok self.k

/-- Trait implementation: [excluded_trait_method::{impl excluded_trait_method::Params for excluded_trait_method::Srs}]
    Source: 'tests/src/excluded-trait-method.rs', lines 23:0-27:1 -/
@[reducible]
impl_def Srs.Insts.Excluded_trait_methodParams : Params Srs := {
  k := Srs.Insts.Excluded_trait_methodParams.k
}

/-- [excluded_trait_method::double_k]:
    Source: 'tests/src/excluded-trait-method.rs', lines 29:0-31:1
    Visibility: public -/
def double_k {P : Type} (ParamsInst : Params P) (p : P) : Result Std.U32 := do
  let i ← ParamsInst.k p
  i * 2#u32

end excluded_trait_method
