-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [generic_iter_zip]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace generic_iter_zip

/-- [generic_iter_zip::dot::{closure}]
    Source: 'tests/src/generic-iter-zip.rs', lines 9:17-9:63 -/
@[reducible]
def dot.closure (I : Type) (Clause0_IntoIter : Type) := Unit

/-- [generic_iter_zip::dot::{impl core::ops::function::FnMut<(u32, (u32, &'_0 u32)), u32> for generic_iter_zip::dot::{closure}<I, Clause0_IntoIter>}::call_mut]:
    Source: 'tests/src/generic-iter-zip.rs', lines 9:17-9:63 -/
def dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32Shared0U32U32.call_mut
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U32 Clause0_IntoIter)
  (c : dot.closure I Clause0_IntoIter)
  (tupled_args : (Std.U32 × (Std.U32 × Std.U32))) :
  Result (Std.U32 × (dot.closure I Clause0_IntoIter))
  := do
  let (a, (x, y)) := tupled_args
  let i ← lift (core.num.U32.wrapping_mul x y)
  let i1 ← lift (core.num.U32.wrapping_add a i)
  ok (i1, c)

/-- [generic_iter_zip::dot::{impl core::ops::function::FnOnce<(u32, (u32, &'_0 u32)), u32> for generic_iter_zip::dot::{closure}<I, Clause0_IntoIter>}::call_once]:
    Source: 'tests/src/generic-iter-zip.rs', lines 9:17-9:63 -/
def
  dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32Shared0U32U32.call_once
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U32 Clause0_IntoIter)
  (c : dot.closure I Clause0_IntoIter) (p : (Std.U32 × (Std.U32 × Std.U32)))
  :
  Result Std.U32
  := do
  let (i, _) ←
    dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32Shared0U32U32.call_mut
      coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst c p
  ok i

/-- Trait implementation: [generic_iter_zip::dot::{impl core::ops::function::FnOnce<(u32, (u32, &'_0 u32)), u32> for generic_iter_zip::dot::{closure}<I, Clause0_IntoIter>}]
    Source: 'tests/src/generic-iter-zip.rs', lines 9:17-9:63 -/
@[reducible]
def dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32Shared0U32U32 {I :
  Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U32 Clause0_IntoIter) :
  core.ops.function.FnOnce (dot.closure I Clause0_IntoIter) (Std.U32 ×
  (Std.U32 × Std.U32)) Std.U32 := {
  call_once :=
    dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32Shared0U32U32.call_once
    coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst
}

/-- Trait implementation: [generic_iter_zip::dot::{impl core::ops::function::FnMut<(u32, (u32, &'_0 u32)), u32> for generic_iter_zip::dot::{closure}<I, Clause0_IntoIter>}]
    Source: 'tests/src/generic-iter-zip.rs', lines 9:17-9:63 -/
@[reducible]
def dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32Shared0U32U32 {I :
  Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U32 Clause0_IntoIter) :
  core.ops.function.FnMut (dot.closure I Clause0_IntoIter) (Std.U32 × (Std.U32
  × Std.U32)) Std.U32 := {
  FnOnceInst :=
    dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairU32Shared0U32U32
    coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst
  call_mut :=
    dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32Shared0U32U32.call_mut
    coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst
}

/-- [generic_iter_zip::dot]:
    Source: 'tests/src/generic-iter-zip.rs', lines 6:0-10:1
    Visibility: public -/
def dot
  {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst :
  core.iter.traits.collect.IntoIterator I Std.U32 Clause0_IntoIter) (xs : I)
  (ys : Slice Std.U32) :
  Result Std.U32
  := do
  let t ←
    coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst.into_iter xs
  let i ← core.slice.Slice.iter ys
  let z ←
    core.iter.traits.iterator.Iterator.zip.trait_default
      coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst.iteratorInst
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) t i
  core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair.fold
    coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst.iteratorInst
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairU32Shared0U32U32
    coreitertraitscollectIntoIteratorIU32Clause0_IntoIterInst) z 0#u32 ()

end generic_iter_zip
