-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [higher_ranked_implied_bounds_borrow]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace higher_ranked_implied_bounds_borrow

/-- Trait declaration: [higher_ranked_implied_bounds_borrow::RefTrait]
    Source: 'tests/src/higher_ranked_implied_bounds_borrow.rs', lines 10:0-12:1 -/
structure RefTrait (Self : Type) (X : Type) where
  get : Self → Result X

/-- [higher_ranked_implied_bounds_borrow::borrow_outlive]:
    Source: 'tests/src/higher_ranked_implied_bounds_borrow.rs', lines 14:0-18:1 -/
def borrow_outlive
  {P : Type} (RefTraitPSharedBSharedBU8Inst : RefTrait P Std.U8) (_p : P) :
  Result Unit
  := do
  ok ()

end higher_ranked_implied_bounds_borrow
