-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [issue_1043_iterator_methods]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace issue_1043_iterator_methods

/-- [issue_1043_iterator_methods::indexed_squares::{closure}]
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 10:25-10:46 -/
@[reducible]
def indexed_squares.closure (I : Type) := Unit

/-- [issue_1043_iterator_methods::indexed_squares::{impl core::ops::function::FnMut<((usize, u32),), u32> for issue_1043_iterator_methods::indexed_squares::{closure}<I>}::call_mut]:
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 10:25-10:46 -/
def
  indexed_squares.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeU32U32.call_mut
  {I : Type} (coreitertraitsiteratorIteratorIU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) (c : indexed_squares.closure I)
  (tupled_args : (Std.Usize × Std.U32)) :
  Result (Std.U32 × (indexed_squares.closure I))
  := do
  let (i, x) := tupled_args
  let i1 ← lift (UScalar.cast .U32 i)
  let i2 ← x + i1
  ok (i2, c)

/-- [issue_1043_iterator_methods::indexed_squares::{impl core::ops::function::FnOnce<((usize, u32),), u32> for issue_1043_iterator_methods::indexed_squares::{closure}<I>}::call_once]:
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 10:25-10:46 -/
def
  indexed_squares.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeU32U32.call_once
  {I : Type} (coreitertraitsiteratorIteratorIU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) (c : indexed_squares.closure I)
  (p : (Std.Usize × Std.U32)) :
  Result Std.U32
  := do
  let (i, _) ←
    indexed_squares.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeU32U32.call_mut
      coreitertraitsiteratorIteratorIU32Inst c p
  ok i

/-- Trait implementation: [issue_1043_iterator_methods::indexed_squares::{impl core::ops::function::FnOnce<((usize, u32),), u32> for issue_1043_iterator_methods::indexed_squares::{closure}<I>}]
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 10:25-10:46 -/
@[reducible]
def indexed_squares.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeU32U32 {I
  : Type} (coreitertraitsiteratorIteratorIU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) : core.ops.function.FnOnce
  (indexed_squares.closure I) (Std.Usize × Std.U32) Std.U32 := {
  call_once :=
    indexed_squares.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeU32U32.call_once
    coreitertraitsiteratorIteratorIU32Inst
}

/-- Trait implementation: [issue_1043_iterator_methods::indexed_squares::{impl core::ops::function::FnMut<((usize, u32),), u32> for issue_1043_iterator_methods::indexed_squares::{closure}<I>}]
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 10:25-10:46 -/
@[reducible]
def indexed_squares.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeU32U32 {I :
  Type} (coreitertraitsiteratorIteratorIU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) : core.ops.function.FnMut
  (indexed_squares.closure I) (Std.Usize × Std.U32) Std.U32 := {
  FnOnceInst :=
    indexed_squares.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeU32U32
    coreitertraitsiteratorIteratorIU32Inst
  call_mut :=
    indexed_squares.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeU32U32.call_mut
    coreitertraitsiteratorIteratorIU32Inst
}

/-- [issue_1043_iterator_methods::indexed_squares]:
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 9:0-11:1
    Visibility: public -/
def indexed_squares
  {I : Type} (coreitertraitsiteratorIteratorIU32Inst :
  core.iter.traits.iterator.Iterator I Std.U32) (iter : I) :
  Result (alloc.vec.Vec Std.U32)
  := do
  let e ← coreitertraitsiteratorIteratorIU32Inst.enumerate iter
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorEnumerate
      coreitertraitsiteratorIteratorIU32Inst)
      (indexed_squares.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeU32U32
      coreitertraitsiteratorIteratorIU32Inst) e ()
  core.iter.traits.iterator.Iterator.collect.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorEnumerate
    coreitertraitsiteratorIteratorIU32Inst)
    (indexed_squares.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeU32U32
    coreitertraitsiteratorIteratorIU32Inst))
    (core.iter.traits.collect.FromIteratorVec Std.U32) m

/-- [issue_1043_iterator_methods::call_it]:
    Source: 'tests/src/issue-1043-iterator-methods.rs', lines 13:0-15:1
    Visibility: public -/
def call_it (n : Std.U32) : Result (alloc.vec.Vec Std.U32) := do
  indexed_squares (core.iter.traits.iterator.IteratorRange
    core.iter.range.StepU32) { start := 0#u32, «end» := n }

end issue_1043_iterator_methods
