-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [issue_1264_closure]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace issue_1264_closure

/-- [issue_1264_closure::call]:
    Source: 'tests/src/issue-1264-closure.rs', lines 5:0-7:1 -/
def call
  {T0 : Type} (coreopsfunctionFnOnceT0TupleTupleInst : core.ops.function.FnOnce
  T0 Unit Unit) (f1 : T0) :
  Result Unit
  := do
  coreopsfunctionFnOnceT0TupleTupleInst.call_once f1 ()

/-- [issue_1264_closure::f::{closure}]
    Source: 'tests/src/issue-1264-closure.rs', lines 11:13-11:24 -/
@[reducible]
def f.closure := Unit

mutual

/-- [issue_1264_closure::f]:
    Source: 'tests/src/issue-1264-closure.rs', lines 9:0-13:1
    Visibility: public -/
def f (b : Bool) : Result Unit := do
  if b
  then
    call
      ({ call_once :=
           (f.closure.Insts.CoreOpsFunctionFnOnceTupleTuple.call_once) }) ()
  else ok ()
partial_fixpoint monotonicity by aeneas_monotonicity [call]

/-- [issue_1264_closure::f::{impl core::ops::function::FnOnce<(), ()> for issue_1264_closure::f::{closure}}::call_once]:
    Source: 'tests/src/issue-1264-closure.rs', lines 11:13-11:24 -/
def f.closure.Insts.CoreOpsFunctionFnOnceTupleTuple.call_once
  (c : f.closure) (_ : Unit) : Result Unit := do
  f false
partial_fixpoint monotonicity by aeneas_monotonicity [call]

end

/-- Trait implementation: [issue_1264_closure::f::{impl core::ops::function::FnOnce<(), ()> for issue_1264_closure::f::{closure}}]
    Source: 'tests/src/issue-1264-closure.rs', lines 11:13-11:24 -/
@[reducible]
impl_def f.closure.Insts.CoreOpsFunctionFnOnceTupleTuple :
  core.ops.function.FnOnce f.closure Unit Unit := {
  call_once := f.closure.Insts.CoreOpsFunctionFnOnceTupleTuple.call_once
}

end issue_1264_closure
