-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [iter_rev_default]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace iter_rev_default

/-- Trait implementation: [core::slice::iter::{impl core::iter::traits::double_ended::DoubleEndedIterator<&'_ T> for core::slice::iter::Iter<'a, T>}]
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 431:8-431:56
    Name pattern: [core::iter::traits::double_ended::DoubleEndedIterator<core::slice::iter::Iter<'a, @T>, &'_ @T>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::double_ended::DoubleEndedIterator<core::slice::iter::Iter<'a, @T>, &'_ @T>"]
def
  core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
  (T : Type) : core.iter.traits.double_ended.DoubleEndedIterator
  (core.slice.iter.Iter T) T := {
  iteratorInst := core.iter.traits.iterator.IteratorSliceIter T
  next_back := core.slice.iter.IteratorSliceIter.next_back
}

/-- [iter_rev_default::sum_rev]: loop body 1:
    Source: 'tests/src/iter-rev-default.rs', lines 9:8-11:9
    Visibility: public -/
@[rust_loop_body]
def sum_rev_loop0_loop0.body
  (iter : core.iter.adapters.rev.Rev (core.ops.range.Range Std.I32))
  (i : Std.U64) :
  Result (ControlFlow ((core.iter.adapters.rev.Rev (core.ops.range.Range
    Std.I32)) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.adapters.rev.Rev.Insts.CoreIterTraitsIteratorIterator.next
      (core.ops.range.Range.Insts.DoubleEndedIterator core.iter.range.StepI32)
      iter
  match o with
  | none => ok (done i)
  | some _ => let i1 ← i + 1#u64
              ok (cont (iter1, i1))

/-- [iter_rev_default::sum_rev]: loop 1:
    Source: 'tests/src/iter-rev-default.rs', lines 9:8-11:9
    Visibility: public -/
@[rust_loop]
def sum_rev_loop0_loop0
  (iter : core.iter.adapters.rev.Rev (core.ops.range.Range Std.I32))
  (i : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, i1) => sum_rev_loop0_loop0.body iter1 i1)
    (iter, i)

/-- [iter_rev_default::sum_rev]: loop body 0:
    Source: 'tests/src/iter-rev-default.rs', lines 7:4-13:5
    Visibility: public -/
@[rust_loop_body]
def sum_rev_loop0.body
  (iter : core.iter.adapters.rev.Rev (core.slice.iter.Iter Std.U64))
  (s : Std.U64) :
  Result (ControlFlow ((core.iter.adapters.rev.Rev (core.slice.iter.Iter
    Std.U64)) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.adapters.rev.Rev.Insts.CoreIterTraitsIteratorIterator.next
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U64) iter
  match o with
  | none => ok (done s)
  | some x =>
    let iter2 ←
      core.iter.traits.iterator.Iterator.rev.trait_default
        (core.iter.traits.iterator.IteratorRange core.iter.range.StepI32)
        (core.ops.range.Range.Insts.DoubleEndedIterator
        core.iter.range.StepI32) { start := 0#i32, «end» := 4#i32 }
    let i ← sum_rev_loop0_loop0 iter2 0#u64
    let i1 ← lift (core.num.U64.wrapping_add s x)
    let s1 ← lift (core.num.U64.wrapping_add i1 i)
    ok (cont (iter1, s1))

/-- [iter_rev_default::sum_rev]: loop 0:
    Source: 'tests/src/iter-rev-default.rs', lines 7:4-13:5
    Visibility: public -/
@[rust_loop]
def sum_rev_loop0
  (iter : core.iter.adapters.rev.Rev (core.slice.iter.Iter Std.U64))
  (s : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, s1) => sum_rev_loop0.body iter1 s1)
    (iter, s)

/-- [iter_rev_default::sum_rev]:
    Source: 'tests/src/iter-rev-default.rs', lines 5:0-15:1
    Visibility: public -/
def sum_rev (xs : Slice Std.U64) : Result Std.U64 := do
  let i ← core.slice.Slice.iter xs
  let iter ←
    core.iter.traits.iterator.Iterator.rev.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U64)
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U64) i
  sum_rev_loop0 iter 0#u64

end iter_rev_default
