-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [iter_std_overrides]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace iter_std_overrides

/-- [iter_std_overrides::array_sum::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 8:26-8:38 -/
@[reducible]
def array_sum.closure := Unit

/-- [iter_std_overrides::array_sum::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_std_overrides::array_sum::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 8:26-8:38 -/
def array_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : array_sum.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × array_sum.closure)
  := do
  let (s, x) := tupled_args
  let i ← s + x
  ok (i, c)

/-- [iter_std_overrides::array_sum::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_std_overrides::array_sum::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 8:26-8:38 -/
def array_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : array_sum.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    array_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_std_overrides::array_sum::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_std_overrides::array_sum::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 8:26-8:38 -/
@[reducible]
def array_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce array_sum.closure (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    array_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_std_overrides::array_sum::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_std_overrides::array_sum::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 8:26-8:38 -/
@[reducible]
def array_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut array_sum.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := array_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut :=
    array_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_std_overrides::array_sum]:
    Source: 'tests/src/iter-std-overrides.rs', lines 7:0-9:1
    Visibility: public -/
def array_sum (a : Array Std.U32 3#usize) : Result Std.U32 := do
  let ii ← Array.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter a
  core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.fold
    array_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 ii 0#u32 ()

/-- [iter_std_overrides::array_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 11:0-13:1
    Visibility: public -/
def array_len (a : Array Std.U32 3#usize) : Result Std.Usize := do
  let ii ← Array.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter a
  core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.count ii

/-- [iter_std_overrides::array_hint]:
    Source: 'tests/src/iter-std-overrides.rs', lines 15:0-19:1
    Visibility: public -/
def array_hint
  (a : Array Std.U32 3#usize) : Result (Std.Usize × (Option Std.Usize)) := do
  let it ← Array.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter a
  let (_, it1) ←
    core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next it
  core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.size_hint it1

/-- [iter_std_overrides::vec_sum::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 22:26-22:38 -/
@[reducible]
def vec_sum.closure := Unit

/-- [iter_std_overrides::vec_sum::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_std_overrides::vec_sum::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 22:26-22:38 -/
def vec_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : vec_sum.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × vec_sum.closure)
  := do
  let (s, x) := tupled_args
  let i ← s + x
  ok (i, c)

/-- [iter_std_overrides::vec_sum::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_std_overrides::vec_sum::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 22:26-22:38 -/
def vec_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : vec_sum.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    vec_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_std_overrides::vec_sum::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_std_overrides::vec_sum::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 22:26-22:38 -/
@[reducible]
def vec_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce vec_sum.closure (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    vec_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_std_overrides::vec_sum::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_std_overrides::vec_sum::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 22:26-22:38 -/
@[reducible]
def vec_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut vec_sum.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := vec_sum.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut := vec_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_std_overrides::vec_sum]:
    Source: 'tests/src/iter-std-overrides.rs', lines 21:0-23:1
    Visibility: public -/
def vec_sum (v : alloc.vec.Vec Std.U32) : Result Std.U32 := do
  let ii ← alloc.vec.IntoIteratorVec.into_iter v
  alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.fold
    vec_sum.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 ii 0#u32 ()

/-- [iter_std_overrides::vec_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 25:0-27:1
    Visibility: public -/
def vec_len (v : alloc.vec.Vec Std.U32) : Result Std.Usize := do
  let ii ← alloc.vec.IntoIteratorVec.into_iter v
  alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.count ii

/-- [iter_std_overrides::ref_vec_sum]: loop body 0:
    Source: 'tests/src/iter-std-overrides.rs', lines 31:4-33:5
    Visibility: public -/
@[rust_loop_body]
def ref_vec_sum_loop.body
  (iter : core.slice.iter.Iter Std.U32) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U32) × Std.U32) Std.U32)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done s)
  | some x =>
    let s1 ← U32.Insts.CoreOpsArithAddAssignShared0U32.add_assign s x
    ok (cont (iter1, s1))

/-- [iter_std_overrides::ref_vec_sum]: loop 0:
    Source: 'tests/src/iter-std-overrides.rs', lines 31:4-33:5
    Visibility: public -/
@[rust_loop]
def ref_vec_sum_loop
  (iter : core.slice.iter.Iter Std.U32) (s : Std.U32) : Result Std.U32 := do
  loop
    (fun (iter1, s1) => ref_vec_sum_loop.body iter1 s1)
    (iter, s)

/-- [iter_std_overrides::ref_vec_sum]:
    Source: 'tests/src/iter-std-overrides.rs', lines 29:0-35:1
    Visibility: public -/
def ref_vec_sum (v : alloc.vec.Vec Std.U32) : Result Std.U32 := do
  let iter ←
    SharedAVec.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter v
  ref_vec_sum_loop iter 0#u32

/-- [iter_std_overrides::indexed::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 38:33-38:66 -/
@[reducible]
def indexed.closure := Unit

/-- [iter_std_overrides::indexed::{impl core::ops::function::FnMut<(usize, (usize, &'_0 u32)), usize> for iter_std_overrides::indexed::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 38:33-38:66 -/
def
  indexed.closure.Insts.CoreOpsFunctionFnMutPairUsizePairUsizeShared0U32Usize.call_mut
  (c : indexed.closure) (tupled_args : (Std.Usize × (Std.Usize × Std.U32))) :
  Result (Std.Usize × indexed.closure)
  := do
  let (s, (i, x)) := tupled_args
  let i1 ← lift (UScalar.cast .Usize x)
  let i2 ← i * i1
  let i3 ← s + i2
  ok (i3, c)

/-- [iter_std_overrides::indexed::{impl core::ops::function::FnOnce<(usize, (usize, &'_0 u32)), usize> for iter_std_overrides::indexed::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 38:33-38:66 -/
def
  indexed.closure.Insts.CoreOpsFunctionFnOncePairUsizePairUsizeShared0U32Usize.call_once
  (c : indexed.closure) (p : (Std.Usize × (Std.Usize × Std.U32))) :
  Result Std.Usize
  := do
  let (i, _) ←
    indexed.closure.Insts.CoreOpsFunctionFnMutPairUsizePairUsizeShared0U32Usize.call_mut
      c p
  ok i

/-- Trait implementation: [iter_std_overrides::indexed::{impl core::ops::function::FnOnce<(usize, (usize, &'_0 u32)), usize> for iter_std_overrides::indexed::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 38:33-38:66 -/
@[reducible]
def
  indexed.closure.Insts.CoreOpsFunctionFnOncePairUsizePairUsizeShared0U32Usize
  : core.ops.function.FnOnce indexed.closure (Std.Usize × (Std.Usize ×
  Std.U32)) Std.Usize := {
  call_once :=
    indexed.closure.Insts.CoreOpsFunctionFnOncePairUsizePairUsizeShared0U32Usize.call_once
}

/-- Trait implementation: [iter_std_overrides::indexed::{impl core::ops::function::FnMut<(usize, (usize, &'_0 u32)), usize> for iter_std_overrides::indexed::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 38:33-38:66 -/
@[reducible]
def indexed.closure.Insts.CoreOpsFunctionFnMutPairUsizePairUsizeShared0U32Usize
  : core.ops.function.FnMut indexed.closure (Std.Usize × (Std.Usize ×
  Std.U32)) Std.Usize := {
  FnOnceInst :=
    indexed.closure.Insts.CoreOpsFunctionFnOncePairUsizePairUsizeShared0U32Usize
  call_mut :=
    indexed.closure.Insts.CoreOpsFunctionFnMutPairUsizePairUsizeShared0U32Usize.call_mut
}

/-- [iter_std_overrides::indexed]:
    Source: 'tests/src/iter-std-overrides.rs', lines 37:0-39:1
    Visibility: public -/
def indexed (v : Slice Std.U32) : Result Std.Usize := do
  let i ← core.slice.Slice.iter v
  let e ←
    core.iter.traits.iterator.Iterator.enumerate.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) i
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    indexed.closure.Insts.CoreOpsFunctionFnMutPairUsizePairUsizeShared0U32Usize
    e 0#usize ()

/-- [iter_std_overrides::indexed_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 41:0-43:1
    Visibility: public -/
def indexed_len (v : Slice Std.U32) : Result Std.Usize := do
  let i ← core.slice.Slice.iter v
  let e ←
    core.iter.traits.iterator.Iterator.enumerate.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) i
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.count
    (core.iter.traits.iterator.IteratorSliceIter Std.U32) e

/-- [iter_std_overrides::dot::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 46:35-46:56 -/
@[reducible]
def dot.closure := Unit

/-- [iter_std_overrides::dot::{impl core::ops::function::FnMut<(u32, (&'_0 u32, &'_1 u32)), u32> for iter_std_overrides::dot::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 46:35-46:56 -/
def
  dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairShared0U32Shared1U32U32.call_mut
  (c : dot.closure) (tupled_args : (Std.U32 × (Std.U32 × Std.U32))) :
  Result (Std.U32 × dot.closure)
  := do
  let (s, (x, y)) := tupled_args
  let i ← Shared1U32.Insts.CoreOpsArithMulShared0U32U32.mul x y
  let i1 ← s + i
  ok (i1, c)

/-- [iter_std_overrides::dot::{impl core::ops::function::FnOnce<(u32, (&'_0 u32, &'_1 u32)), u32> for iter_std_overrides::dot::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 46:35-46:56 -/
def
  dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairShared0U32Shared1U32U32.call_once
  (c : dot.closure) (p : (Std.U32 × (Std.U32 × Std.U32))) :
  Result Std.U32
  := do
  let (i, _) ←
    dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairShared0U32Shared1U32U32.call_mut
      c p
  ok i

/-- Trait implementation: [iter_std_overrides::dot::{impl core::ops::function::FnOnce<(u32, (&'_0 u32, &'_1 u32)), u32> for iter_std_overrides::dot::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 46:35-46:56 -/
@[reducible]
def dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairShared0U32Shared1U32U32 :
  core.ops.function.FnOnce dot.closure (Std.U32 × (Std.U32 × Std.U32))
  Std.U32 := {
  call_once :=
    dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairShared0U32Shared1U32U32.call_once
}

/-- Trait implementation: [iter_std_overrides::dot::{impl core::ops::function::FnMut<(u32, (&'_0 u32, &'_1 u32)), u32> for iter_std_overrides::dot::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 46:35-46:56 -/
@[reducible]
def dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairShared0U32Shared1U32U32 :
  core.ops.function.FnMut dot.closure (Std.U32 × (Std.U32 × Std.U32)) Std.U32
  := {
  FnOnceInst :=
    dot.closure.Insts.CoreOpsFunctionFnOncePairU32PairShared0U32Shared1U32U32
  call_mut :=
    dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairShared0U32Shared1U32U32.call_mut
}

/-- [iter_std_overrides::dot]:
    Source: 'tests/src/iter-std-overrides.rs', lines 45:0-47:1
    Visibility: public -/
def dot (a : Slice Std.U32) (b : Slice Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter a
  let i1 ← core.slice.Slice.iter b
  let z ←
    core.iter.traits.iterator.Iterator.zip.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    dot.closure.Insts.CoreOpsFunctionFnMutPairU32PairShared0U32Shared1U32U32 z
    0#u32 ()

/-- [iter_std_overrides::zip_hint]:
    Source: 'tests/src/iter-std-overrides.rs', lines 49:0-51:1
    Visibility: public -/
def zip_hint
  (a : Slice Std.U32) (b : Slice Std.U32) :
  Result (Std.Usize × (Option Std.Usize))
  := do
  let i ← core.slice.Slice.iter a
  let i1 ← core.slice.Slice.iter b
  let z ←
    core.iter.traits.iterator.Iterator.zip.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair.size_hint
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.iterator.IteratorSliceIter Std.U32) z

/-- [iter_std_overrides::flat_len::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 54:22-54:31 -/
@[reducible]
def flat_len.closure := Unit

/-- [iter_std_overrides::flat_len::{impl core::ops::function::FnMut<(&'_0 u32,), core::ops::range::Range<u32>> for iter_std_overrides::flat_len::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 54:22-54:31 -/
def flat_len.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32RangeU32.call_mut
  (c : flat_len.closure) (tupled_args : Std.U32) :
  Result ((core.ops.range.Range Std.U32) × flat_len.closure)
  := do
  ok ({ start := 0#u32, «end» := tupled_args }, c)

/-- [iter_std_overrides::flat_len::{impl core::ops::function::FnOnce<(&'_0 u32,), core::ops::range::Range<u32>> for iter_std_overrides::flat_len::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 54:22-54:31 -/
def
  flat_len.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32RangeU32.call_once
  (c : flat_len.closure) (i : Std.U32) :
  Result (core.ops.range.Range Std.U32)
  := do
  let (r, _) ←
    flat_len.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32RangeU32.call_mut
      c i
  ok r

/-- Trait implementation: [iter_std_overrides::flat_len::{impl core::ops::function::FnOnce<(&'_0 u32,), core::ops::range::Range<u32>> for iter_std_overrides::flat_len::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 54:22-54:31 -/
@[reducible]
def flat_len.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32RangeU32 :
  core.ops.function.FnOnce flat_len.closure Std.U32 (core.ops.range.Range
  Std.U32) := {
  call_once :=
    flat_len.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32RangeU32.call_once
}

/-- Trait implementation: [iter_std_overrides::flat_len::{impl core::ops::function::FnMut<(&'_0 u32,), core::ops::range::Range<u32>> for iter_std_overrides::flat_len::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 54:22-54:31 -/
@[reducible]
def flat_len.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32RangeU32 :
  core.ops.function.FnMut flat_len.closure Std.U32 (core.ops.range.Range
  Std.U32) := {
  FnOnceInst :=
    flat_len.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32RangeU32
  call_mut :=
    flat_len.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32RangeU32.call_mut
}

/-- [iter_std_overrides::flat_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 53:0-55:1
    Visibility: public -/
def flat_len (v : Slice Std.U32) : Result Std.Usize := do
  let i ← core.slice.Slice.iter v
  let fm ←
    core.iter.traits.iterator.Iterator.flat_map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU32))
      flat_len.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32RangeU32 i ()
  core.iter.adapters.flatten.FlatMap.Insts.CoreIterTraitsIteratorIterator.count
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.collect.IntoIterator.Blanket
    (core.iter.traits.iterator.IteratorRange core.iter.range.StepU32))
    flat_len.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32RangeU32 fm

/-- [iter_std_overrides::range_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 57:0-59:1
    Visibility: public -/
def range_len (a : Std.Usize) (b : Std.Usize) : Result Std.Usize := do
  core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.count
    core.iter.range.StepUsize { start := a, «end» := b }

/-- [iter_std_overrides::range_max]:
    Source: 'tests/src/iter-std-overrides.rs', lines 61:0-63:1
    Visibility: public -/
def range_max (a : Std.Usize) (b : Std.Usize) : Result (Option Std.Usize) := do
  core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.max
    core.iter.range.StepUsize core.cmp.OrdUsize { start := a, «end» := b }

/-- [iter_std_overrides::incl_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 65:0-67:1
    Visibility: public -/
def incl_len (a : Std.Usize) (b : Std.Usize) : Result Std.Usize := do
  let ri ← core.ops.range.RangeInclusive.new a b
  core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.count
    core.iter.range.StepUsize ri

/-- [iter_std_overrides::incl_sum::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 70:20-70:32 -/
@[reducible]
def incl_sum.closure := Unit

/-- [iter_std_overrides::incl_sum::{impl core::ops::function::FnMut<(usize, usize), usize> for iter_std_overrides::incl_sum::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 70:20-70:32 -/
def incl_sum.closure.Insts.CoreOpsFunctionFnMutPairUsizeUsizeUsize.call_mut
  (c : incl_sum.closure) (tupled_args : (Std.Usize × Std.Usize)) :
  Result (Std.Usize × incl_sum.closure)
  := do
  let (s, x) := tupled_args
  let i ← s + x
  ok (i, c)

/-- [iter_std_overrides::incl_sum::{impl core::ops::function::FnOnce<(usize, usize), usize> for iter_std_overrides::incl_sum::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 70:20-70:32 -/
def incl_sum.closure.Insts.CoreOpsFunctionFnOncePairUsizeUsizeUsize.call_once
  (c : incl_sum.closure) (p : (Std.Usize × Std.Usize)) :
  Result Std.Usize
  := do
  let (i, _) ←
    incl_sum.closure.Insts.CoreOpsFunctionFnMutPairUsizeUsizeUsize.call_mut c p
  ok i

/-- Trait implementation: [iter_std_overrides::incl_sum::{impl core::ops::function::FnOnce<(usize, usize), usize> for iter_std_overrides::incl_sum::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 70:20-70:32 -/
@[reducible]
def incl_sum.closure.Insts.CoreOpsFunctionFnOncePairUsizeUsizeUsize :
  core.ops.function.FnOnce incl_sum.closure (Std.Usize × Std.Usize) Std.Usize
  := {
  call_once :=
    incl_sum.closure.Insts.CoreOpsFunctionFnOncePairUsizeUsizeUsize.call_once
}

/-- Trait implementation: [iter_std_overrides::incl_sum::{impl core::ops::function::FnMut<(usize, usize), usize> for iter_std_overrides::incl_sum::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 70:20-70:32 -/
@[reducible]
def incl_sum.closure.Insts.CoreOpsFunctionFnMutPairUsizeUsizeUsize :
  core.ops.function.FnMut incl_sum.closure (Std.Usize × Std.Usize) Std.Usize
  := {
  FnOnceInst := incl_sum.closure.Insts.CoreOpsFunctionFnOncePairUsizeUsizeUsize
  call_mut :=
    incl_sum.closure.Insts.CoreOpsFunctionFnMutPairUsizeUsizeUsize.call_mut
}

/-- [iter_std_overrides::incl_sum]:
    Source: 'tests/src/iter-std-overrides.rs', lines 69:0-71:1
    Visibility: public -/
def incl_sum (a : Std.Usize) (b : Std.Usize) : Result Std.Usize := do
  let ri ← core.ops.range.RangeInclusive.new a b
  core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.fold
    core.iter.range.StepUsize
    incl_sum.closure.Insts.CoreOpsFunctionFnMutPairUsizeUsizeUsize ri 0#usize
    ()

/-- [iter_std_overrides::incl_max]:
    Source: 'tests/src/iter-std-overrides.rs', lines 73:0-75:1
    Visibility: public -/
def incl_max (a : Std.Usize) (b : Std.Usize) : Result (Option Std.Usize) := do
  let ri ← core.ops.range.RangeInclusive.new a b
  core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.max
    core.iter.range.StepUsize core.cmp.OrdUsize ri

/-- [iter_std_overrides::range_twice]:
    Source: 'tests/src/iter-std-overrides.rs', lines 77:0-79:1
    Visibility: public -/
def range_twice (r : core.ops.range.Range Std.Usize) : Result Std.Usize := do
  let r1 ←
    core.ops.range.Range.Insts.CoreCloneClone.clone core.clone.CloneUsize r
  let i ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.count
      core.iter.range.StepUsize r1
  let i1 ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.count
      core.iter.range.StepUsize r
  i + i1

/-- [iter_std_overrides::incl_twice]:
    Source: 'tests/src/iter-std-overrides.rs', lines 81:0-83:1
    Visibility: public -/
def incl_twice
  (r : core.ops.range.RangeInclusive Std.Usize) : Result Std.Usize := do
  let ri ←
    core.ops.range.RangeInclusive.Insts.CoreCloneClone.clone
      core.clone.CloneUsize r
  let i ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.count
      core.iter.range.StepUsize ri
  let i1 ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.count
      core.iter.range.StepUsize r
  i + i1

/-- [iter_std_overrides::chunk_count]:
    Source: 'tests/src/iter-std-overrides.rs', lines 85:0-87:1
    Visibility: public -/
def chunk_count (v : Slice Std.U32) (n : Std.Usize) : Result Std.Usize := do
  let c ← core.slice.Slice.chunks v n
  core.slice.iter.Chunks.Insts.CoreIterTraitsIteratorIteratorSharedASlice.count
    c

/-- [iter_std_overrides::chunk_hint]:
    Source: 'tests/src/iter-std-overrides.rs', lines 89:0-91:1
    Visibility: public -/
def chunk_hint
  (v : Slice Std.U32) (n : Std.Usize) :
  Result (Std.Usize × (Option Std.Usize))
  := do
  let c ← core.slice.Slice.chunks v n
  core.slice.iter.Chunks.Insts.CoreIterTraitsIteratorIteratorSharedASlice.size_hint
    c

/-- [iter_std_overrides::last_chunk]: loop body 0:
    Source: 'tests/src/iter-std-overrides.rs', lines 96:4-98:5
    Visibility: public -/
@[rust_loop_body]
def last_chunk_loop.body
  (iter : core.slice.iter.Chunks Std.U32) (last : Std.Usize) :
  Result (ControlFlow ((core.slice.iter.Chunks Std.U32) × Std.Usize)
    Std.Usize)
  := do
  let (o, iter1) ←
    core.slice.iter.Chunks.Insts.CoreIterTraitsIteratorIteratorSharedASlice.next
      iter
  match o with
  | none => ok (done last)
  | some c => let last1 := Slice.len c
              ok (cont (iter1, last1))

/-- [iter_std_overrides::last_chunk]: loop 0:
    Source: 'tests/src/iter-std-overrides.rs', lines 96:4-98:5
    Visibility: public -/
@[rust_loop]
def last_chunk_loop
  (iter : core.slice.iter.Chunks Std.U32) (last : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, last1) => last_chunk_loop.body iter1 last1)
    (iter, last)

/-- [iter_std_overrides::last_chunk]:
    Source: 'tests/src/iter-std-overrides.rs', lines 94:0-100:1
    Visibility: public -/
def last_chunk (v : Slice Std.U32) (n : Std.Usize) : Result Std.Usize := do
  let iter ← core.slice.Slice.chunks v n
  last_chunk_loop iter 0#usize

/-- [iter_std_overrides::mut_len]:
    Source: 'tests/src/iter-std-overrides.rs', lines 105:0-107:1
    Visibility: public -/
def mut_len (v : Slice Std.U32) : Result (Std.Usize × (Slice Std.U32)) := do
  let (im, iter_mut_back) ← core.slice.Slice.iter_mut v
  let (i, im1) ←
    core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT.count im
  let v1 := iter_mut_back im1
  ok (i, v1)

/-- [iter_std_overrides::mut_hint]:
    Source: 'tests/src/iter-std-overrides.rs', lines 109:0-111:1
    Visibility: public -/
def mut_hint
  (v : Slice Std.U32) :
  Result ((Std.Usize × (Option Std.Usize)) × (Slice Std.U32))
  := do
  let (im, iter_mut_back) ← core.slice.Slice.iter_mut v
  let p ←
    core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT.size_hint
      im
  let v1 := iter_mut_back im
  ok (p, v1)

/-- [iter_std_overrides::halve_checked::{closure}]
    Source: 'tests/src/iter-std-overrides.rs', lines 114:17-114:65 -/
@[reducible]
def halve_checked.closure := Unit

/-- [iter_std_overrides::halve_checked::{impl core::ops::function::FnMut<(&'_0 u32,), core::result::Result<u32, u32>> for iter_std_overrides::halve_checked::{closure}}::call_mut]:
    Source: 'tests/src/iter-std-overrides.rs', lines 114:17-114:65 -/
def
  halve_checked.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ResultU32U32.call_mut
  (c : halve_checked.closure) (tupled_args : Std.U32) :
  Result ((core.result.Result Std.U32 Std.U32) × halve_checked.closure)
  := do
  let i ← Shared0U32.Insts.CoreOpsArithRemU32U32.rem tupled_args 2#u32
  if i = 0#u32
  then
    let i1 ← Shared0U32.Insts.CoreOpsArithDivU32U32.div tupled_args 2#u32
    ok (core.result.Result.Ok i1, c)
  else ok (core.result.Result.Err tupled_args, c)

/-- [iter_std_overrides::halve_checked::{impl core::ops::function::FnOnce<(&'_0 u32,), core::result::Result<u32, u32>> for iter_std_overrides::halve_checked::{closure}}::call_once]:
    Source: 'tests/src/iter-std-overrides.rs', lines 114:17-114:65 -/
def
  halve_checked.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ResultU32U32.call_once
  (c : halve_checked.closure) (i : Std.U32) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  let (r, _) ←
    halve_checked.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ResultU32U32.call_mut
      c i
  ok r

/-- Trait implementation: [iter_std_overrides::halve_checked::{impl core::ops::function::FnOnce<(&'_0 u32,), core::result::Result<u32, u32>> for iter_std_overrides::halve_checked::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 114:17-114:65 -/
@[reducible]
def
  halve_checked.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ResultU32U32
  : core.ops.function.FnOnce halve_checked.closure Std.U32 (core.result.Result
  Std.U32 Std.U32) := {
  call_once :=
    halve_checked.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ResultU32U32.call_once
}

/-- Trait implementation: [iter_std_overrides::halve_checked::{impl core::ops::function::FnMut<(&'_0 u32,), core::result::Result<u32, u32>> for iter_std_overrides::halve_checked::{closure}}]
    Source: 'tests/src/iter-std-overrides.rs', lines 114:17-114:65 -/
@[reducible]
def halve_checked.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ResultU32U32
  : core.ops.function.FnMut halve_checked.closure Std.U32 (core.result.Result
  Std.U32 Std.U32) := {
  FnOnceInst :=
    halve_checked.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ResultU32U32
  call_mut :=
    halve_checked.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ResultU32U32.call_mut
}

/-- [iter_std_overrides::halve_checked]:
    Source: 'tests/src/iter-std-overrides.rs', lines 113:0-115:1
    Visibility: public -/
def halve_checked
  (v : Slice Std.U32) :
  Result (core.result.Result (alloc.vec.Vec Std.U32) Std.U32)
  := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      halve_checked.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ResultU32U32
      i ()
  core.iter.traits.iterator.Iterator.collect.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    halve_checked.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ResultU32U32)
    (core.result.Result.Insts.CoreIterTraitsCollectFromIteratorResult Std.U32
    (core.iter.traits.collect.FromIteratorVec Std.U32)) m

end iter_std_overrides
