-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [iter_adapters_std]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace iter_adapters_std

/-- Trait implementation: [core::cmp::impls::{impl core::cmp::Ord for usize}::{impl core::ops::function::FnOnce<(&'_0 usize, &'_1 usize), core::cmp::Ordering> for core::cmp::impls::{impl core::cmp::Ord for usize}::cmp<'static, 'static>}]
    Source: '/rustc/library/core/src/cmp.rs', lines 2347:16-2347:55
    Name pattern: [core::ops::function::FnOnce<@, (&'0 usize, &'1 usize), core::cmp::Ordering>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnOnce<@, (&'0 usize, &'1 usize), core::cmp::Ordering>"]
def
  core.cmp.impls.OrdUsize.cmp.Insts.CoreOpsFunctionFnOncePairShared0UsizeShared1UsizeOrdering
  : core.ops.function.FnOnce (Std.Usize → Std.Usize → Ordering) (Std.Usize
  × Std.Usize) Ordering := {
  call_once :=
    core.cmp.impls.OrdUsize.cmp.Insts.CoreOpsFunctionFnOnce.call_once
}

/-- Trait implementation: [core::cmp::impls::{impl core::cmp::Ord for usize}::{impl core::ops::function::FnMut<(&'_0 usize, &'_1 usize), core::cmp::Ordering> for core::cmp::impls::{impl core::cmp::Ord for usize}::cmp<'static, 'static>}]
    Source: '/rustc/library/core/src/cmp.rs', lines 2347:16-2347:55
    Name pattern: [core::ops::function::FnMut<@, (&'0 usize, &'1 usize), core::cmp::Ordering>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnMut<@, (&'0 usize, &'1 usize), core::cmp::Ordering>"]
def
  core.cmp.impls.OrdUsize.cmp.Insts.CoreOpsFunctionFnMutPairShared0UsizeShared1UsizeOrdering
  : core.ops.function.FnMut (Std.Usize → Std.Usize → Ordering) (Std.Usize
  × Std.Usize) Ordering := {
  FnOnceInst :=
    core.cmp.impls.OrdUsize.cmp.Insts.CoreOpsFunctionFnOncePairShared0UsizeShared1UsizeOrdering
  call_mut := core.cmp.impls.OrdUsize.cmp.Insts.CoreOpsFunctionFnMut.call_mut
}

/-- [iter_adapters_std::sum_doubled::{closure#1}]
    Source: 'tests/src/iter-adapters-std.rs', lines 9:36-9:48 -/
@[reducible]
def sum_doubled.closure_1 := Unit

/-- [iter_adapters_std::sum_doubled::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_adapters_std::sum_doubled::{closure#1}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 9:36-9:48 -/
def sum_doubled.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : sum_doubled.closure_1) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × sum_doubled.closure_1)
  := do
  let (a, x) := tupled_args
  let i ← a + x
  ok (i, c)

/-- [iter_adapters_std::sum_doubled::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_adapters_std::sum_doubled::{closure#1}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 9:36-9:48 -/
def sum_doubled.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : sum_doubled.closure_1) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    sum_doubled.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_adapters_std::sum_doubled::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_adapters_std::sum_doubled::{closure#1}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 9:36-9:48 -/
@[reducible]
def sum_doubled.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce sum_doubled.closure_1 (Std.U32 × Std.U32) Std.U32
  := {
  call_once :=
    sum_doubled.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_adapters_std::sum_doubled::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_adapters_std::sum_doubled::{closure#1}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 9:36-9:48 -/
@[reducible]
def sum_doubled.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut sum_doubled.closure_1 (Std.U32 × Std.U32) Std.U32
  := {
  FnOnceInst := sum_doubled.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut :=
    sum_doubled.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_adapters_std::sum_doubled::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 9:17-9:26 -/
@[reducible]
def sum_doubled.closure := Unit

/-- [iter_adapters_std::sum_doubled::{impl core::ops::function::FnMut<(&'_0 u32,), u32> for iter_adapters_std::sum_doubled::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 9:17-9:26 -/
def sum_doubled.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
  (c : sum_doubled.closure) (tupled_args : Std.U32) :
  Result (Std.U32 × sum_doubled.closure)
  := do
  let i ← Shared0U32.Insts.CoreOpsArithMulU32U32.mul tupled_args 2#u32
  ok (i, c)

/-- [iter_adapters_std::sum_doubled::{impl core::ops::function::FnOnce<(&'_0 u32,), u32> for iter_adapters_std::sum_doubled::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 9:17-9:26 -/
def sum_doubled.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32.call_once
  (c : sum_doubled.closure) (i : Std.U32) : Result Std.U32 := do
  let (i1, _) ←
    sum_doubled.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut c
      i
  ok i1

/-- Trait implementation: [iter_adapters_std::sum_doubled::{impl core::ops::function::FnOnce<(&'_0 u32,), u32> for iter_adapters_std::sum_doubled::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 9:17-9:26 -/
@[reducible]
def sum_doubled.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32 :
  core.ops.function.FnOnce sum_doubled.closure Std.U32 Std.U32 := {
  call_once :=
    sum_doubled.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32.call_once
}

/-- Trait implementation: [iter_adapters_std::sum_doubled::{impl core::ops::function::FnMut<(&'_0 u32,), u32> for iter_adapters_std::sum_doubled::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 9:17-9:26 -/
@[reducible]
def sum_doubled.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 :
  core.ops.function.FnMut sum_doubled.closure Std.U32 Std.U32 := {
  FnOnceInst :=
    sum_doubled.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32
  call_mut :=
    sum_doubled.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
}

/-- [iter_adapters_std::sum_doubled]:
    Source: 'tests/src/iter-adapters-std.rs', lines 8:0-10:1
    Visibility: public -/
def sum_doubled (v : Slice Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      sum_doubled.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 i ()
  core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    sum_doubled.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32
    sum_doubled.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32 m 0#u32 ()

/-- [iter_adapters_std::count_even::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 13:20-13:36 -/
@[reducible]
def count_even.closure := Unit

/-- [iter_adapters_std::count_even::{impl core::ops::function::FnMut<(&'_0 &'_1 u32,), bool> for iter_adapters_std::count_even::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 13:20-13:36 -/
def
  count_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
  (c : count_even.closure) (tupled_args : Std.U32) :
  Result (Bool × count_even.closure)
  := do
  let i ← tupled_args % 2#u32
  ok (i = 0#u32, c)

/-- [iter_adapters_std::count_even::{impl core::ops::function::FnOnce<(&'_0 &'_1 u32,), bool> for iter_adapters_std::count_even::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 13:20-13:36 -/
def
  count_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool.call_once
  (c : count_even.closure) (i : Std.U32) : Result Bool := do
  let (b, _) ←
    count_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
      c i
  ok b

/-- Trait implementation: [iter_adapters_std::count_even::{impl core::ops::function::FnOnce<(&'_0 &'_1 u32,), bool> for iter_adapters_std::count_even::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 13:20-13:36 -/
@[reducible]
def count_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool :
  core.ops.function.FnOnce count_even.closure Std.U32 Bool := {
  call_once :=
    count_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool.call_once
}

/-- Trait implementation: [iter_adapters_std::count_even::{impl core::ops::function::FnMut<(&'_0 &'_1 u32,), bool> for iter_adapters_std::count_even::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 13:20-13:36 -/
@[reducible]
def count_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool :
  core.ops.function.FnMut count_even.closure Std.U32 Bool := {
  FnOnceInst :=
    count_even.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool
  call_mut :=
    count_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
}

/-- [iter_adapters_std::count_even]:
    Source: 'tests/src/iter-adapters-std.rs', lines 12:0-14:1
    Visibility: public -/
def count_even (v : Slice Std.U32) : Result Std.Usize := do
  let i ← core.slice.Slice.iter v
  let f ←
    core.iter.traits.iterator.Iterator.filter.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      count_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool i
      ()
  core.iter.adapters.filter.Filter.Insts.CoreIterTraitsIteratorIterator.count
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    count_even.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool f

/-- [iter_adapters_std::any_big::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 17:17-17:28 -/
@[reducible]
def any_big.closure := Unit

/-- [iter_adapters_std::any_big::{impl core::ops::function::FnMut<(&'_0 u32,), bool> for iter_adapters_std::any_big::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 17:17-17:28 -/
def any_big.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool.call_mut
  (c : any_big.closure) (tupled_args : Std.U32) :
  Result (Bool × any_big.closure)
  := do
  ok (tupled_args > 10#u32, c)

/-- [iter_adapters_std::any_big::{impl core::ops::function::FnOnce<(&'_0 u32,), bool> for iter_adapters_std::any_big::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 17:17-17:28 -/
def any_big.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool.call_once
  (c : any_big.closure) (i : Std.U32) : Result Bool := do
  let (b, _) ←
    any_big.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool.call_mut c i
  ok b

/-- Trait implementation: [iter_adapters_std::any_big::{impl core::ops::function::FnOnce<(&'_0 u32,), bool> for iter_adapters_std::any_big::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 17:17-17:28 -/
@[reducible]
def any_big.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool :
  core.ops.function.FnOnce any_big.closure Std.U32 Bool := {
  call_once :=
    any_big.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool.call_once
}

/-- Trait implementation: [iter_adapters_std::any_big::{impl core::ops::function::FnMut<(&'_0 u32,), bool> for iter_adapters_std::any_big::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 17:17-17:28 -/
@[reducible]
def any_big.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool :
  core.ops.function.FnMut any_big.closure Std.U32 Bool := {
  FnOnceInst := any_big.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool
  call_mut :=
    any_big.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool.call_mut
}

/-- [iter_adapters_std::any_big]:
    Source: 'tests/src/iter-adapters-std.rs', lines 16:0-18:1
    Visibility: public -/
def any_big (v : Slice Std.U32) : Result Bool := do
  let i ← core.slice.Slice.iter v
  let (b, _) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.any
      any_big.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool i ()
  ok b

/-- [iter_adapters_std::halves::{closure#1}]
    Source: 'tests/src/iter-adapters-std.rs', lines 23:17-23:29 -/
@[reducible]
def halves.closure_1 := Unit

/-- [iter_adapters_std::halves::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_adapters_std::halves::{closure#1}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 23:17-23:29 -/
def halves.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : halves.closure_1) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × halves.closure_1)
  := do
  let (a, x) := tupled_args
  let i ← a + x
  ok (i, c)

/-- [iter_adapters_std::halves::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_adapters_std::halves::{closure#1}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 23:17-23:29 -/
def halves.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : halves.closure_1) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    halves.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_adapters_std::halves::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_adapters_std::halves::{closure#1}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 23:17-23:29 -/
@[reducible]
def halves.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce halves.closure_1 (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    halves.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_adapters_std::halves::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_adapters_std::halves::{closure#1}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 23:17-23:29 -/
@[reducible]
def halves.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut halves.closure_1 (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := halves.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut := halves.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_adapters_std::halves::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 22:20-22:67 -/
@[reducible]
def halves.closure := Unit

/-- [iter_adapters_std::halves::{impl core::ops::function::FnMut<(&'_0 u32,), core::option::Option<u32>> for iter_adapters_std::halves::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 22:20-22:67 -/
def halves.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32.call_mut
  (c : halves.closure) (tupled_args : Std.U32) :
  Result ((Option Std.U32) × halves.closure)
  := do
  let i ← Shared0U32.Insts.CoreOpsArithRemU32U32.rem tupled_args 2#u32
  if i = 0#u32
  then
    let i1 ← Shared0U32.Insts.CoreOpsArithDivU32U32.div tupled_args 2#u32
    ok (some i1, c)
  else ok (none, c)

/-- [iter_adapters_std::halves::{impl core::ops::function::FnOnce<(&'_0 u32,), core::option::Option<u32>> for iter_adapters_std::halves::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 22:20-22:67 -/
def
  halves.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32.call_once
  (c : halves.closure) (i : Std.U32) : Result (Option Std.U32) := do
  let (o, _) ←
    halves.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32.call_mut
      c i
  ok o

/-- Trait implementation: [iter_adapters_std::halves::{impl core::ops::function::FnOnce<(&'_0 u32,), core::option::Option<u32>> for iter_adapters_std::halves::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 22:20-22:67 -/
@[reducible]
def halves.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32 :
  core.ops.function.FnOnce halves.closure Std.U32 (Option Std.U32) := {
  call_once :=
    halves.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32.call_once
}

/-- Trait implementation: [iter_adapters_std::halves::{impl core::ops::function::FnMut<(&'_0 u32,), core::option::Option<u32>> for iter_adapters_std::halves::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 22:20-22:67 -/
@[reducible]
def halves.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32 :
  core.ops.function.FnMut halves.closure Std.U32 (Option Std.U32) := {
  FnOnceInst :=
    halves.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32
  call_mut :=
    halves.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32.call_mut
}

/-- [iter_adapters_std::halves]:
    Source: 'tests/src/iter-adapters-std.rs', lines 20:0-24:1
    Visibility: public -/
def halves (v : Slice Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter v
  let fm ←
    core.iter.traits.iterator.Iterator.filter_map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      halves.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32 i ()
  core.iter.adapters.filter_map.FilterMap.Insts.CoreIterTraitsIteratorIterator.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    halves.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32
    halves.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32 fm 0#u32 ()

/-- [iter_adapters_std::chained]:
    Source: 'tests/src/iter-adapters-std.rs', lines 26:0-28:1
    Visibility: public -/
def chained (a : Slice Std.U32) (b : Slice Std.U32) : Result Std.Usize := do
  let i ← core.slice.Slice.iter a
  let i1 ← core.slice.Slice.iter b
  let c ←
    core.iter.traits.iterator.Iterator.chain.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  core.iter.adapters.chain.Chain.Insts.CoreIterTraitsIteratorIterator.count
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.iterator.IteratorSliceIter Std.U32) c

/-- [iter_adapters_std::chained_sum::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 31:37-31:49 -/
@[reducible]
def chained_sum.closure := Unit

/-- [iter_adapters_std::chained_sum::{impl core::ops::function::FnMut<(u32, &'_0 u32), u32> for iter_adapters_std::chained_sum::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 31:37-31:49 -/
def chained_sum.closure.Insts.CoreOpsFunctionFnMutPairU32Shared0U32U32.call_mut
  (c : chained_sum.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × chained_sum.closure)
  := do
  let (s, x) := tupled_args
  let i ← U32.Insts.CoreOpsArithAddShared0U32U32.add s x
  ok (i, c)

/-- [iter_adapters_std::chained_sum::{impl core::ops::function::FnOnce<(u32, &'_0 u32), u32> for iter_adapters_std::chained_sum::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 31:37-31:49 -/
def
  chained_sum.closure.Insts.CoreOpsFunctionFnOncePairU32Shared0U32U32.call_once
  (c : chained_sum.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    chained_sum.closure.Insts.CoreOpsFunctionFnMutPairU32Shared0U32U32.call_mut
      c p
  ok i

/-- Trait implementation: [iter_adapters_std::chained_sum::{impl core::ops::function::FnOnce<(u32, &'_0 u32), u32> for iter_adapters_std::chained_sum::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 31:37-31:49 -/
@[reducible]
def chained_sum.closure.Insts.CoreOpsFunctionFnOncePairU32Shared0U32U32 :
  core.ops.function.FnOnce chained_sum.closure (Std.U32 × Std.U32) Std.U32
  := {
  call_once :=
    chained_sum.closure.Insts.CoreOpsFunctionFnOncePairU32Shared0U32U32.call_once
}

/-- Trait implementation: [iter_adapters_std::chained_sum::{impl core::ops::function::FnMut<(u32, &'_0 u32), u32> for iter_adapters_std::chained_sum::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 31:37-31:49 -/
@[reducible]
def chained_sum.closure.Insts.CoreOpsFunctionFnMutPairU32Shared0U32U32 :
  core.ops.function.FnMut chained_sum.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst :=
    chained_sum.closure.Insts.CoreOpsFunctionFnOncePairU32Shared0U32U32
  call_mut :=
    chained_sum.closure.Insts.CoreOpsFunctionFnMutPairU32Shared0U32U32.call_mut
}

/-- [iter_adapters_std::chained_sum]:
    Source: 'tests/src/iter-adapters-std.rs', lines 30:0-32:1
    Visibility: public -/
def chained_sum (a : Slice Std.U32) (b : Slice Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter a
  let i1 ← core.slice.Slice.iter b
  let c ←
    core.iter.traits.iterator.Iterator.chain.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  core.iter.adapters.chain.Chain.Insts.CoreIterTraitsIteratorIterator.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    chained_sum.closure.Insts.CoreOpsFunctionFnMutPairU32Shared0U32U32 c 0#u32
    ()

/-- [iter_adapters_std::flat::{closure#1}]
    Source: 'tests/src/iter-adapters-std.rs', lines 38:17-38:34 -/
@[reducible]
def flat.closure_1 := Unit

/-- [iter_adapters_std::flat::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_adapters_std::flat::{closure#1}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 38:17-38:34 -/
def flat.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : flat.closure_1) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × flat.closure_1)
  := do
  let (a, x) := tupled_args
  let i ← a * 10#u32
  let i1 ← i + x
  ok (i1, c)

/-- [iter_adapters_std::flat::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_adapters_std::flat::{closure#1}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 38:17-38:34 -/
def flat.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : flat.closure_1) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    flat.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_adapters_std::flat::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_adapters_std::flat::{closure#1}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 38:17-38:34 -/
@[reducible]
def flat.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce flat.closure_1 (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    flat.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_adapters_std::flat::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_adapters_std::flat::{closure#1}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 38:17-38:34 -/
@[reducible]
def flat.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut flat.closure_1 (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := flat.closure_1.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut := flat.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_adapters_std::flat::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 37:18-37:71 -/
@[reducible]
def flat.closure := Unit

/-- [iter_adapters_std::flat::{impl core::ops::function::FnMut<(&'_0 u32,), core::iter::adapters::chain::Chain<core::iter::sources::once::Once<u32>, core::iter::sources::once::Once<u32>>> for iter_adapters_std::flat::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 37:18-37:71 -/
def
  flat.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ChainOnceU32OnceU32.call_mut
  (c : flat.closure) (tupled_args : Std.U32) :
  Result ((core.iter.adapters.chain.Chain (core.iter.sources.once.Once Std.U32)
    (core.iter.sources.once.Once Std.U32)) × flat.closure)
  := do
  let o ← core.iter.sources.once.once tupled_args
  let i ← SharedU32.Insts.CoreOpsArithAddU32U32.add tupled_args 1#u32
  let o1 ← core.iter.sources.once.once i
  let c1 ←
    core.iter.traits.iterator.Iterator.chain.default
      (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator
      Std.U32) (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator
      Std.U32)) o o1
  ok (c1, c)

/-- [iter_adapters_std::flat::{impl core::ops::function::FnOnce<(&'_0 u32,), core::iter::adapters::chain::Chain<core::iter::sources::once::Once<u32>, core::iter::sources::once::Once<u32>>> for iter_adapters_std::flat::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 37:18-37:71 -/
def
  flat.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ChainOnceU32OnceU32.call_once
  (c : flat.closure) (i : Std.U32) :
  Result (core.iter.adapters.chain.Chain (core.iter.sources.once.Once Std.U32)
    (core.iter.sources.once.Once Std.U32))
  := do
  let (c1, _) ←
    flat.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ChainOnceU32OnceU32.call_mut
      c i
  ok c1

/-- Trait implementation: [iter_adapters_std::flat::{impl core::ops::function::FnOnce<(&'_0 u32,), core::iter::adapters::chain::Chain<core::iter::sources::once::Once<u32>, core::iter::sources::once::Once<u32>>> for iter_adapters_std::flat::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 37:18-37:71 -/
@[reducible]
def flat.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ChainOnceU32OnceU32
  : core.ops.function.FnOnce flat.closure Std.U32
  (core.iter.adapters.chain.Chain (core.iter.sources.once.Once Std.U32)
  (core.iter.sources.once.Once Std.U32)) := {
  call_once :=
    flat.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ChainOnceU32OnceU32.call_once
}

/-- Trait implementation: [iter_adapters_std::flat::{impl core::ops::function::FnMut<(&'_0 u32,), core::iter::adapters::chain::Chain<core::iter::sources::once::Once<u32>, core::iter::sources::once::Once<u32>>> for iter_adapters_std::flat::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 37:18-37:71 -/
@[reducible]
def flat.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ChainOnceU32OnceU32 :
  core.ops.function.FnMut flat.closure Std.U32 (core.iter.adapters.chain.Chain
  (core.iter.sources.once.Once Std.U32) (core.iter.sources.once.Once Std.U32))
  := {
  FnOnceInst :=
    flat.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32ChainOnceU32OnceU32
  call_mut :=
    flat.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ChainOnceU32OnceU32.call_mut
}

/-- [iter_adapters_std::flat]:
    Source: 'tests/src/iter-adapters-std.rs', lines 35:0-39:1
    Visibility: public -/
def flat (v : Slice Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter v
  let fm ←
    core.iter.traits.iterator.Iterator.flat_map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.adapters.chain.Chain.Insts.CoreIterTraitsIteratorIterator
      (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator
      Std.U32)
      (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator
      Std.U32)))
      flat.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ChainOnceU32OnceU32
      i ()
  core.iter.adapters.flatten.FlatMap.Insts.CoreIterTraitsIteratorIterator.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.collect.IntoIterator.Blanket
    (core.iter.adapters.chain.Chain.Insts.CoreIterTraitsIteratorIterator
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator Std.U32)
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator
    Std.U32)))
    flat.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32ChainOnceU32OnceU32
    flat.closure_1.Insts.CoreOpsFunctionFnMutPairU32U32U32 fm 0#u32 ()

/-- [iter_adapters_std::once_then_empty]:
    Source: 'tests/src/iter-adapters-std.rs', lines 41:0-43:1
    Visibility: public -/
def once_then_empty (x : Std.U32) : Result Std.Usize := do
  let o ← core.iter.sources.once.once x
  let e ← core.iter.sources.empty.empty Std.U32
  let c ←
    core.iter.traits.iterator.Iterator.chain.default
      (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator
      Std.U32) (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.sources.empty.Empty.Insts.CoreIterTraitsIteratorIterator
      Std.U32)) o e
  core.iter.adapters.chain.Chain.Insts.CoreIterTraitsIteratorIterator.count
    (core.iter.sources.once.Once.Insts.CoreIterTraitsIteratorIterator Std.U32)
    (core.iter.sources.empty.Empty.Insts.CoreIterTraitsIteratorIterator
    Std.U32) c

/-- [iter_adapters_std::largest::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 46:17-46:23 -/
@[reducible]
def largest.closure := Unit

/-- [iter_adapters_std::largest::{impl core::ops::function::FnMut<(&'_0 usize,), usize> for iter_adapters_std::largest::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 46:17-46:23 -/
def largest.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
  (c : largest.closure) (tupled_args : Std.Usize) :
  Result (Std.Usize × largest.closure)
  := do
  ok (tupled_args, c)

/-- [iter_adapters_std::largest::{impl core::ops::function::FnOnce<(&'_0 usize,), usize> for iter_adapters_std::largest::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 46:17-46:23 -/
def largest.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize.call_once
  (c : largest.closure) (i : Std.Usize) : Result Std.Usize := do
  let (i1, _) ←
    largest.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut c
      i
  ok i1

/-- Trait implementation: [iter_adapters_std::largest::{impl core::ops::function::FnOnce<(&'_0 usize,), usize> for iter_adapters_std::largest::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 46:17-46:23 -/
@[reducible]
def largest.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize :
  core.ops.function.FnOnce largest.closure Std.Usize Std.Usize := {
  call_once :=
    largest.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize.call_once
}

/-- Trait implementation: [iter_adapters_std::largest::{impl core::ops::function::FnMut<(&'_0 usize,), usize> for iter_adapters_std::largest::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 46:17-46:23 -/
@[reducible]
def largest.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize :
  core.ops.function.FnMut largest.closure Std.Usize Std.Usize := {
  FnOnceInst :=
    largest.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize
  call_mut :=
    largest.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
}

/-- [iter_adapters_std::largest]:
    Source: 'tests/src/iter-adapters-std.rs', lines 45:0-47:1
    Visibility: public -/
def largest (v : Slice Std.Usize) : Result (Option Std.Usize) := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
      largest.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize i ()
  core.iter.traits.iterator.Iterator.max.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
    largest.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize)
    core.cmp.OrdUsize m

/-- [iter_adapters_std::largest_by::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 51:17-51:23 -/
@[reducible]
def largest_by.closure := Unit

/-- [iter_adapters_std::largest_by::{impl core::ops::function::FnMut<(&'_0 usize,), usize> for iter_adapters_std::largest_by::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 51:17-51:23 -/
def
  largest_by.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
  (c : largest_by.closure) (tupled_args : Std.Usize) :
  Result (Std.Usize × largest_by.closure)
  := do
  ok (tupled_args, c)

/-- [iter_adapters_std::largest_by::{impl core::ops::function::FnOnce<(&'_0 usize,), usize> for iter_adapters_std::largest_by::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 51:17-51:23 -/
def
  largest_by.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize.call_once
  (c : largest_by.closure) (i : Std.Usize) : Result Std.Usize := do
  let (i1, _) ←
    largest_by.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
      c i
  ok i1

/-- Trait implementation: [iter_adapters_std::largest_by::{impl core::ops::function::FnOnce<(&'_0 usize,), usize> for iter_adapters_std::largest_by::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 51:17-51:23 -/
@[reducible]
def largest_by.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize :
  core.ops.function.FnOnce largest_by.closure Std.Usize Std.Usize := {
  call_once :=
    largest_by.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize.call_once
}

/-- Trait implementation: [iter_adapters_std::largest_by::{impl core::ops::function::FnMut<(&'_0 usize,), usize> for iter_adapters_std::largest_by::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 51:17-51:23 -/
@[reducible]
def largest_by.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize :
  core.ops.function.FnMut largest_by.closure Std.Usize Std.Usize := {
  FnOnceInst :=
    largest_by.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize
  call_mut :=
    largest_by.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
}

/-- [iter_adapters_std::largest_by]:
    Source: 'tests/src/iter-adapters-std.rs', lines 50:0-52:1
    Visibility: public -/
def largest_by (v : Slice Std.Usize) : Result (Option Std.Usize) := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
      largest_by.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize i ()
  core.iter.traits.iterator.Iterator.max_by.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
    largest_by.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize)
    core.cmp.impls.OrdUsize.cmp.Insts.CoreOpsFunctionFnMutPairShared0UsizeShared1UsizeOrdering
    m (core.cmp.impls.OrdUsize.cmp)

/-- [iter_adapters_std::total::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 55:17-55:23 -/
@[reducible]
def total.closure := Unit

/-- [iter_adapters_std::total::{impl core::ops::function::FnMut<(&'_0 usize,), usize> for iter_adapters_std::total::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 55:17-55:23 -/
def total.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
  (c : total.closure) (tupled_args : Std.Usize) :
  Result (Std.Usize × total.closure)
  := do
  ok (tupled_args, c)

/-- [iter_adapters_std::total::{impl core::ops::function::FnOnce<(&'_0 usize,), usize> for iter_adapters_std::total::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 55:17-55:23 -/
def total.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize.call_once
  (c : total.closure) (i : Std.Usize) : Result Std.Usize := do
  let (i1, _) ←
    total.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut c i
  ok i1

/-- Trait implementation: [iter_adapters_std::total::{impl core::ops::function::FnOnce<(&'_0 usize,), usize> for iter_adapters_std::total::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 55:17-55:23 -/
@[reducible]
def total.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize :
  core.ops.function.FnOnce total.closure Std.Usize Std.Usize := {
  call_once :=
    total.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize.call_once
}

/-- Trait implementation: [iter_adapters_std::total::{impl core::ops::function::FnMut<(&'_0 usize,), usize> for iter_adapters_std::total::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 55:17-55:23 -/
@[reducible]
def total.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize :
  core.ops.function.FnMut total.closure Std.Usize Std.Usize := {
  FnOnceInst := total.closure.Insts.CoreOpsFunctionFnOnceTupleShared0UsizeUsize
  call_mut :=
    total.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize.call_mut
}

/-- [iter_adapters_std::total]:
    Source: 'tests/src/iter-adapters-std.rs', lines 54:0-56:1
    Visibility: public -/
def total (v : Slice Std.Usize) : Result Std.Usize := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
      total.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize i ()
  core.iter.traits.iterator.Iterator.sum.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
    total.closure.Insts.CoreOpsFunctionFnMutTupleShared0UsizeUsize)
    Usize.Insts.CoreIterTraitsAccumSumUsize m

/-- [iter_adapters_std::hint::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 59:17-59:26 -/
@[reducible]
def hint.closure := Unit

/-- [iter_adapters_std::hint::{impl core::ops::function::FnMut<(&'_0 u32,), u32> for iter_adapters_std::hint::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 59:17-59:26 -/
def hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
  (c : hint.closure) (tupled_args : Std.U32) :
  Result (Std.U32 × hint.closure)
  := do
  let i ← SharedU32.Insts.CoreOpsArithAddU32U32.add tupled_args 1#u32
  ok (i, c)

/-- [iter_adapters_std::hint::{impl core::ops::function::FnOnce<(&'_0 u32,), u32> for iter_adapters_std::hint::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 59:17-59:26 -/
def hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32.call_once
  (c : hint.closure) (i : Std.U32) : Result Std.U32 := do
  let (i1, _) ←
    hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut c i
  ok i1

/-- Trait implementation: [iter_adapters_std::hint::{impl core::ops::function::FnOnce<(&'_0 u32,), u32> for iter_adapters_std::hint::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 59:17-59:26 -/
@[reducible]
def hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32 :
  core.ops.function.FnOnce hint.closure Std.U32 Std.U32 := {
  call_once :=
    hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32.call_once
}

/-- Trait implementation: [iter_adapters_std::hint::{impl core::ops::function::FnMut<(&'_0 u32,), u32> for iter_adapters_std::hint::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 59:17-59:26 -/
@[reducible]
def hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 :
  core.ops.function.FnMut hint.closure Std.U32 Std.U32 := {
  FnOnceInst := hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32U32
  call_mut :=
    hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32.call_mut
}

/-- [iter_adapters_std::hint]:
    Source: 'tests/src/iter-adapters-std.rs', lines 58:0-60:1
    Visibility: public -/
def hint (v : Slice Std.U32) : Result (Std.Usize × (Option Std.Usize)) := do
  let i ← core.slice.Slice.iter v
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 i ()
  core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.size_hint
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32U32 m

/-- [iter_adapters_std::filter_hint::{closure}]
    Source: 'tests/src/iter-adapters-std.rs', lines 63:20-63:31 -/
@[reducible]
def filter_hint.closure := Unit

/-- [iter_adapters_std::filter_hint::{impl core::ops::function::FnMut<(&'_0 &'_1 u32,), bool> for iter_adapters_std::filter_hint::{closure}}::call_mut]:
    Source: 'tests/src/iter-adapters-std.rs', lines 63:20-63:31 -/
def
  filter_hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
  (c : filter_hint.closure) (tupled_args : Std.U32) :
  Result (Bool × filter_hint.closure)
  := do
  ok (tupled_args > 1#u32, c)

/-- [iter_adapters_std::filter_hint::{impl core::ops::function::FnOnce<(&'_0 &'_1 u32,), bool> for iter_adapters_std::filter_hint::{closure}}::call_once]:
    Source: 'tests/src/iter-adapters-std.rs', lines 63:20-63:31 -/
def
  filter_hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool.call_once
  (c : filter_hint.closure) (i : Std.U32) : Result Bool := do
  let (b, _) ←
    filter_hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
      c i
  ok b

/-- Trait implementation: [iter_adapters_std::filter_hint::{impl core::ops::function::FnOnce<(&'_0 &'_1 u32,), bool> for iter_adapters_std::filter_hint::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 63:20-63:31 -/
@[reducible]
def filter_hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool :
  core.ops.function.FnOnce filter_hint.closure Std.U32 Bool := {
  call_once :=
    filter_hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool.call_once
}

/-- Trait implementation: [iter_adapters_std::filter_hint::{impl core::ops::function::FnMut<(&'_0 &'_1 u32,), bool> for iter_adapters_std::filter_hint::{closure}}]
    Source: 'tests/src/iter-adapters-std.rs', lines 63:20-63:31 -/
@[reducible]
def filter_hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool :
  core.ops.function.FnMut filter_hint.closure Std.U32 Bool := {
  FnOnceInst :=
    filter_hint.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1U32Bool
  call_mut :=
    filter_hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool.call_mut
}

/-- [iter_adapters_std::filter_hint]:
    Source: 'tests/src/iter-adapters-std.rs', lines 62:0-64:1
    Visibility: public -/
def filter_hint
  (v : Slice Std.U32) : Result (Std.Usize × (Option Std.Usize)) := do
  let i ← core.slice.Slice.iter v
  let f ←
    core.iter.traits.iterator.Iterator.filter.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      filter_hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool
      i ()
  core.iter.adapters.filter.Filter.Insts.CoreIterTraitsIteratorIterator.size_hint
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    filter_hint.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1U32Bool f

/-- [iter_adapters_std::chain_hint]:
    Source: 'tests/src/iter-adapters-std.rs', lines 66:0-68:1
    Visibility: public -/
def chain_hint
  (a : Slice Std.U32) (b : Slice Std.U32) :
  Result (Std.Usize × (Option Std.Usize))
  := do
  let i ← core.slice.Slice.iter a
  let i1 ← core.slice.Slice.iter b
  let c ←
    core.iter.traits.iterator.Iterator.chain.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  core.iter.adapters.chain.Chain.Insts.CoreIterTraitsIteratorIterator.size_hint
    (core.iter.traits.iterator.IteratorSliceIter Std.U32)
    (core.iter.traits.iterator.IteratorSliceIter Std.U32) c

end iter_adapters_std
