-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loops_nested_exits]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loops_nested_exits

/-- [loops_nested_exits::check]:
    Source: 'tests/src/loops-nested-exits.rs', lines 8:0-14:1 -/
def check (x : Std.U32) : Result (core.result.Result Std.U32 Std.U32) := do
  if x = 0#u32
  then ok (core.result.Result.Err 7#u32)
  else ok (core.result.Result.Ok x)

/-- [loops_nested_exits::sum_checked]: loop body 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 23:8-30:1
    Visibility: public -/
@[rust_loop_body]
def sum_checked_loop0_loop0.body
  (xss : Slice (alloc.vec.Vec Std.U32)) (i : Std.Usize) (s : Std.U32)
  (j : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (Std.U32 × (Option
    (core.result.Result Std.U32 Std.U32))))
  := do
  let v ← Slice.index_usize xss i
  let i1 := alloc.vec.Vec.len v
  if j < i1
  then
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v j
    let r ← check i2
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let s1 ← lift (core.num.U32.wrapping_add s val)
      let j1 ← j + 1#usize
      ok (cont (s1, j1))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Std.U32 (core.convert.FromSame Std.U32) residual
      ok (done (s, some r1))
  else ok (done (s, none))

/-- [loops_nested_exits::sum_checked]: loop 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 23:8-30:1
    Visibility: public -/
@[rust_loop]
def sum_checked_loop0_loop0
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize)
  (j : Std.Usize) :
  Result (Std.U32 × (Option (core.result.Result Std.U32 Std.U32)))
  := do
  loop
    (fun (s1, j1) => sum_checked_loop0_loop0.body xss i s1 j1)
    (s, j)

/-- [loops_nested_exits::sum_checked]: loop body 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 21:4-30:1
    Visibility: public -/
@[rust_loop_body]
def sum_checked_loop0.body
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (core.result.Result Std.U32
    Std.U32))
  := do
  let i1 := Slice.len xss
  if i < i1
  then
    let (s1, loop_return) ← sum_checked_loop0_loop0 xss s i 0#usize
    match loop_return with
    | none => let i2 ← i + 1#usize
              ok (cont (s1, i2))
    | some r => ok (done r)
  else ok (done (core.result.Result.Ok s))

/-- [loops_nested_exits::sum_checked]: loop 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 21:4-30:1
    Visibility: public -/
@[rust_loop]
def sum_checked_loop0
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  loop
    (fun (s1, i1) => sum_checked_loop0.body xss s1 i1)
    (s, i)

/-- [loops_nested_exits::sum_checked]:
    Source: 'tests/src/loops-nested-exits.rs', lines 18:0-30:1
    Visibility: public -/
@[reducible]
def sum_checked
  (xss : Slice (alloc.vec.Vec Std.U32)) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  sum_checked_loop0 xss 0#u32 0#usize

/-- [loops_nested_exits::find3]: loop body 2:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-50:1
    Visibility: public -/
@[rust_loop_body]
def find3_loop0_loop0_loop0.body
  (n : Std.U32) (i : Std.U32) (j : Std.U32) (k : Std.U32) :
  Result (ControlFlow Std.U32 (Option Std.U32))
  := do
  if k < n
  then
    let i1 ← i + j
    let i2 ← i1 + k
    if i2 = 4#u32
    then
      if i < j
      then
        if j < k
        then
          let i3 ← 100#u32 * i
          let i4 ← 10#u32 * j
          let i5 ← i3 + i4
          let i6 ← i5 + k
          ok (done (some i6))
        else let k1 ← k + 1#u32
             ok (cont k1)
      else let k1 ← k + 1#u32
           ok (cont k1)
    else let k1 ← k + 1#u32
         ok (cont k1)
  else ok (done none)

/-- [loops_nested_exits::find3]: loop 2:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-50:1
    Visibility: public -/
@[rust_loop]
def find3_loop0_loop0_loop0
  (n : Std.U32) (i : Std.U32) (j : Std.U32) (k : Std.U32) :
  Result (Option Std.U32)
  := do
  loop
    (fun k1 => find3_loop0_loop0_loop0.body n i j k1)
    k

/-- [loops_nested_exits::find3]: loop body 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-50:1
    Visibility: public -/
@[rust_loop_body]
def find3_loop0_loop0.body
  (n : Std.U32) (i : Std.U32) (j : Std.U32) :
  Result (ControlFlow Std.U32 (Option Std.U32))
  := do
  if j < n
  then
    let loop_return ← find3_loop0_loop0_loop0 n i j 0#u32
    match loop_return with
    | none => let j1 ← j + 1#u32
              ok (cont j1)
    | some _ => ok (done loop_return)
  else ok (done none)

/-- [loops_nested_exits::find3]: loop 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-50:1
    Visibility: public -/
@[rust_loop]
def find3_loop0_loop0
  (n : Std.U32) (i : Std.U32) (j : Std.U32) : Result (Option Std.U32) := do
  loop
    (fun j1 => find3_loop0_loop0.body n i j1)
    j

/-- [loops_nested_exits::find3]: loop body 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-50:1
    Visibility: public -/
@[rust_loop_body]
def find3_loop0.body
  (n : Std.U32) (i : Std.U32) : Result (ControlFlow Std.U32 Std.U32) := do
  if i < n
  then
    let loop_return ← find3_loop0_loop0 n i 0#u32
    match loop_return with
    | none => let i1 ← i + 1#u32
              ok (cont i1)
    | some i1 => ok (done i1)
  else ok (done 0#u32)

/-- [loops_nested_exits::find3]: loop 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-50:1
    Visibility: public -/
@[rust_loop]
def find3_loop0 (n : Std.U32) (i : Std.U32) : Result Std.U32 := do
  loop
    (fun i1 => find3_loop0.body n i1)
    i

/-- [loops_nested_exits::find3]:
    Source: 'tests/src/loops-nested-exits.rs', lines 33:0-50:1
    Visibility: public -/
@[reducible] def find3 (n : Std.U32) : Result Std.U32 := do
               find3_loop0 n 0#u32

/-- [loops_nested_exits::prefix_sums]: loop body 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-68:5
    Visibility: public -/
@[rust_loop_body]
def prefix_sums_loop0_loop0.body
  (row : alloc.vec.Vec Std.U32) (s : Std.U32) (j : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (Std.U32 × Bool))
  := do
  let i := alloc.vec.Vec.len row
  if j < i
  then
    let i1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) row j
    if i1 = 0#u32
    then ok (done (s, true))
    else
      let s1 ← lift (core.num.U32.wrapping_add s i1)
      let j1 ← j + 1#usize
      ok (cont (s1, j1))
  else ok (done (s, false))

/-- [loops_nested_exits::prefix_sums]: loop 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-68:5
    Visibility: public -/
@[rust_loop]
def prefix_sums_loop0_loop0
  (s : Std.U32) (row : alloc.vec.Vec Std.U32) (j : Std.Usize) :
  Result (Std.U32 × Bool)
  := do
  loop
    (fun (s1, j1) => prefix_sums_loop0_loop0.body row s1 j1)
    (s, j)

/-- [loops_nested_exits::prefix_sums]: loop body 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-68:5
    Visibility: public -/
@[rust_loop_body]
def prefix_sums_loop0.body
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  let i1 := Slice.len xss
  if i < i1
  then
    let row ← Slice.index_usize xss i
    let i2 ← i + 1#usize
    let (s1, loop_exit) ← prefix_sums_loop0_loop0 s row 0#usize
    if loop_exit
    then ok (cont (s1, i2))
    else
      let s2 ← lift (core.num.U32.wrapping_add s1 1000#u32)
      ok (cont (s2, i2))
  else ok (done s)

/-- [loops_nested_exits::prefix_sums]: loop 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-68:5
    Visibility: public -/
@[rust_loop]
def prefix_sums_loop0
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (s1, i1) => prefix_sums_loop0.body xss s1 i1)
    (s, i)

/-- [loops_nested_exits::prefix_sums]:
    Source: 'tests/src/loops-nested-exits.rs', lines 53:0-70:1
    Visibility: public -/
@[reducible]
def prefix_sums (xss : Slice (alloc.vec.Vec Std.U32)) : Result Std.U32 := do
  prefix_sums_loop0 xss 0#u32 0#usize

/-- [loops_nested_exits::until_zero]: loop body 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-86:5
    Visibility: public -/
@[rust_loop_body]
def until_zero_loop0_loop0.body
  (xss : Slice (alloc.vec.Vec Std.U32)) (i : Std.Usize) (s : Std.U32)
  (j : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) (Std.U32 × Bool))
  := do
  let v ← Slice.index_usize xss i
  let i1 := alloc.vec.Vec.len v
  if j < i1
  then
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v j
    if i2 = 0#u32
    then ok (done (s, true))
    else
      let i3 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v j
      let s1 ← lift (core.num.U32.wrapping_add s i3)
      let j1 ← j + 1#usize
      ok (cont (s1, j1))
  else ok (done (s, false))

/-- [loops_nested_exits::until_zero]: loop 1:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-86:5
    Visibility: public -/
@[rust_loop]
def until_zero_loop0_loop0
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize)
  (j : Std.Usize) :
  Result (Std.U32 × Bool)
  := do
  loop
    (fun (s1, j1) => until_zero_loop0_loop0.body xss i s1 j1)
    (s, j)

/-- [loops_nested_exits::until_zero]: loop body 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-86:5
    Visibility: public -/
@[rust_loop_body]
def until_zero_loop0.body
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  let i1 := Slice.len xss
  if i < i1
  then
    let (s1, loop_exit) ← until_zero_loop0_loop0 xss s i 0#usize
    if loop_exit
    then ok (done s1)
    else let i2 ← i + 1#usize
         ok (cont (s1, i2))
  else ok (done s)

/-- [loops_nested_exits::until_zero]: loop 0:
    Source: 'tests/src/loops-nested-exits.rs', lines 1:0-86:5
    Visibility: public -/
@[rust_loop]
def until_zero_loop0
  (xss : Slice (alloc.vec.Vec Std.U32)) (s : Std.U32) (i : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (s1, i1) => until_zero_loop0.body xss s1 i1)
    (s, i)

/-- [loops_nested_exits::until_zero]:
    Source: 'tests/src/loops-nested-exits.rs', lines 73:0-88:1
    Visibility: public -/
@[reducible]
def until_zero (xss : Slice (alloc.vec.Vec Std.U32)) : Result Std.U32 := do
  until_zero_loop0 xss 0#u32 0#usize

end loops_nested_exits
