-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loop_push_shared_refs_from_map]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace loop_push_shared_refs_from_map

/-- Trait implementation: [core::clone::impls::{impl core::clone::Clone for &'_0 T}]
    Source: '/rustc/library/core/src/clone.rs', lines 780:4-780:44
    Name pattern: [core::clone::Clone<&'0 @T>] -/
@[reducible, rust_trait_impl "core::clone::Clone<&'0 @T>"]
def Shared0T.Insts.CoreCloneClone (T : Type) : core.clone.Clone T := {
  clone := core.clone.impls.CloneShared.clone
}

/-- [loop_push_shared_refs_from_map::C]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 7:0-9:1
    Visibility: public -/
structure C where
  x : Std.U64

/-- [loop_push_shared_refs_from_map::group::{closure#1}::{closure}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:34-17:41 -/
@[reducible]
def group.closure_1.closure := Unit

/-- [loop_push_shared_refs_from_map::group::{closure#1}::{impl core::ops::function::FnMut<(&'_0 &'_1 loop_push_shared_refs_from_map::C,), u64> for loop_push_shared_refs_from_map::group::{closure#1}::{closure}}::call_mut]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:34-17:41 -/
def
  group.closure_1.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1CU64.call_mut
  (c : group.closure_1.closure) (tupled_args : C) :
  Result (Std.U64 × group.closure_1.closure)
  := do
  ok (tupled_args.x, c)

/-- [loop_push_shared_refs_from_map::group::{closure#1}::{impl core::ops::function::FnOnce<(&'_0 &'_1 loop_push_shared_refs_from_map::C,), u64> for loop_push_shared_refs_from_map::group::{closure#1}::{closure}}::call_once]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:34-17:41 -/
def
  group.closure_1.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1CU64.call_once
  (c : group.closure_1.closure) (c1 : C) : Result Std.U64 := do
  let (i, _) ←
    group.closure_1.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1CU64.call_mut
      c c1
  ok i

/-- Trait implementation: [loop_push_shared_refs_from_map::group::{closure#1}::{impl core::ops::function::FnOnce<(&'_0 &'_1 loop_push_shared_refs_from_map::C,), u64> for loop_push_shared_refs_from_map::group::{closure#1}::{closure}}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:34-17:41 -/
@[reducible]
def group.closure_1.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1CU64
  : core.ops.function.FnOnce group.closure_1.closure C Std.U64 := {
  call_once :=
    group.closure_1.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1CU64.call_once
}

/-- Trait implementation: [loop_push_shared_refs_from_map::group::{closure#1}::{impl core::ops::function::FnMut<(&'_0 &'_1 loop_push_shared_refs_from_map::C,), u64> for loop_push_shared_refs_from_map::group::{closure#1}::{closure}}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:34-17:41 -/
@[reducible]
def group.closure_1.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1CU64 :
  core.ops.function.FnMut group.closure_1.closure C Std.U64 := {
  FnOnceInst :=
    group.closure_1.closure.Insts.CoreOpsFunctionFnOnceTupleShared0Shared1CU64
  call_mut :=
    group.closure_1.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1CU64.call_mut
}

/-- [loop_push_shared_refs_from_map::group::{closure#1}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:17-17:52 -/
@[reducible]
def group.closure_1 := Unit

/-- [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnMut<(&'_0 alloc::vec::Vec<&'_1 loop_push_shared_refs_from_map::C>,), alloc::vec::Vec<u64>> for loop_push_shared_refs_from_map::group::{closure#1}}::call_mut]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:17-17:52 -/
def
  group.closure_1.Insts.CoreOpsFunctionFnMutTupleShared0VecShared1CVecU64.call_mut
  (c : group.closure_1) (tupled_args : alloc.vec.Vec C) :
  Result ((alloc.vec.Vec Std.U64) × group.closure_1)
  := do
  let s := alloc.vec.Vec.deref tupled_args
  let i ← core.slice.Slice.iter s
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter C)
      group.closure_1.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1CU64
      i ()
  let v ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorSliceIter C)
      group.closure_1.closure.Insts.CoreOpsFunctionFnMutTupleShared0Shared1CU64)
      (core.iter.traits.collect.FromIteratorVec Std.U64) m
  ok (v, c)

/-- [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnOnce<(&'_0 alloc::vec::Vec<&'_1 loop_push_shared_refs_from_map::C>,), alloc::vec::Vec<u64>> for loop_push_shared_refs_from_map::group::{closure#1}}::call_once]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:17-17:52 -/
def
  group.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0VecShared1CVecU64.call_once
  (c : group.closure_1) (v : alloc.vec.Vec C) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let (v1, _) ←
    group.closure_1.Insts.CoreOpsFunctionFnMutTupleShared0VecShared1CVecU64.call_mut
      c v
  ok v1

/-- Trait implementation: [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnOnce<(&'_0 alloc::vec::Vec<&'_1 loop_push_shared_refs_from_map::C>,), alloc::vec::Vec<u64>> for loop_push_shared_refs_from_map::group::{closure#1}}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:17-17:52 -/
@[reducible]
def group.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0VecShared1CVecU64 :
  core.ops.function.FnOnce group.closure_1 (alloc.vec.Vec C) (alloc.vec.Vec
  Std.U64) := {
  call_once :=
    group.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0VecShared1CVecU64.call_once
}

/-- Trait implementation: [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnMut<(&'_0 alloc::vec::Vec<&'_1 loop_push_shared_refs_from_map::C>,), alloc::vec::Vec<u64>> for loop_push_shared_refs_from_map::group::{closure#1}}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 17:17-17:52 -/
@[reducible]
def group.closure_1.Insts.CoreOpsFunctionFnMutTupleShared0VecShared1CVecU64 :
  core.ops.function.FnMut group.closure_1 (alloc.vec.Vec C) (alloc.vec.Vec
  Std.U64) := {
  FnOnceInst :=
    group.closure_1.Insts.CoreOpsFunctionFnOnceTupleShared0VecShared1CVecU64
  call_mut :=
    group.closure_1.Insts.CoreOpsFunctionFnMutTupleShared0VecShared1CVecU64.call_mut
}

/-- [loop_push_shared_refs_from_map::group::{closure}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 12:57-12:79 -/
@[reducible]
def group.closure := Unit

/-- [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnMut<((usize, &'_0 loop_push_shared_refs_from_map::C),), (u32, &'_ loop_push_shared_refs_from_map::C)> for loop_push_shared_refs_from_map::group::{closure}}::call_mut]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 12:57-12:79 -/
def
  group.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared0CPairU32SharedC.call_mut
  (c : group.closure) (tupled_args : (Std.Usize × C)) :
  Result ((Std.U32 × C) × group.closure)
  := do
  let (i, c1) := tupled_args
  let i1 ← lift (UScalar.cast .U32 i)
  ok ((i1, c1), c)

/-- [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnOnce<((usize, &'_0 loop_push_shared_refs_from_map::C),), (u32, &'_ loop_push_shared_refs_from_map::C)> for loop_push_shared_refs_from_map::group::{closure}}::call_once]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 12:57-12:79 -/
def
  group.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared0CPairU32SharedC.call_once
  (c : group.closure) (p : (Std.Usize × C)) : Result (Std.U32 × C) := do
  let ((i, c1), _) ←
    group.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared0CPairU32SharedC.call_mut
      c p
  ok (i, c1)

/-- Trait implementation: [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnOnce<((usize, &'_0 loop_push_shared_refs_from_map::C),), (u32, &'_ loop_push_shared_refs_from_map::C)> for loop_push_shared_refs_from_map::group::{closure}}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 12:57-12:79 -/
@[reducible]
def
  group.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared0CPairU32SharedC
  : core.ops.function.FnOnce group.closure (Std.Usize × C) (Std.U32 × C) := {
  call_once :=
    group.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared0CPairU32SharedC.call_once
}

/-- Trait implementation: [loop_push_shared_refs_from_map::group::{impl core::ops::function::FnMut<((usize, &'_0 loop_push_shared_refs_from_map::C),), (u32, &'_ loop_push_shared_refs_from_map::C)> for loop_push_shared_refs_from_map::group::{closure}}]
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 12:57-12:79 -/
@[reducible]
def
  group.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared0CPairU32SharedC
  : core.ops.function.FnMut group.closure (Std.Usize × C) (Std.U32 × C) := {
  FnOnceInst :=
    group.closure.Insts.CoreOpsFunctionFnOnceTuplePairUsizeShared0CPairU32SharedC
  call_mut :=
    group.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared0CPairU32SharedC.call_mut
}

/-- [loop_push_shared_refs_from_map::group]: loop body 0:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 14:4-16:5
    Visibility: public -/
@[rust_loop_body]
def group_loop.body
  (m : alloc.collections.btree.map.BTreeMap Std.U32 C Global)
  (iter : alloc.vec.into_iter.IntoIter (Std.U32 × Std.Usize))
  (q : alloc.vec.Vec (alloc.vec.Vec C)) :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter (Std.U32 × Std.Usize)) ×
    (alloc.vec.Vec (alloc.vec.Vec C))) (alloc.vec.Vec (alloc.vec.Vec C)))
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done q)
  | some p =>
    let (k, i) := p
    let (v, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
        (alloc.vec.Vec C)) q i
    let c ←
      alloc.collections.btree.map.BTreeMap.Insts.CoreOpsIndexIndexShared0QV.index
        alloc.alloc.Global.Insts.CoreAllocAllocatorClone
        (core.borrow.Borrow.Blanket Std.U32) core.cmp.OrdU32 core.cmp.OrdU32 m
        k
    let v1 ← alloc.vec.Vec.push v c
    let q1 := index_mut_back v1
    ok (cont (iter1, q1))

/-- [loop_push_shared_refs_from_map::group]: loop 0:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 14:4-16:5
    Visibility: public -/
@[rust_loop]
def group_loop
  (iter : alloc.vec.into_iter.IntoIter (Std.U32 × Std.Usize))
  (m : alloc.collections.btree.map.BTreeMap Std.U32 C Global)
  (q : alloc.vec.Vec (alloc.vec.Vec C)) :
  Result (alloc.vec.Vec (alloc.vec.Vec C))
  := do
  loop
    (fun (iter1, q1) => group_loop.body m iter1 q1)
    (iter, q)

/-- [loop_push_shared_refs_from_map::group]:
    Source: 'tests/src/loop-push-shared-refs-from-map.rs', lines 11:0-18:1
    Visibility: public -/
def group
  (cs : Slice C) (keys : alloc.vec.Vec (Std.U32 × Std.Usize)) (n : Std.Usize)
  :
  Result (alloc.vec.Vec (alloc.vec.Vec Std.U64))
  := do
  let i ← core.slice.Slice.iter cs
  let e ←
    core.iter.traits.iterator.Iterator.enumerate.trait_default
      (core.iter.traits.iterator.IteratorSliceIter C) i
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter C))
      group.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared0CPairU32SharedC
      e ()
  let m1 ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter C))
      group.closure.Insts.CoreOpsFunctionFnMutTuplePairUsizeShared0CPairU32SharedC)
      (alloc.collections.btree.map.BTreeMapKVGlobal.Insts.CoreIterTraitsCollectFromIteratorPair
      C core.cmp.OrdU32) m
  let q ←
    alloc.vec.from_elem (core.clone.CloneallocvecVec
      (Shared0T.Insts.CoreCloneClone C)) (alloc.vec.Vec.new C) n
  let iter ← alloc.vec.IntoIteratorVec.into_iter keys
  let q1 ← group_loop iter m1 q
  let s := alloc.vec.Vec.deref q1
  let i1 ← core.slice.Slice.iter s
  let m2 ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec C))
      group.closure_1.Insts.CoreOpsFunctionFnMutTupleShared0VecShared1CVecU64
      i1 ()
  core.iter.traits.iterator.Iterator.collect.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec C))
    group.closure_1.Insts.CoreOpsFunctionFnMutTupleShared0VecShared1CVecU64)
    (core.iter.traits.collect.FromIteratorVec (alloc.vec.Vec Std.U64)) m2

end loop_push_shared_refs_from_map
