-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [map_fn_item_max]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace map_fn_item_max

/-- [alloc::vec::{alloc::vec::Vec<T>}::{impl core::ops::function::FnMut<(&'_0 alloc::vec::Vec<T>,), usize> for alloc::vec::{alloc::vec::Vec<T>}::len<'static, T, A>}::call_mut]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3135:4-3135:36
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::{core::ops::function::FnMut<@, (&'0 alloc::vec::Vec<@T>), usize>}::call_mut]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{alloc::vec::Vec<@T>}::{core::ops::function::FnMut<@, (&'0 alloc::vec::Vec<@T>), usize>}::call_mut"]
axiom alloc.vec.Vec.len.Insts.CoreOpsFunctionFnMutTupleShared0VecUsize.call_mut
  {T : Type} (A : Type) :
  (alloc.vec.Vec T → Std.Usize) → alloc.vec.Vec T → Result (Std.Usize ×
    (alloc.vec.Vec T → Std.Usize))

/-- [alloc::vec::{alloc::vec::Vec<T>}::{impl core::ops::function::FnOnce<(&'_0 alloc::vec::Vec<T>,), usize> for alloc::vec::{alloc::vec::Vec<T>}::len<'static, T, A>}::call_once]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3135:4-3135:36
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::{core::ops::function::FnOnce<@, (&'0 alloc::vec::Vec<@T>), usize>}::call_once]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{alloc::vec::Vec<@T>}::{core::ops::function::FnOnce<@, (&'0 alloc::vec::Vec<@T>), usize>}::call_once"]
axiom
  alloc.vec.Vec.len.Insts.CoreOpsFunctionFnOnceTupleShared0VecUsize.call_once
  {T : Type} (A : Type) :
  (alloc.vec.Vec T → Std.Usize) → alloc.vec.Vec T → Result Std.Usize

/-- Trait implementation: [alloc::vec::{alloc::vec::Vec<T>}::{impl core::ops::function::FnOnce<(&'_0 alloc::vec::Vec<T>,), usize> for alloc::vec::{alloc::vec::Vec<T>}::len<'static, T, A>}]
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3135:4-3135:36
    Name pattern: [core::ops::function::FnOnce<@, (&'0 alloc::vec::Vec<@T>), usize>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnOnce<@, (&'0 alloc::vec::Vec<@T>), usize>"]
def alloc.vec.Vec.len.Insts.CoreOpsFunctionFnOnceTupleShared0VecUsize (T :
  Type) (A : Type) : core.ops.function.FnOnce (alloc.vec.Vec T → Std.Usize)
  (alloc.vec.Vec T) Std.Usize := {
  call_once :=
    alloc.vec.Vec.len.Insts.CoreOpsFunctionFnOnceTupleShared0VecUsize.call_once
    A
}

/-- Trait implementation: [alloc::vec::{alloc::vec::Vec<T>}::{impl core::ops::function::FnMut<(&'_0 alloc::vec::Vec<T>,), usize> for alloc::vec::{alloc::vec::Vec<T>}::len<'static, T, A>}]
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3135:4-3135:36
    Name pattern: [core::ops::function::FnMut<@, (&'0 alloc::vec::Vec<@T>), usize>] -/
@[reducible, rust_trait_impl
  "core::ops::function::FnMut<@, (&'0 alloc::vec::Vec<@T>), usize>"]
def alloc.vec.Vec.len.Insts.CoreOpsFunctionFnMutTupleShared0VecUsize (T : Type)
  (A : Type) : core.ops.function.FnMut (alloc.vec.Vec T → Std.Usize)
  (alloc.vec.Vec T) Std.Usize := {
  FnOnceInst :=
    alloc.vec.Vec.len.Insts.CoreOpsFunctionFnOnceTupleShared0VecUsize T A
  call_mut :=
    alloc.vec.Vec.len.Insts.CoreOpsFunctionFnMutTupleShared0VecUsize.call_mut A
}

/-- [map_fn_item_max::longest]:
    Source: 'tests/src/map-fn-item-max.rs', lines 5:0-7:1
    Visibility: public -/
def longest
  (v : alloc.vec.Vec (alloc.vec.Vec Std.U32)) : Result Std.Usize := do
  let s := alloc.vec.Vec.deref v
  let i ← core.slice.Slice.iter s
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec Std.U32))
      (alloc.vec.Vec.len.Insts.CoreOpsFunctionFnMutTupleShared0VecUsize Std.U32
      Global) i (alloc.vec.Vec.len)
  let o ←
    core.iter.traits.iterator.Iterator.max.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorSliceIter (alloc.vec.Vec Std.U32))
      (alloc.vec.Vec.len.Insts.CoreOpsFunctionFnMutTupleShared0VecUsize Std.U32
      Global)) core.cmp.OrdUsize m
  ok (core.option.Option.unwrap_or o 0#usize)

end map_fn_item_max
