-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nested_shared_iter]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nested_shared_iter

/-- [nested_shared_iter::total_len]: loop body 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 10:4-12:5
    Visibility: public -/
@[rust_loop_body]
def total_len_loop.body
  (iter : core.slice.iter.Iter (Slice Std.U32)) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter (Slice Std.U32)) × Std.U32)
    Std.U32)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done s)
  | some xs =>
    let i := Slice.len xs
    let i1 ← lift (UScalar.cast .U32 i)
    let s1 ← lift (core.num.U32.wrapping_add s i1)
    ok (cont (iter1, s1))

/-- [nested_shared_iter::total_len]: loop 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 10:4-12:5
    Visibility: public -/
@[rust_loop]
def total_len_loop
  (iter : core.slice.iter.Iter (Slice Std.U32)) (s : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, s1) => total_len_loop.body iter1 s1)
    (iter, s)

/-- [nested_shared_iter::total_len]:
    Source: 'tests/src/nested-shared-iter.rs', lines 8:0-14:1
    Visibility: public -/
def total_len (xss : Slice (Slice Std.U32)) : Result Std.U32 := do
  let iter ← core.slice.Slice.iter xss
  total_len_loop iter 0#u32

/-- [nested_shared_iter::total]: loop body 1:
    Source: 'tests/src/nested-shared-iter.rs', lines 20:8-22:9
    Visibility: public -/
@[rust_loop_body]
def total_loop0_loop0.body
  (iter : core.slice.iter.Iter Std.U32) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U32) × Std.U32) Std.U32)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done s)
  | some x =>
    let s1 ← lift (core.num.U32.wrapping_add s x)
    ok (cont (iter1, s1))

/-- [nested_shared_iter::total]: loop 1:
    Source: 'tests/src/nested-shared-iter.rs', lines 20:8-22:9
    Visibility: public -/
@[rust_loop]
def total_loop0_loop0
  (iter : core.slice.iter.Iter Std.U32) (s : Std.U32) : Result Std.U32 := do
  loop
    (fun (iter1, s1) => total_loop0_loop0.body iter1 s1)
    (iter, s)

/-- [nested_shared_iter::total]: loop body 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 19:4-23:5
    Visibility: public -/
@[rust_loop_body]
def total_loop0.body
  (iter : core.slice.iter.Iter (Slice Std.U32)) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter (Slice Std.U32)) × Std.U32)
    Std.U32)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done s)
  | some xs =>
    let iter2 ←
      SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
        xs
    let s1 ← total_loop0_loop0 iter2 s
    ok (cont (iter1, s1))

/-- [nested_shared_iter::total]: loop 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 19:4-23:5
    Visibility: public -/
@[rust_loop]
def total_loop0
  (iter : core.slice.iter.Iter (Slice Std.U32)) (s : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, s1) => total_loop0.body iter1 s1)
    (iter, s)

/-- [nested_shared_iter::total]:
    Source: 'tests/src/nested-shared-iter.rs', lines 17:0-25:1
    Visibility: public -/
def total (xss : Slice (Slice Std.U32)) : Result Std.U32 := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter xss
  total_loop0 iter 0#u32

/-- [nested_shared_iter::check]:
    Source: 'tests/src/nested-shared-iter.rs', lines 27:0-33:1 -/
def check (x : Std.U32) : Result (core.result.Result Std.U32 Std.U32) := do
  if x = 0#u32
  then ok (core.result.Result.Err 7#u32)
  else ok (core.result.Result.Ok x)

/-- [nested_shared_iter::absorb]: loop body 1:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-42:9
    Visibility: public -/
@[rust_loop_body]
def absorb_loop0_loop0.body
  (iter : core.slice.iter.Iter Std.U32) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U32) × Std.U32) (Std.U32 ×
    (Option (core.result.Result Std.U32 Std.U32))))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (s, none))
  | some x =>
    let r ← check x
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let s1 ← lift (core.num.U32.wrapping_add s val)
      ok (cont (iter1, s1))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Std.U32 (core.convert.FromSame Std.U32) residual
      ok (done (s, some r1))

/-- [nested_shared_iter::absorb]: loop 1:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-42:9
    Visibility: public -/
@[rust_loop]
def absorb_loop0_loop0
  (iter : core.slice.iter.Iter Std.U32) (s : Std.U32) :
  Result (Std.U32 × (Option (core.result.Result Std.U32 Std.U32)))
  := do
  loop
    (fun (iter1, s1) => absorb_loop0_loop0.body iter1 s1)
    (iter, s)

/-- [nested_shared_iter::absorb]: loop body 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-45:1
    Visibility: public -/
@[rust_loop_body]
def absorb_loop0.body
  (iter : core.slice.iter.Iter (Slice Std.U32)) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter (Slice Std.U32)) × Std.U32)
    (core.result.Result Std.U32 Std.U32))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (core.result.Result.Ok s))
  | some xs =>
    let i := Slice.len xs
    let i1 ← lift (UScalar.cast .U32 i)
    let r ← check i1
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let s1 ← lift (core.num.U32.wrapping_add s val)
      let iter2 ← core.slice.Slice.iter xs
      let (s2, loop_return) ← absorb_loop0_loop0 iter2 s1
      match loop_return with
      | none => ok (cont (iter1, s2))
      | some r1 => ok (done r1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Std.U32 (core.convert.FromSame Std.U32) residual
      ok (done r1)

/-- [nested_shared_iter::absorb]: loop 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-45:1
    Visibility: public -/
@[rust_loop]
def absorb_loop0
  (iter : core.slice.iter.Iter (Slice Std.U32)) (s : Std.U32) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  loop
    (fun (iter1, s1) => absorb_loop0.body iter1 s1)
    (iter, s)

/-- [nested_shared_iter::absorb]:
    Source: 'tests/src/nested-shared-iter.rs', lines 36:0-45:1
    Visibility: public -/
def absorb
  (xss : Slice (Slice Std.U32)) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  let iter ← core.slice.Slice.iter xss
  absorb_loop0 iter 0#u32

/-- Trait declaration: [nested_shared_iter::Hashable]
    Source: 'tests/src/nested-shared-iter.rs', lines 48:0-50:1
    Visibility: public -/
structure Hashable (Self : Type) where
  bytes : Self → Result Std.U32

/-- Trait declaration: [nested_shared_iter::Field]
    Source: 'tests/src/nested-shared-iter.rs', lines 53:0-55:1
    Visibility: public -/
structure Field (Self : Type) where
  HashableInst : Hashable Self
  coremarkerCopyInst : core.marker.Copy Self
  from_u128 : Std.U128 → Result Self

/-- Trait declaration: [nested_shared_iter::Transcript]
    Source: 'tests/src/nested-shared-iter.rs', lines 58:0-60:1
    Visibility: public -/
structure Transcript (Self : Type) where
  common : forall {V : Type} (HashableInst : Hashable V), Self → V → Result
    ((core.result.Result Unit Std.U32) × Self)

/-- [nested_shared_iter::Trace]
    Source: 'tests/src/nested-shared-iter.rs', lines 63:0-65:1
    Visibility: public -/
structure Trace where
  v : alloc.vec.Vec Std.U32

/-- [nested_shared_iter::parse]: loop body 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-92:1
    Visibility: public -/
@[rust_loop_body]
def parse_loop0.body
  {C : Type} {T : Type} (HashableInst : Hashable C) (TranscriptInst :
  Transcript T) (iter : core.slice.iter.Iter C) (t : T) :
  Result (ControlFlow ((core.slice.iter.Iter C) × T) (T × (Option
    (core.result.Result Trace Std.U32))))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (t, none))
  | some c =>
    let (r, t1) ← TranscriptInst.common HashableInst t c
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ => ok (cont (iter1, t1))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Trace (core.convert.FromSame Std.U32) residual
      ok (done (t1, some r1))

/-- [nested_shared_iter::parse]: loop 0:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-92:1
    Visibility: public -/
@[rust_loop]
def parse_loop0
  {C : Type} {T : Type} (HashableInst : Hashable C) (TranscriptInst :
  Transcript T) (iter : core.slice.iter.Iter C) (t : T) :
  Result (T × (Option (core.result.Result Trace Std.U32)))
  := do
  loop
    (fun (iter1, t1) => parse_loop0.body HashableInst TranscriptInst iter1 t1)
    (iter, t)

/-- [nested_shared_iter::parse]: loop body 2:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-82:9
    Visibility: public -/
@[rust_loop_body]
def parse_loop1_loop0.body
  {F : Type} {T : Type} (FieldInst : Field F) (TranscriptInst : Transcript T)
  (loop_return : Option (core.result.Result Trace Std.U32))
  (iter : core.slice.iter.Iter F) (t : T) :
  Result (ControlFlow ((core.slice.iter.Iter F) × T) (T × (Option
    (core.result.Result Trace Std.U32)) × Bool))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (t, loop_return, false))
  | some value =>
    let (r, t1) ← TranscriptInst.common FieldInst.HashableInst t value
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ => ok (cont (iter1, t1))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Trace (core.convert.FromSame Std.U32) residual
      ok (done (t1, some r1, true))

/-- [nested_shared_iter::parse]: loop 2:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-82:9
    Visibility: public -/
@[rust_loop]
def parse_loop1_loop0
  {F : Type} {T : Type} (FieldInst : Field F) (TranscriptInst : Transcript T)
  (iter : core.slice.iter.Iter F) (t : T)
  (loop_return : Option (core.result.Result Trace Std.U32)) :
  Result (T × (Option (core.result.Result Trace Std.U32)) × Bool)
  := do
  loop
    (fun (iter1, t1) => parse_loop1_loop0.body FieldInst TranscriptInst
      loop_return iter1 t1)
    (iter, t)

/-- [nested_shared_iter::parse]: loop body 1:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-92:1
    Visibility: public -/
@[rust_loop_body]
def parse_loop1.body
  {F : Type} {T : Type} (FieldInst : Field F) (TranscriptInst : Transcript T)
  (iter : core.slice.iter.Iter (Slice F)) (t : T)
  (loop_return : Option (core.result.Result Trace Std.U32)) :
  Result (ControlFlow ((core.slice.iter.Iter (Slice F)) × T × (Option
    (core.result.Result Trace Std.U32))) (T × (Option (core.result.Result
    Trace Std.U32))))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (t, loop_return))
  | some «instance» =>
    let i := Slice.len «instance»
    let i1 ← lift (UScalar.cast .U128 i)
    let t1 ← FieldInst.from_u128 i1
    let (r, t2) ← TranscriptInst.common FieldInst.HashableInst t t1
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      let iter2 ← core.slice.Slice.iter «instance»
      let (t3, loop_return1, loop_exit) ←
        parse_loop1_loop0 FieldInst TranscriptInst iter2 t2 loop_return
      if loop_exit
      then ok (done (t3, loop_return1))
      else ok (cont (iter1, t3, loop_return1))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Trace (core.convert.FromSame Std.U32) residual
      ok (done (t2, some r1))

/-- [nested_shared_iter::parse]: loop 1:
    Source: 'tests/src/nested-shared-iter.rs', lines 1:0-92:1
    Visibility: public -/
@[rust_loop]
def parse_loop1
  {F : Type} {T : Type} (FieldInst : Field F) (TranscriptInst : Transcript T)
  (iter : core.slice.iter.Iter (Slice F)) (t : T)
  (loop_return : Option (core.result.Result Trace Std.U32)) :
  Result (T × (Option (core.result.Result Trace Std.U32)))
  := do
  loop
    (fun (iter1, t1, loop_return1) => parse_loop1.body FieldInst TranscriptInst
      iter1 t1 loop_return1)
    (iter, t, loop_return)

/-- [nested_shared_iter::parse]: loop body 3:
    Source: 'tests/src/nested-shared-iter.rs', lines 88:4-90:5
    Visibility: public -/
@[rust_loop_body]
def parse_loop2.body
  (iter : core.ops.range.Range Std.Usize) (labels : alloc.vec.Vec Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec
    Std.U32)) (alloc.vec.Vec Std.U32))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done labels)
  | some i =>
    let i1 ← lift (UScalar.cast .U32 i)
    let labels1 ← alloc.vec.Vec.push labels i1
    ok (cont (iter1, labels1))

/-- [nested_shared_iter::parse]: loop 3:
    Source: 'tests/src/nested-shared-iter.rs', lines 88:4-90:5
    Visibility: public -/
@[rust_loop]
def parse_loop2
  (iter : core.ops.range.Range Std.Usize) (labels : alloc.vec.Vec Std.U32) :
  Result (alloc.vec.Vec Std.U32)
  := do
  loop
    (fun (iter1, labels1) => parse_loop2.body iter1 labels1)
    (iter, labels)

/-- [nested_shared_iter::parse]:
    Source: 'tests/src/nested-shared-iter.rs', lines 69:0-92:1
    Visibility: public -/
def parse
  {F : Type} {C : Type} {T : Type} (FieldInst : Field F) (HashableInst :
  Hashable C) (TranscriptInst : Transcript T) (committed : Slice C)
  (instances : Slice (Slice F)) (t : T) :
  Result ((core.result.Result Trace Std.U32) × T)
  := do
  let y ←
    lift (Std.Array.to_slice (Array.make 1#usize [ 1#u32 ] : Array Std.U32
      1#usize))
  let ret := alloc.slice.Slice.into_vec y
  let iter ← core.slice.Slice.iter committed
  let (t1, loop_return) ← parse_loop0 HashableInst TranscriptInst iter t
  match loop_return with
  | none =>
    let iter1 ← core.slice.Slice.iter instances
    let (t2, loop_return1) ←
      parse_loop1 FieldInst TranscriptInst iter1 t1 none
    match loop_return1 with
    | none =>
      let i := Slice.len instances
      let labels ← parse_loop2 { start := 0#usize, «end» := i } ret
      ok (core.result.Result.Ok { v := labels }, t2)
    | some r => ok (r, t2)
  | some r => ok (r, t1)

end nested_shared_iter
