-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [newtype_getter_same_name]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace newtype_getter_same_name

/-- [newtype_getter_same_name::Key]
    Source: 'tests/src/newtype-getter-same-name.rs', lines 6:0-8:1
    Visibility: public -/
structure Key where
  commitment : Std.U32

/-- [newtype_getter_same_name::Absorbed]
    Source: 'tests/src/newtype-getter-same-name.rs', lines 10:0-10:33
    Visibility: public -/
@[reducible]
def Absorbed := Key

/-- [newtype_getter_same_name::{newtype_getter_same_name::Absorbed<'a>}::commitment]:
    Source: 'tests/src/newtype-getter-same-name.rs', lines 13:4-15:5
    Visibility: public -/
def Absorbed.commitment (self : Absorbed) : Result Std.U32 := do
  ok (Key.commitment self)

end newtype_getter_same_name
