-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [recursive_impl_generic_method]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace recursive_impl_generic_method

/-- Trait declaration: [recursive_impl_generic_method::Visit]
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 7:0-9:1
    Visibility: public -/
structure Visit (Self : Type) where
  visit : forall {V : Type} (coreopsfunctionFnPTupleU32U32Inst :
    core.ops.function.Fn V Std.U32 Std.U32), Self → V → Result Std.U32

/-- [recursive_impl_generic_method::Tree]
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 11:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive Tree where
| Leaf : Std.U32 → Tree
| Node : alloc.vec.Vec Tree → Tree

/-- [recursive_impl_generic_method::visit_all]: loop body 0:
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 27:4-29:5
    Visibility: public -/
@[rust_loop_body]
def visit_all_loop.body
  {T : Type} {V : Type} (VisitInst : Visit T)
  (coreopsfunctionFnVTupleU32U32Inst : core.ops.function.Fn V Std.U32 Std.U32)
  (v : V) (iter : core.slice.iter.Iter T) (s : Std.U32) :
  Result (ControlFlow ((core.slice.iter.Iter T) × Std.U32) Std.U32)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done s)
  | some t =>
    let i ← VisitInst.visit coreopsfunctionFnVTupleU32U32Inst t v
    let s1 ← lift (core.num.U32.wrapping_add s i)
    ok (cont (iter1, s1))

/-- [recursive_impl_generic_method::visit_all]: loop 0:
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 27:4-29:5
    Visibility: public -/
@[rust_loop]
def visit_all_loop
  {T : Type} {V : Type} (VisitInst : Visit T)
  (coreopsfunctionFnVTupleU32U32Inst : core.ops.function.Fn V Std.U32 Std.U32)
  (iter : core.slice.iter.Iter T) (v : V) (s : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, s1) => visit_all_loop.body VisitInst
      coreopsfunctionFnVTupleU32U32Inst v iter1 s1)
    (iter, s)

/-- [recursive_impl_generic_method::visit_all]:
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 25:0-31:1
    Visibility: public -/
def visit_all
  {T : Type} {V : Type} (VisitInst : Visit T)
  (coreopsfunctionFnVTupleU32U32Inst : core.ops.function.Fn V Std.U32 Std.U32)
  (ts : Slice T) (v : V) :
  Result Std.U32
  := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter ts
  visit_all_loop VisitInst coreopsfunctionFnVTupleU32U32Inst iter v 0#u32

/-- [recursive_impl_generic_method::{impl recursive_impl_generic_method::Visit for recursive_impl_generic_method::Tree}::visit]:
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 17:4-22:5
    Visibility: public -/
def Tree.Insts.Recursive_impl_generic_methodVisit.visit
  {V : Type} (coreopsfunctionFnVTupleU32U32Inst : core.ops.function.Fn V
  Std.U32 Std.U32) (self : Tree) (v : V) :
  Result Std.U32
  := do
  match self with
  | Tree.Leaf x => coreopsfunctionFnVTupleU32U32Inst.call v x
  | Tree.Node ts =>
    let s := alloc.vec.Vec.deref ts
    visit_all
      ({ visit := ( fun {V1 : Type} (coreopsfunctionFnPTupleU32U32Inst :
           core.ops.function.Fn V1 Std.U32 Std.U32) =>
           Tree.Insts.Recursive_impl_generic_methodVisit.visit
           coreopsfunctionFnPTupleU32U32Inst) } : Visit Tree)
      coreopsfunctionFnVTupleU32U32Inst s v
partial_fixpoint monotonicity by aeneas_monotonicity [visit_all, visit_all_loop, visit_all_loop.body]

/-- Trait implementation: [recursive_impl_generic_method::{impl recursive_impl_generic_method::Visit for recursive_impl_generic_method::Tree}]
    Source: 'tests/src/recursive-impl-generic-method.rs', lines 16:0-23:1 -/
@[reducible]
impl_def Tree.Insts.Recursive_impl_generic_methodVisit : Visit Tree := {
  visit := fun {V : Type} (coreopsfunctionFnPTupleU32U32Inst :
    core.ops.function.Fn V Std.U32 Std.U32) =>
    Tree.Insts.Recursive_impl_generic_methodVisit.visit
    coreopsfunctionFnPTupleU32U32Inst
}

end recursive_impl_generic_method
