-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [recursive_derive_clone]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace recursive_derive_clone

/-- [recursive_derive_clone::Label]
    Source: 'tests/src/recursive-derive-clone.rs', lines 11:0-16:1
    Visibility: public -/
@[discriminant isize]
inductive Label where
| Fixed : Std.Usize → Label
| Custom : Std.U32 → Label
| Collection : alloc.vec.Vec Label → Label
| NoLabel : Label

/-- [recursive_derive_clone::{impl core::clone::Clone for recursive_derive_clone::Label}::clone]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:9-10:14
    Visibility: public -/
def Label.Insts.CoreCloneClone.clone (self : Label) : Result Label := do
  match self with
  | Label.Fixed __self_0 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    ok (Label.Fixed i)
  | Label.Custom __self_0 =>
    let i ← lift (core.clone.impls.CloneU32.clone __self_0)
    ok (Label.Custom i)
  | Label.Collection __self_0 =>
    let v ←
      alloc.vec.CloneVec.clone ({ clone := (Label.Insts.CoreCloneClone.clone) }
        : core.clone.Clone Label) __self_0
    ok (Label.Collection v)
  | Label.NoLabel => ok Label.NoLabel
partial_fixpoint monotonicity by aeneas_monotonicity []

/-- Trait implementation: [recursive_derive_clone::{impl core::clone::Clone for recursive_derive_clone::Label}]
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:9-10:14 -/
@[reducible]
impl_def Label.Insts.CoreCloneClone : core.clone.Clone Label := {
  clone := Label.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [recursive_derive_clone::{impl core::marker::StructuralPartialEq for recursive_derive_clone::Label}]
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:16-10:25 -/
@[reducible]
def Label.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Label := {
}

/-- [recursive_derive_clone::{impl core::cmp::PartialEq<recursive_derive_clone::Label> for recursive_derive_clone::Label}::eq]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:16-10:25
    Visibility: public -/
def Label.Insts.CoreCmpPartialEqLabel.eq
  (self : Label) (other : Label) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Label.Fixed __self_0 =>
      match other with
      | Label.Fixed __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
      | Label.Custom _ => ok true
      | Label.Collection _ => ok true
      | Label.NoLabel => ok true
    | Label.Custom __self_0 =>
      match other with
      | Label.Fixed _ => ok true
      | Label.Custom __arg1_0 =>
        lift (core.cmp.impls.PartialEqU32.eq __self_0 __arg1_0)
      | Label.Collection _ => ok true
      | Label.NoLabel => ok true
    | Label.Collection __self_0 =>
      match other with
      | Label.Fixed _ => ok true
      | Label.Custom _ => ok true
      | Label.Collection __arg1_0 =>
        alloc.vec.partial_eq.PartialEqVec.eq
          ({ eq := (Label.Insts.CoreCmpPartialEqLabel.eq) } :
          core.cmp.PartialEq Label Label) __self_0 __arg1_0
      | Label.NoLabel => ok true
    | Label.NoLabel => ok true
  else ok false
partial_fixpoint monotonicity by aeneas_monotonicity []

/-- Trait implementation: [recursive_derive_clone::{impl core::cmp::PartialEq<recursive_derive_clone::Label> for recursive_derive_clone::Label}]
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:16-10:25 -/
@[reducible]
impl_def Label.Insts.CoreCmpPartialEqLabel : core.cmp.PartialEq Label Label
  := {
  eq := Label.Insts.CoreCmpPartialEqLabel.eq
}

/-- [recursive_derive_clone::{impl core::cmp::Eq for recursive_derive_clone::Label}::assert_fields_are_eq]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:27-10:29
    Visibility: public -/
def Label.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Label) : Result Unit := do
  ok ()

/-- Trait implementation: [recursive_derive_clone::{impl core::cmp::Eq for recursive_derive_clone::Label}]
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:27-10:29 -/
@[reducible]
def Label.Insts.CoreCmpEq : core.cmp.Eq Label := {
  partialEqInst := Label.Insts.CoreCmpPartialEqLabel
  assert_fields_are_eq := Label.Insts.CoreCmpEq.assert_fields_are_eq
}

mutual

/-- [recursive_derive_clone::{impl core::cmp::Ord for recursive_derive_clone::Label}::cmp]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:31-10:34
    Visibility: public -/
def Label.Insts.CoreCmpOrd.cmp
  (self : Label) (other : Label) : Result Ordering := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  let o ← lift (core.cmp.impls.OrdIsize.cmp self1 other1)
  match o with
  | Ordering.lt => ok Ordering.lt
  | Ordering.eq =>
    match self with
    | Label.Fixed __self_0 =>
      match other with
      | Label.Fixed __arg1_0 =>
        ok (core.cmp.impls.OrdUsize.cmp __self_0 __arg1_0)
      | Label.Custom _ => ok Ordering.eq
      | Label.Collection _ => ok Ordering.eq
      | Label.NoLabel => ok Ordering.eq
    | Label.Custom __self_0 =>
      match other with
      | Label.Fixed _ => ok Ordering.eq
      | Label.Custom __arg1_0 =>
        ok (core.cmp.impls.OrdU32.cmp __self_0 __arg1_0)
      | Label.Collection _ => ok Ordering.eq
      | Label.NoLabel => ok Ordering.eq
    | Label.Collection __self_0 =>
      match other with
      | Label.Fixed _ => ok Ordering.eq
      | Label.Custom _ => ok Ordering.eq
      | Label.Collection __arg1_0 =>
        alloc.vec.OrdVec.cmp
          ({ eqInst := Label.Insts.CoreCmpEq,
             partialOrdInst :=
               ({ partialEqInst := Label.Insts.CoreCmpPartialEqLabel,
                  partial_cmp :=
                    (Label.Insts.CoreCmpPartialOrdLabel.partial_cmp) } :
               core.cmp.PartialOrd Label Label),
             cmp := (Label.Insts.CoreCmpOrd.cmp) } : core.cmp.Ord Label)
          __self_0 __arg1_0
      | Label.NoLabel => ok Ordering.eq
    | Label.NoLabel => ok Ordering.eq
  | Ordering.gt => ok Ordering.gt
partial_fixpoint monotonicity by aeneas_monotonicity []

/-- [recursive_derive_clone::{impl core::cmp::PartialOrd<recursive_derive_clone::Label> for recursive_derive_clone::Label}::partial_cmp]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 19:4-21:5
    Visibility: public -/
def Label.Insts.CoreCmpPartialOrdLabel.partial_cmp
  (self : Label) (other : Label) : Result (Option Ordering) := do
  let o ← Label.Insts.CoreCmpOrd.cmp self other
  ok (some o)
partial_fixpoint monotonicity by aeneas_monotonicity []

end

/-- Trait implementation: [recursive_derive_clone::{impl core::cmp::PartialOrd<recursive_derive_clone::Label> for recursive_derive_clone::Label}]
    Source: 'tests/src/recursive-derive-clone.rs', lines 18:0-22:1 -/
@[reducible]
def Label.Insts.CoreCmpPartialOrdLabel : core.cmp.PartialOrd Label Label := {
  partialEqInst := Label.Insts.CoreCmpPartialEqLabel
  partial_cmp := Label.Insts.CoreCmpPartialOrdLabel.partial_cmp
}

/-- Trait implementation: [recursive_derive_clone::{impl core::cmp::Ord for recursive_derive_clone::Label}]
    Source: 'tests/src/recursive-derive-clone.rs', lines 10:31-10:34 -/
@[reducible]
def Label.Insts.CoreCmpOrd : core.cmp.Ord Label := {
  eqInst := Label.Insts.CoreCmpEq
  partialOrdInst := Label.Insts.CoreCmpPartialOrdLabel
  cmp := Label.Insts.CoreCmpOrd.cmp
}

/-- [recursive_derive_clone::copy]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 25:0-27:1
    Visibility: public -/
def copy (l : Label) : Result Label := do
  Label.Insts.CoreCloneClone.clone l

/-- [recursive_derive_clone::same]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 30:0-32:1
    Visibility: public -/
def same (a : Label) (b : Label) : Result Bool := do
  Label.Insts.CoreCmpPartialEqLabel.eq a b

/-- [recursive_derive_clone::order]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 35:0-37:1
    Visibility: public -/
def order (a : Label) (b : Label) : Result Ordering := do
  Label.Insts.CoreCmpOrd.cmp a b

/-- [recursive_derive_clone::sample]:
    Source: 'tests/src/recursive-derive-clone.rs', lines 39:0-41:1
    Visibility: public -/
def sample : Result Label := do
  let y ←
    lift (Std.Array.to_slice (Array.make 1#usize [ Label.NoLabel ] : Array
      Label 1#usize))
  let ret := alloc.slice.Slice.into_vec y
  let y1 ←
    lift (Std.Array.to_slice
      (Array.make 2#usize [ Label.Fixed 1#usize, Label.Collection ret ] : Array
      Label 2#usize))
  let ret1 := alloc.slice.Slice.into_vec y1
  ok (Label.Collection ret1)

end recursive_derive_clone
