-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [slice_pattern]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace slice_pattern

/-- [slice_pattern::single]:
    Source: 'tests/src/slice-pattern.rs', lines 5:0-10:1
    Visibility: public -/
def single (s : Slice Std.U32) : Result Std.U32 := do
  let s1 := Slice.len s
  if s1 = 1#usize
  then Slice.index_usize s 0#usize
  else ok 0#u32

/-- [slice_pattern::first_of_two]:
    Source: 'tests/src/slice-pattern.rs', lines 12:0-17:1
    Visibility: public -/
def first_of_two (s : Slice Std.U32) : Result (Option Std.U32) := do
  let s1 := Slice.len s
  if s1 = 2#usize
  then let x ← Slice.index_usize s 0#usize
       ok (some x)
  else ok none

end slice_pattern
