-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [static_str]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace static_str

/-- [core::fmt::{impl core::fmt::Debug for str}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2917:4-2917:50
    Name pattern: [core::fmt::{core::fmt::Debug<str>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Debug<str>}::fmt"]
axiom Str.Insts.CoreFmtDebug.fmt
  :
  Str → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [core::fmt::{impl core::fmt::Debug for str}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2916:0-2916:18
    Name pattern: [core::fmt::Debug<str>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<str>"]
def Str.Insts.CoreFmtDebug : core.fmt.Debug Str := {
  fmt := Str.Insts.CoreFmtDebug.fmt
}

/-- [static_str::name]:
    Source: 'tests/src/static-str.rs', lines 7:0-9:1
    Visibility: public -/
def «name» : Result Str := do
  ok (toStr "column")

/-- [static_str::Any]
    Source: 'tests/src/static-str.rs', lines 12:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive Any where
| Advice : Any
| Fixed : Any

/-- [static_str::{impl core::clone::Clone for static_str::Any}::clone]:
    Source: 'tests/src/static-str.rs', lines 11:9-11:14
    Visibility: public -/
def Any.Insts.CoreCloneClone.clone (self : Any) : Result Any := do
  ok self

/-- Trait implementation: [static_str::{impl core::clone::Clone for static_str::Any}]
    Source: 'tests/src/static-str.rs', lines 11:9-11:14 -/
@[reducible]
def Any.Insts.CoreCloneClone : core.clone.Clone Any := {
  clone := Any.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [static_str::{impl core::marker::Copy for static_str::Any}]
    Source: 'tests/src/static-str.rs', lines 11:16-11:20 -/
@[reducible]
def Any.Insts.CoreMarkerCopy : core.marker.Copy Any := {
  cloneInst := Any.Insts.CoreCloneClone
}

/-- [static_str::Column]
    Source: 'tests/src/static-str.rs', lines 18:0-21:1
    Visibility: public -/
structure Column where
  index : Std.Usize
  column_type : Any

/-- [static_str::{impl core::clone::Clone for static_str::Column}::clone]:
    Source: 'tests/src/static-str.rs', lines 17:9-17:14
    Visibility: public -/
def Column.Insts.CoreCloneClone.clone (self : Column) : Result Column := do
  ok self

/-- Trait implementation: [static_str::{impl core::clone::Clone for static_str::Column}]
    Source: 'tests/src/static-str.rs', lines 17:9-17:14 -/
@[reducible]
def Column.Insts.CoreCloneClone : core.clone.Clone Column := {
  clone := Column.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [static_str::{impl core::marker::Copy for static_str::Column}]
    Source: 'tests/src/static-str.rs', lines 17:16-17:20 -/
@[reducible]
def Column.Insts.CoreMarkerCopy : core.marker.Copy Column := {
  cloneInst := Column.Insts.CoreCloneClone
}

/-- [static_str::{static_str::Column}::column_type]:
    Source: 'tests/src/static-str.rs', lines 24:4-26:5
    Visibility: public -/
def Column.impl.column_type (self : Column) : Result Any := do
  ok self.column_type

/-- [static_str::advice_index]:
    Source: 'tests/src/static-str.rs', lines 30:0-35:1
    Visibility: public -/
def advice_index
  (any : Column) : Result (core.result.Result Std.Usize Str) := do
  let a ← Column.impl.column_type any
  match a with
  | Any.Advice => ok (core.result.Result.Ok any.index)
  | Any.Fixed =>
    ok (core.result.Result.Err (toStr "Cannot convert into Column<Advice>"))

/-- [static_str::first]:
    Source: 'tests/src/static-str.rs', lines 37:0-39:1 -/
def first (a : Str) (_b : Str) : Result Str := do
  ok a

/-- [static_str::renamed]:
    Source: 'tests/src/static-str.rs', lines 42:0-44:1
    Visibility: public -/
def renamed : Result Str := do
  let s ← «name»
  first s (toStr "other")

/-- [static_str::check]:
    Source: 'tests/src/static-str.rs', lines 46:0-49:1
    Visibility: public -/
def check
  (i : Std.Usize) (b : Bool) : Result (core.result.Result Std.Usize Str) := do
  let a ← if b
            then ok Any.Advice
            else ok Any.Fixed
  advice_index { index := i, column_type := a }

/-- [static_str::advice_or_panic]:
    Source: 'tests/src/static-str.rs', lines 52:0-54:1
    Visibility: public -/
def advice_or_panic (i : Std.Usize) : Result Std.Usize := do
  let r ← check i true
  core.result.Result.unwrap (core.fmt.DebugShared Str.Insts.CoreFmtDebug) r

end static_str
