-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [std_small_ops]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace std_small_ops

/-- Trait implementation: [core::option::{impl core::cmp::PartialEq<core::option::Option<T>> for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 2439:0-2439:56
    Name pattern: [core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<core::option::Option<@T>, core::option::Option<@T>>"]
def core.option.Option.Insts.CoreCmpPartialEqOption {T : Type}
  (cmpPartialEqInst : core.cmp.PartialEq T T) : core.cmp.PartialEq (Option T)
  (Option T) := {
  eq := core.option.Option.Insts.CoreCmpPartialEqOption.eq cmpPartialEqInst
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 28:12-28:74
    Name pattern: [core::cmp::PartialEq<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialEqPair {U : Type} {T : Type} (cmpPartialEqInst :
  core.cmp.PartialEq U U) (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (U × T) (U × T) := {
  eq := Pair.Insts.CoreCmpPartialEqPair.eq cmpPartialEqInst cmpPartialEqInst1
}

/-- [std_small_ops::option_order]:
    Source: 'tests/src/std-small-ops.rs', lines 8:0-10:1
    Visibility: public -/
def option_order
  (a : Option Std.U32) (b : Option Std.U32) : Result Ordering := do
  core.option.Option.Insts.CoreCmpOrd.cmp core.cmp.OrdU32 a b

/-- [std_small_ops::option_partial_order]:
    Source: 'tests/src/std-small-ops.rs', lines 12:0-14:1
    Visibility: public -/
def option_partial_order
  (a : Option Std.U32) (b : Option Std.U32) : Result (Option Ordering) := do
  core.option.Option.Insts.CoreCmpPartialOrdOption.partial_cmp
    core.cmp.PartialOrdU32 a b

/-- [std_small_ops::option_same]:
    Source: 'tests/src/std-small-ops.rs', lines 16:0-18:1
    Visibility: public -/
def option_same (a : Option Std.U32) (b : Option Std.U32) : Result Bool := do
  core.option.Option.Insts.CoreCmpPartialEqOption.eq core.cmp.PartialEqU32 a b

/-- [std_small_ops::or_default]:
    Source: 'tests/src/std-small-ops.rs', lines 20:0-22:1
    Visibility: public -/
def or_default (a : Option Std.U32) : Result Std.U32 := do
  core.option.Option.unwrap_or_default core.default.DefaultU32 a

/-- [std_small_ops::pair_same]:
    Source: 'tests/src/std-small-ops.rs', lines 24:0-26:1
    Visibility: public -/
def pair_same
  (a : (Std.U32 × Std.U64)) (b : (Std.U32 × Std.U64)) : Result Bool := do
  Pair.Insts.CoreCmpPartialEqPair.eq core.cmp.PartialEqU32
    core.cmp.PartialEqU64 a b

/-- [std_small_ops::ref_order]:
    Source: 'tests/src/std-small-ops.rs', lines 29:0-31:1
    Visibility: public -/
def ref_order (a : Std.U32) (b : Std.U32) : Result Ordering := do
  core.cmp.impls.OrdShared.cmp core.cmp.OrdU32 a b

/-- [std_small_ops::abs]:
    Source: 'tests/src/std-small-ops.rs', lines 33:0-35:1
    Visibility: public -/
def abs (x : Std.I32) : Result Std.I32 := do
  core.num.I32.abs x

/-- [std_small_ops::unsigned_abs]:
    Source: 'tests/src/std-small-ops.rs', lines 37:0-39:1
    Visibility: public -/
def unsigned_abs (x : Std.I64) : Result Std.U64 := do
  core.num.I64.unsigned_abs x

/-- [std_small_ops::div_ceil]:
    Source: 'tests/src/std-small-ops.rs', lines 41:0-43:1
    Visibility: public -/
def div_ceil (a : Std.Usize) (b : Std.Usize) : Result Std.Usize := do
  core.num.Usize.div_ceil a b

/-- [std_small_ops::next_power_of_two]:
    Source: 'tests/src/std-small-ops.rs', lines 45:0-47:1
    Visibility: public -/
def next_power_of_two (x : Std.Usize) : Result Std.Usize := do
  core.num.Usize.next_power_of_two x

/-- [std_small_ops::swap_remove]:
    Source: 'tests/src/std-small-ops.rs', lines 49:0-51:1
    Visibility: public -/
def swap_remove
  (v : alloc.vec.Vec Std.U32) (i : Std.Usize) :
  Result (Std.U32 × (alloc.vec.Vec Std.U32))
  := do
  alloc.vec.Vec.swap_remove v i

/-- [std_small_ops::copied]:
    Source: 'tests/src/std-small-ops.rs', lines 54:0-56:1
    Visibility: public -/
def copied (x : Option Std.U32) : Result (Option Std.U32) := do
  core.option.OptionShared0T.copied core.marker.CopyU32 x

/-- [std_small_ops::split_first::{closure}]
    Source: 'tests/src/std-small-ops.rs', lines 60:24-60:46 -/
@[reducible]
def split_first.closure := Unit

/-- [std_small_ops::split_first::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 [u32]),), (u32, usize)> for std_small_ops::split_first::{closure}}::call_once]:
    Source: 'tests/src/std-small-ops.rs', lines 60:24-60:46 -/
def
  split_first.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1SliceU32PairU32Usize.call_once
  (c : split_first.closure) (tupled_args : (Std.U32 × (Slice Std.U32))) :
  Result (Std.U32 × Std.Usize)
  := do
  let (h, t) := tupled_args
  let i := Slice.len t
  ok (h, i)

/-- Trait implementation: [std_small_ops::split_first::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 [u32]),), (u32, usize)> for std_small_ops::split_first::{closure}}]
    Source: 'tests/src/std-small-ops.rs', lines 60:24-60:46 -/
@[reducible]
def
  split_first.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1SliceU32PairU32Usize
  : core.ops.function.FnOnce split_first.closure (Std.U32 × (Slice Std.U32))
  (Std.U32 × Std.Usize) := {
  call_once :=
    split_first.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1SliceU32PairU32Usize.call_once
}

/-- [std_small_ops::split_first]:
    Source: 'tests/src/std-small-ops.rs', lines 59:0-61:1
    Visibility: public -/
def split_first
  (s : Slice Std.U32) : Result (Option (Std.U32 × Std.Usize)) := do
  let o ← core.slice.Slice.split_first s
  core.option.Option.map
    split_first.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1SliceU32PairU32Usize
    o ()

/-- [std_small_ops::from_ref]:
    Source: 'tests/src/std-small-ops.rs', lines 63:0-65:1
    Visibility: public -/
def from_ref (x : Std.U32) : Result Std.Usize := do
  let s ← core.slice.raw.from_ref x
  ok (Slice.len s)

/-- [std_small_ops::phantom]:
    Source: 'tests/src/std-small-ops.rs', lines 67:0-69:1
    Visibility: public -/
def phantom : Result (core.marker.PhantomData Std.U32) := do
  core.marker.PhantomData.Insts.CoreDefaultDefault.default Std.U32

/-- [std_small_ops::borrowed]:
    Source: 'tests/src/std-small-ops.rs', lines 71:0-73:1
    Visibility: public -/
def borrowed (x : Std.U32) : Result Std.U32 := do
  core.borrow.Borrow.Blanket.borrow x

end std_small_ops
