-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [string_ops]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace string_ops

/-- Trait implementation: [alloc::string::{impl core::cmp::PartialEq<alloc::string::String> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [core::cmp::PartialEq<alloc::string::String, alloc::string::String>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<alloc::string::String, alloc::string::String>"]
def alloc.string.String.Insts.CoreCmpPartialEqString : core.cmp.PartialEq
  String String := {
  eq := alloc.string.String.Insts.CoreCmpPartialEqString.eq
}

/-- [string_ops::copy]:
    Source: 'tests/src/string-ops.rs', lines 8:0-10:1
    Visibility: public -/
def copy (s : String) : Result String := do
  alloc.string.String.Insts.CoreCloneClone.clone s

/-- [string_ops::same]:
    Source: 'tests/src/string-ops.rs', lines 12:0-14:1
    Visibility: public -/
def same (a : String) (b : String) : Result Bool := do
  alloc.string.String.Insts.CoreCmpPartialEqString.eq a b

/-- [string_ops::order]:
    Source: 'tests/src/string-ops.rs', lines 16:0-18:1
    Visibility: public -/
def order (a : String) (b : String) : Result Ordering := do
  alloc.string.String.Insts.CoreCmpOrd.cmp a b

/-- [string_ops::partial_order]:
    Source: 'tests/src/string-ops.rs', lines 20:0-22:1
    Visibility: public -/
def partial_order (a : String) (b : String) : Result (Option Ordering) := do
  alloc.string.String.Insts.CoreCmpPartialOrdString.partial_cmp a b

/-- [string_ops::Tag]
    Source: 'tests/src/string-ops.rs', lines 25:0-28:1
    Visibility: public -/
@[discriminant isize]
inductive Tag where
| Fixed : Std.Usize → Tag
| Custom : String → Tag

/-- [string_ops::{impl core::clone::Clone for string_ops::Tag}::clone]:
    Source: 'tests/src/string-ops.rs', lines 24:9-24:14
    Visibility: public -/
def Tag.Insts.CoreCloneClone.clone (self : Tag) : Result Tag := do
  match self with
  | Tag.Fixed __self_0 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    ok (Tag.Fixed i)
  | Tag.Custom __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (Tag.Custom s)

/-- Trait implementation: [string_ops::{impl core::clone::Clone for string_ops::Tag}]
    Source: 'tests/src/string-ops.rs', lines 24:9-24:14 -/
@[reducible]
def Tag.Insts.CoreCloneClone : core.clone.Clone Tag := {
  clone := Tag.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [string_ops::{impl core::marker::StructuralPartialEq for string_ops::Tag}]
    Source: 'tests/src/string-ops.rs', lines 24:16-24:25 -/
@[reducible]
def Tag.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Tag := {
}

/-- [string_ops::{impl core::cmp::PartialEq<string_ops::Tag> for string_ops::Tag}::eq]:
    Source: 'tests/src/string-ops.rs', lines 24:16-24:25
    Visibility: public -/
def Tag.Insts.CoreCmpPartialEqTag.eq
  (self : Tag) (other : Tag) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Tag.Fixed __self_0 =>
      match other with
      | Tag.Fixed __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
      | Tag.Custom _ => fail panic
    | Tag.Custom __self_0 =>
      match other with
      | Tag.Fixed _ => fail panic
      | Tag.Custom __arg1_0 =>
        alloc.string.String.Insts.CoreCmpPartialEqString.eq __self_0 __arg1_0
  else ok false

/-- Trait implementation: [string_ops::{impl core::cmp::PartialEq<string_ops::Tag> for string_ops::Tag}]
    Source: 'tests/src/string-ops.rs', lines 24:16-24:25 -/
@[reducible]
def Tag.Insts.CoreCmpPartialEqTag : core.cmp.PartialEq Tag Tag := {
  eq := Tag.Insts.CoreCmpPartialEqTag.eq
}

/-- [string_ops::{impl core::cmp::Eq for string_ops::Tag}::assert_fields_are_eq]:
    Source: 'tests/src/string-ops.rs', lines 24:27-24:29
    Visibility: public -/
def Tag.Insts.CoreCmpEq.assert_fields_are_eq (self : Tag) : Result Unit := do
  ok ()

/-- Trait implementation: [string_ops::{impl core::cmp::Eq for string_ops::Tag}]
    Source: 'tests/src/string-ops.rs', lines 24:27-24:29 -/
@[reducible]
def Tag.Insts.CoreCmpEq : core.cmp.Eq Tag := {
  partialEqInst := Tag.Insts.CoreCmpPartialEqTag
  assert_fields_are_eq := Tag.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [string_ops::{impl core::cmp::Ord for string_ops::Tag}::cmp]:
    Source: 'tests/src/string-ops.rs', lines 24:43-24:46
    Visibility: public -/
def Tag.Insts.CoreCmpOrd.cmp (self : Tag) (other : Tag) : Result Ordering := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  let o ← lift (core.cmp.impls.OrdIsize.cmp self1 other1)
  match o with
  | Ordering.lt => ok Ordering.lt
  | Ordering.eq =>
    match self with
    | Tag.Fixed __self_0 =>
      match other with
      | Tag.Fixed __arg1_0 =>
        ok (core.cmp.impls.OrdUsize.cmp __self_0 __arg1_0)
      | Tag.Custom _ => fail panic
    | Tag.Custom __self_0 =>
      match other with
      | Tag.Fixed _ => fail panic
      | Tag.Custom __arg1_0 =>
        alloc.string.String.Insts.CoreCmpOrd.cmp __self_0 __arg1_0
  | Ordering.gt => ok Ordering.gt

/-- [string_ops::{impl core::cmp::PartialOrd<string_ops::Tag> for string_ops::Tag}::partial_cmp]:
    Source: 'tests/src/string-ops.rs', lines 24:31-24:41
    Visibility: public -/
def Tag.Insts.CoreCmpPartialOrdTag.partial_cmp
  (self : Tag) (other : Tag) : Result (Option Ordering) := do
  let o ← Tag.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [string_ops::{impl core::cmp::PartialOrd<string_ops::Tag> for string_ops::Tag}]
    Source: 'tests/src/string-ops.rs', lines 24:31-24:41 -/
@[reducible]
def Tag.Insts.CoreCmpPartialOrdTag : core.cmp.PartialOrd Tag Tag := {
  partialEqInst := Tag.Insts.CoreCmpPartialEqTag
  partial_cmp := Tag.Insts.CoreCmpPartialOrdTag.partial_cmp
}

/-- Trait implementation: [string_ops::{impl core::cmp::Ord for string_ops::Tag}]
    Source: 'tests/src/string-ops.rs', lines 24:43-24:46 -/
@[reducible]
def Tag.Insts.CoreCmpOrd : core.cmp.Ord Tag := {
  eqInst := Tag.Insts.CoreCmpEq
  partialOrdInst := Tag.Insts.CoreCmpPartialOrdTag
  cmp := Tag.Insts.CoreCmpOrd.cmp
}

/-- [string_ops::copy_tag]:
    Source: 'tests/src/string-ops.rs', lines 30:0-32:1
    Visibility: public -/
def copy_tag (l : Tag) : Result Tag := do
  Tag.Insts.CoreCloneClone.clone l

/-- [string_ops::same_tag]:
    Source: 'tests/src/string-ops.rs', lines 34:0-36:1
    Visibility: public -/
def same_tag (a : Tag) (b : Tag) : Result Bool := do
  Tag.Insts.CoreCmpPartialEqTag.eq a b

/-- [string_ops::order_tag]:
    Source: 'tests/src/string-ops.rs', lines 38:0-40:1
    Visibility: public -/
def order_tag (a : Tag) (b : Tag) : Result Ordering := do
  Tag.Insts.CoreCmpOrd.cmp a b

/-- [string_ops::partial_order_tag]:
    Source: 'tests/src/string-ops.rs', lines 42:0-44:1
    Visibility: public -/
def partial_order_tag (a : Tag) (b : Tag) : Result (Option Ordering) := do
  Tag.Insts.CoreCmpPartialOrdTag.partial_cmp a b

end string_ops
