-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [str_unicode]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace str_unicode

/-- [str_unicode::pi]:
    Source: 'tests/src/str-unicode.rs', lines 3:0-5:1
    Visibility: public -/
def pi : Result Str := do
  ok (toStr "π")

/-- [str_unicode::escapes]:
    Source: 'tests/src/str-unicode.rs', lines 7:0-9:1
    Visibility: public -/
def escapes : Result Str := do
  ok (toStr "tab\there \"quoted\" back\\slash\nnul\x00 bell\x07 é")

end str_unicode
