-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_method_diamond]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait_method_diamond

/-- Trait declaration: [trait_method_diamond::TranscriptHash]
    Source: 'tests/src/trait-method-diamond.rs', lines 7:0-10:1
    Visibility: public -/
structure TranscriptHash (Self : Type) (Self_Input : Type) where
  absorb : Self → Self_Input → Result Self

/-- Trait declaration: [trait_method_diamond::Hashable]
    Source: 'tests/src/trait-method-diamond.rs', lines 12:0-14:1
    Visibility: public -/
structure Hashable (Self : Type) (H : Type) (Self_Clause0_Input : Type) where
  TranscriptHashInst : TranscriptHash H Self_Clause0_Input
  to_input : Self → Result Self_Clause0_Input

/-- Trait declaration: [trait_method_diamond::Transcript]
    Source: 'tests/src/trait-method-diamond.rs', lines 16:0-19:1
    Visibility: public -/
structure Transcript (Self : Type) (Self_Hash : Type) (Self_Clause0_Input :
  Type) where
  TranscriptHashInst : TranscriptHash Self_Hash Self_Clause0_Input
  hasher : Self → Result (Self_Hash × (Self_Hash → Self))

/-- Trait declaration: [trait_method_diamond::Scheme]
    Source: 'tests/src/trait-method-diamond.rs', lines 21:0-29:1
    Visibility: public -/
structure Scheme (Self : Type) (Self_Commitment : Type) (Self_Params : Type)
  (Self_Guard : Type) where
  write : forall {T : Type} {Clause0_Hash : Type} {Clause0_Clause0_Input :
    Type} (Clause1_Clause0_Input : Type) (TranscriptInst : Transcript T
    Clause0_Hash Clause0_Clause0_Input) (HashableInst : Hashable
    Self_Commitment Clause0_Hash Clause0_Clause0_Input), T → Self_Commitment
    → Self_Guard → Result T
  size : Result Std.Usize

/-- [trait_method_diamond::Kzg]
    Source: 'tests/src/trait-method-diamond.rs', lines 31:0-31:15
    Visibility: public -/
@[reducible]
def Kzg := Unit

/-- [trait_method_diamond::sizes]:
    Source: 'tests/src/trait-method-diamond.rs', lines 60:0-62:1
    Visibility: public -/
def sizes
  {S : Type} {Clause0_Commitment : Type} {Clause0_Params : Type} {Clause0_Guard
  : Type} (SchemeInst : Scheme S Clause0_Commitment Clause0_Params
  Clause0_Guard) (n : Std.Usize) :
  Result Std.Usize
  := do
  if n = 0#usize
  then ok 0#usize
  else SchemeInst.size

/-- [trait_method_diamond::{impl trait_method_diamond::Scheme<u32, (), u8> for trait_method_diamond::Kzg}::write]:
    Source: 'tests/src/trait-method-diamond.rs', lines 37:4-43:5
    Visibility: public -/
def Kzg.Insts.Trait_method_diamondSchemeU32TupleU8.write
  {T : Type} {Clause0_Hash : Type} {Clause0_Clause0_Input : Type}
  (Clause1_Clause0_Input : Type) (TranscriptInst : Transcript T Clause0_Hash
  Clause0_Clause0_Input) (HashableU32Clause0_HashClause0_Clause0_InputInst :
  Hashable Std.U32 Clause0_Hash Clause0_Clause0_Input) (t : T) (c : Std.U32)
  (_g : Std.U8) :
  Result T
  := do
  let x ← HashableU32Clause0_HashClause0_Clause0_InputInst.to_input c
  let (t1, hasher_back) ← TranscriptInst.hasher t
  let t2 ←
    HashableU32Clause0_HashClause0_Clause0_InputInst.TranscriptHashInst.absorb
      t1 x
  ok (hasher_back t2)

/-- [trait_method_diamond::{impl trait_method_diamond::Scheme<u32, (), u8> for trait_method_diamond::Kzg}::size]:
    Source: 'tests/src/trait-method-diamond.rs', lines 44:4-46:5
    Visibility: public -/
def Kzg.Insts.Trait_method_diamondSchemeU32TupleU8.size
  : Result Std.Usize := do
  sizes
    ({ write := ( fun {T : Type} {Clause0_Hash : Type} {Clause0_Clause0_Input :
         Type} (Clause1_Clause0_Input : Type) (TranscriptInst : Transcript T
         Clause0_Hash Clause0_Clause0_Input) (HashableU32PPInst : Hashable
         Std.U32 Clause0_Hash Clause0_Clause0_Input) =>
         Kzg.Insts.Trait_method_diamondSchemeU32TupleU8.write
         Clause0_Clause0_Input TranscriptInst HashableU32PPInst),
       size := (Kzg.Insts.Trait_method_diamondSchemeU32TupleU8.size) } : Scheme
    Kzg Std.U32 Unit Std.U8) 1#usize
partial_fixpoint monotonicity by aeneas_monotonicity [sizes]

/-- Trait implementation: [trait_method_diamond::{impl trait_method_diamond::Scheme<u32, (), u8> for trait_method_diamond::Kzg}]
    Source: 'tests/src/trait-method-diamond.rs', lines 33:0-47:1 -/
@[reducible]
impl_def Kzg.Insts.Trait_method_diamondSchemeU32TupleU8 : Scheme Kzg Std.U32
  Unit Std.U8 := {
  write := fun {T : Type} {Clause0_Hash : Type} {Clause0_Clause0_Input : Type}
    (Clause1_Clause0_Input : Type) (TranscriptInst : Transcript T Clause0_Hash
    Clause0_Clause0_Input) (HashableU32PPInst : Hashable Std.U32 Clause0_Hash
    Clause0_Clause0_Input) =>
    Kzg.Insts.Trait_method_diamondSchemeU32TupleU8.write Clause0_Clause0_Input
    TranscriptInst HashableU32PPInst
  size := Kzg.Insts.Trait_method_diamondSchemeU32TupleU8.size
}

/-- [trait_method_diamond::write_through]:
    Source: 'tests/src/trait-method-diamond.rs', lines 52:0-57:1
    Visibility: public -/
def write_through
  {S : Type} {T : Type} {Clause0_Commitment : Type} {Clause0_Params : Type}
  {Clause0_Guard : Type} {Clause1_Hash : Type} {Clause1_Clause0_Input : Type}
  (Clause2_Clause0_Input : Type) (SchemeInst : Scheme S Clause0_Commitment
  Clause0_Params Clause0_Guard) (TranscriptInst : Transcript T Clause1_Hash
  Clause1_Clause0_Input) (HashableInst : Hashable Clause0_Commitment
  Clause1_Hash Clause1_Clause0_Input) (t : T) (c : Clause0_Commitment)
  (g : Clause0_Guard) :
  Result T
  := do
  SchemeInst.write Clause1_Clause0_Input TranscriptInst HashableInst t c g

end trait_method_diamond
