-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [misc_extra]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace misc_extra

/-- [misc_extra::Label]
    Source: 'tests/src/misc-extra.rs', lines 10:0-10:26
    Visibility: public -/
@[reducible]
def Label := Std.U32

/-- [misc_extra::Tagged]
    Source: 'tests/src/misc-extra.rs', lines 19:0-22:1
    Visibility: public -/
structure Tagged (T : Type) where
  «name» : String
  marker : core.marker.PhantomData T

/-- [misc_extra::conv::{closure}]
    Source: 'tests/src/misc-extra.rs', lines 36:29-36:49 -/
@[reducible]
def conv.closure := Unit

end misc_extra
