-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [iter_extra]: function definitions
module
public import Aeneas
public import IterExtra.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace iter_extra

/-- Trait implementation: [core::iter::adapters::zip::{impl core::iter::traits::double_ended::DoubleEndedIterator<(Clause0_Clause0_Item, Clause2_Clause0_Item)> for core::iter::adapters::zip::Zip<A, B>}]
    Source: '/rustc/library/core/src/iter/adapters/zip.rs', lines 116:0-119:47
    Name pattern: [core::iter::traits::double_ended::DoubleEndedIterator<core::iter::adapters::zip::Zip<@A, @B>, (@Clause0_Clause0_Item, @Clause2_Clause0_Item)>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::double_ended::DoubleEndedIterator<core::iter::adapters::zip::Zip<@A, @B>, (@Clause0_Clause0_Item, @Clause2_Clause0_Item)>"]
def
  core.iter.adapters.zip.Zip.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorPair
  {A : Type} {B : Type} {Clause0_Clause0_Item : Type} {Clause1_Clause0_Item :
  Type} {Clause2_Clause0_Item : Type} {Clause3_Clause0_Item : Type}
  (traitsdouble_endedDoubleEndedIteratorInst :
  core.iter.traits.double_ended.DoubleEndedIterator A Clause0_Clause0_Item)
  (traitsexact_sizeExactSizeIteratorInst :
  core.iter.traits.exact_size.ExactSizeIterator A Clause1_Clause0_Item)
  (traitsdouble_endedDoubleEndedIteratorInst1 :
  core.iter.traits.double_ended.DoubleEndedIterator B Clause2_Clause0_Item)
  (traitsexact_sizeExactSizeIteratorInst1 :
  core.iter.traits.exact_size.ExactSizeIterator B Clause3_Clause0_Item) :
  core.iter.traits.double_ended.DoubleEndedIterator (core.iter.adapters.zip.Zip
  A B) (Clause0_Clause0_Item × Clause2_Clause0_Item) := {
  iteratorInst :=
    core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair
    traitsdouble_endedDoubleEndedIteratorInst.iteratorInst
    traitsdouble_endedDoubleEndedIteratorInst1.iteratorInst
  next_back :=
    core.iter.adapters.zip.Zip.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorPair.next_back
    traitsdouble_endedDoubleEndedIteratorInst
    traitsexact_sizeExactSizeIteratorInst
    traitsdouble_endedDoubleEndedIteratorInst1
    traitsexact_sizeExactSizeIteratorInst1
}

/-- Trait implementation: [core::slice::iter::{impl core::iter::traits::exact_size::ExactSizeIterator<&'_ T> for core::slice::iter::Iter<'_0, T>}]
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 140:8-140:50
    Name pattern: [core::iter::traits::exact_size::ExactSizeIterator<core::slice::iter::Iter<'0, @T>, &'_ @T>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::exact_size::ExactSizeIterator<core::slice::iter::Iter<'0, @T>, &'_ @T>"]
def core.slice.iter.Iter.Insts.CoreIterTraitsExact_sizeExactSizeIteratorSharedT
  (T : Type) : core.iter.traits.exact_size.ExactSizeIterator
  (core.slice.iter.Iter T) T := {
  iteratorInst := core.iter.traits.iterator.IteratorSliceIter T
}

/-- Trait implementation: [core::slice::iter::{impl core::iter::traits::double_ended::DoubleEndedIterator<&'_ T> for core::slice::iter::Iter<'a, T>}]
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 431:8-431:56
    Name pattern: [core::iter::traits::double_ended::DoubleEndedIterator<core::slice::iter::Iter<'a, @T>, &'_ @T>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::double_ended::DoubleEndedIterator<core::slice::iter::Iter<'a, @T>, &'_ @T>"]
def
  core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
  (T : Type) : core.iter.traits.double_ended.DoubleEndedIterator
  (core.slice.iter.Iter T) T := {
  iteratorInst := core.iter.traits.iterator.IteratorSliceIter T
  next_back := core.slice.iter.IteratorSliceIter.next_back
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialEq<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 28:12-28:74
    Name pattern: [core::cmp::PartialEq<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialEqPair {U : Type} {T : Type} (cmpPartialEqInst :
  core.cmp.PartialEq U U) (cmpPartialEqInst1 : core.cmp.PartialEq T T) :
  core.cmp.PartialEq (U × T) (U × T) := {
  eq := Pair.Insts.CoreCmpPartialEqPair.eq cmpPartialEqInst cmpPartialEqInst1
}

/-- Trait implementation: [core::tuple::{impl core::cmp::Eq for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 44:12-44:60
    Name pattern: [core::cmp::Eq<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::Eq<(@U, @T)>"]
def Pair.Insts.CoreCmpEq {U : Type} {T : Type} (cmpEqInst : core.cmp.Eq U)
  (cmpEqInst1 : core.cmp.Eq T) : core.cmp.Eq (U × T) := {
  partialEqInst := Pair.Insts.CoreCmpPartialEqPair cmpEqInst.partialEqInst
    cmpEqInst1.partialEqInst
}

/-- Trait implementation: [core::tuple::{impl core::cmp::PartialOrd<(U, T)> for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 66:12-66:76
    Name pattern: [core::cmp::PartialOrd<(@U, @T), (@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::PartialOrd<(@U, @T), (@U, @T)>"]
def Pair.Insts.CoreCmpPartialOrdPair {U : Type} {T : Type} (cmpPartialOrdInst :
  core.cmp.PartialOrd U U) (cmpPartialOrdInst1 : core.cmp.PartialOrd T T) :
  core.cmp.PartialOrd (U × T) (U × T) := {
  partialEqInst := Pair.Insts.CoreCmpPartialEqPair
    cmpPartialOrdInst.partialEqInst cmpPartialOrdInst1.partialEqInst
  partial_cmp := Pair.Insts.CoreCmpPartialOrdPair.partial_cmp cmpPartialOrdInst
    cmpPartialOrdInst1
}

/-- Trait implementation: [core::tuple::{impl core::cmp::Ord for (U, T)}]
    Source: '/rustc/library/core/src/tuple.rs', lines 111:12-111:62
    Name pattern: [core::cmp::Ord<(@U, @T)>] -/
@[reducible, rust_trait_impl "core::cmp::Ord<(@U, @T)>"]
def Pair.Insts.CoreCmpOrd {U : Type} {T : Type} (cmpOrdInst : core.cmp.Ord U)
  (cmpOrdInst1 : core.cmp.Ord T) : core.cmp.Ord (U × T) := {
  eqInst := Pair.Insts.CoreCmpEq cmpOrdInst.eqInst cmpOrdInst1.eqInst
  partialOrdInst := Pair.Insts.CoreCmpPartialOrdPair cmpOrdInst.partialOrdInst
    cmpOrdInst1.partialOrdInst
  cmp := Pair.Insts.CoreCmpOrd.cmp cmpOrdInst cmpOrdInst1
}

/-- [iter_extra::powers::{impl core::ops::function::FnMut<(&'_0 u32,), core::option::Option<u32>> for iter_extra::powers::{closure}}::call_mut]:
    Source: 'tests/src/iter-extra.rs', lines 8:38-8:66 -/
def powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32.call_mut
  (c : powers.closure) (tupled_args : Std.U32) :
  Result ((Option Std.U32) × powers.closure)
  := do
  let o ← lift (U32.checked_mul tupled_args c)
  ok (o, c)

/-- [iter_extra::powers::{impl core::ops::function::FnOnce<(&'_0 u32,), core::option::Option<u32>> for iter_extra::powers::{closure}}::call_once]:
    Source: 'tests/src/iter-extra.rs', lines 8:38-8:66 -/
def
  powers.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32.call_once
  (c : powers.closure) (i : Std.U32) : Result (Option Std.U32) := do
  let (o, _) ←
    powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32.call_mut
      c i
  ok o

/-- Trait implementation: [iter_extra::powers::{impl core::ops::function::FnOnce<(&'_0 u32,), core::option::Option<u32>> for iter_extra::powers::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 8:38-8:66 -/
@[reducible]
def powers.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32 :
  core.ops.function.FnOnce powers.closure Std.U32 (Option Std.U32) := {
  call_once :=
    powers.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32.call_once
}

/-- Trait implementation: [iter_extra::powers::{impl core::ops::function::FnMut<(&'_0 u32,), core::option::Option<u32>> for iter_extra::powers::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 8:38-8:66 -/
@[reducible]
def powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32 :
  core.ops.function.FnMut powers.closure Std.U32 (Option Std.U32) := {
  FnOnceInst :=
    powers.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32OptionU32
  call_mut :=
    powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32.call_mut
}

/-- [iter_extra::powers]:
    Source: 'tests/src/iter-extra.rs', lines 7:0-9:1
    Visibility: public -/
def powers
  (base : Std.U32) :
  Result (core.iter.sources.successors.Successors Std.U32 powers.closure)
  := do
  core.iter.sources.successors.successors
    powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32 (some
    1#u32) base

/-- [iter_extra::first_powers]:
    Source: 'tests/src/iter-extra.rs', lines 11:0-13:1
    Visibility: public -/
def first_powers (base : Std.U32) : Result (alloc.vec.Vec Std.U32) := do
  let s ← powers base
  let t ←
    core.iter.traits.iterator.Iterator.take.trait_default
      (core.iter.sources.successors.Successors.Insts.CoreIterTraitsIteratorIterator
      powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32) s
      4#usize
  core.iter.traits.iterator.Iterator.collect.default
    (core.iter.traits.iterator.IteratorTake
    (core.iter.sources.successors.Successors.Insts.CoreIterTraitsIteratorIterator
    powers.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32OptionU32))
    (core.iter.traits.collect.FromIteratorVec Std.U32) t

/-- [iter_extra::sum_cloned::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_extra::sum_cloned::{closure}}::call_mut]:
    Source: 'tests/src/iter-extra.rs', lines 16:33-16:57 -/
def sum_cloned.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : sum_cloned.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × sum_cloned.closure)
  := do
  let (a, x) := tupled_args
  let i ← lift (core.num.U32.wrapping_add a x)
  ok (i, c)

/-- [iter_extra::sum_cloned::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_extra::sum_cloned::{closure}}::call_once]:
    Source: 'tests/src/iter-extra.rs', lines 16:33-16:57 -/
def sum_cloned.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : sum_cloned.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    sum_cloned.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_extra::sum_cloned::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_extra::sum_cloned::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 16:33-16:57 -/
@[reducible]
def sum_cloned.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce sum_cloned.closure (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    sum_cloned.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_extra::sum_cloned::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_extra::sum_cloned::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 16:33-16:57 -/
@[reducible]
def sum_cloned.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut sum_cloned.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := sum_cloned.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut :=
    sum_cloned.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_extra::sum_cloned]:
    Source: 'tests/src/iter-extra.rs', lines 15:0-17:1
    Visibility: public -/
def sum_cloned (v : Slice Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter v
  let c ←
    core.iter.traits.iterator.Iterator.cloned.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) core.clone.CloneU32
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) i
  core.iter.adapters.cloned.Cloned.Insts.CoreIterTraitsIteratorIterator.fold
    (core.iter.traits.iterator.IteratorSliceIter Std.U32) core.clone.CloneU32
    sum_cloned.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 c 0#u32 ()

/-- [iter_extra::horner::{impl core::ops::function::FnMut<(u32, &'_1 u32), u32> for iter_extra::horner::{closure}<'_0>}::call_mut]:
    Source: 'tests/src/iter-extra.rs', lines 20:35-20:80 -/
def horner.closure.Insts.CoreOpsFunctionFnMutPairU32Shared1U32U32.call_mut
  (c : horner.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × horner.closure)
  := do
  let (acc, c1) := tupled_args
  let i ← lift (core.num.U32.wrapping_mul acc c)
  let i1 ← lift (core.num.U32.wrapping_add i c1)
  ok (i1, c)

/-- [iter_extra::horner::{impl core::ops::function::FnOnce<(u32, &'_1 u32), u32> for iter_extra::horner::{closure}<'_0>}::call_once]:
    Source: 'tests/src/iter-extra.rs', lines 20:35-20:80 -/
def horner.closure.Insts.CoreOpsFunctionFnOncePairU32Shared1U32U32.call_once
  (c : horner.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    horner.closure.Insts.CoreOpsFunctionFnMutPairU32Shared1U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_extra::horner::{impl core::ops::function::FnOnce<(u32, &'_1 u32), u32> for iter_extra::horner::{closure}<'_0>}]
    Source: 'tests/src/iter-extra.rs', lines 20:35-20:80 -/
@[reducible]
def horner.closure.Insts.CoreOpsFunctionFnOncePairU32Shared1U32U32 :
  core.ops.function.FnOnce horner.closure (Std.U32 × Std.U32) Std.U32 := {
  call_once :=
    horner.closure.Insts.CoreOpsFunctionFnOncePairU32Shared1U32U32.call_once
}

/-- Trait implementation: [iter_extra::horner::{impl core::ops::function::FnMut<(u32, &'_1 u32), u32> for iter_extra::horner::{closure}<'_0>}]
    Source: 'tests/src/iter-extra.rs', lines 20:35-20:80 -/
@[reducible]
def horner.closure.Insts.CoreOpsFunctionFnMutPairU32Shared1U32U32 :
  core.ops.function.FnMut horner.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := horner.closure.Insts.CoreOpsFunctionFnOncePairU32Shared1U32U32
  call_mut :=
    horner.closure.Insts.CoreOpsFunctionFnMutPairU32Shared1U32U32.call_mut
}

/-- [iter_extra::horner]:
    Source: 'tests/src/iter-extra.rs', lines 19:0-21:1
    Visibility: public -/
def horner (coeffs : Slice Std.U32) (x : Std.U32) : Result Std.U32 := do
  let i ← core.slice.Slice.iter coeffs
  let r ←
    core.iter.traits.iterator.Iterator.rev.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U32) i
  core.iter.adapters.rev.Rev.Insts.CoreIterTraitsIteratorIterator.fold
    (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
    Std.U32) horner.closure.Insts.CoreOpsFunctionFnMutPairU32Shared1U32U32 r
    0#u32 x

/-- [iter_extra::last_pair::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 u32),), (u32, u32)> for iter_extra::last_pair::{closure}}::call_once]:
    Source: 'tests/src/iter-extra.rs', lines 24:44-24:61 -/
def
  last_pair.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32.call_once
  (c : last_pair.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × Std.U32)
  := do
  ok tupled_args

/-- Trait implementation: [iter_extra::last_pair::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 u32),), (u32, u32)> for iter_extra::last_pair::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 24:44-24:61 -/
@[reducible]
def
  last_pair.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32
  : core.ops.function.FnOnce last_pair.closure (Std.U32 × Std.U32) (Std.U32 ×
  Std.U32) := {
  call_once :=
    last_pair.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32.call_once
}

/-- [iter_extra::last_pair]:
    Source: 'tests/src/iter-extra.rs', lines 23:0-25:1
    Visibility: public -/
def last_pair
  (a : Slice Std.U32) (b : Slice Std.U32) :
  Result (Option (Std.U32 × Std.U32))
  := do
  let i ← core.slice.Slice.iter a
  let i1 ← core.slice.Slice.iter b
  let z ←
    core.iter.traits.iterator.Iterator.zip.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  let r ←
    core.iter.traits.iterator.Iterator.rev.trait_default
      (core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.iterator.IteratorSliceIter Std.U32))
      (core.iter.adapters.zip.Zip.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorPair
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsExact_sizeExactSizeIteratorSharedT
      Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsExact_sizeExactSizeIteratorSharedT
      Std.U32)) z
  let (o, _) ←
    core.iter.adapters.rev.Rev.Insts.CoreIterTraitsIteratorIterator.next
      (core.iter.adapters.zip.Zip.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorPair
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsExact_sizeExactSizeIteratorSharedT
      Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsDouble_endedDoubleEndedIteratorSharedT
      Std.U32)
      (core.slice.iter.Iter.Insts.CoreIterTraitsExact_sizeExactSizeIteratorSharedT
      Std.U32)) r
  core.option.Option.map
    last_pair.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32PairU32U32
    o ()

/-- [iter_extra::split]:
    Source: 'tests/src/iter-extra.rs', lines 27:0-29:1
    Visibility: public -/
def split
  (v : Slice (Std.U32 × Std.U64)) :
  Result ((alloc.vec.Vec Std.U32) × (alloc.vec.Vec Std.U64))
  := do
  let i ← core.slice.Slice.iter v
  let c ←
    core.iter.traits.iterator.Iterator.cloned.default
      (core.iter.traits.iterator.IteratorSliceIter (Std.U32 × Std.U64))
      (BuiltinClone (Std.U32 × Std.U64))
      (core.iter.traits.iterator.IteratorSliceIter (Std.U32 × Std.U64)) i
  core.iter.traits.iterator.Iterator.unzip.default
    (core.iter.adapters.cloned.Cloned.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter (Std.U32 × Std.U64))
    (BuiltinClone (Std.U32 × Std.U64)))
    (alloc.vec.Vec.Insts.CoreDefaultDefault Std.U32)
    (alloc.vec.Vec.Insts.CoreIterTraitsCollectExtend Std.U32)
    (alloc.vec.Vec.Insts.CoreDefaultDefault Std.U64)
    (alloc.vec.Vec.Insts.CoreIterTraitsCollectExtend Std.U64)
    (core.iter.adapters.cloned.Cloned.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter (Std.U32 × Std.U64))
    (BuiltinClone (Std.U32 × Std.U64))) c

/-- [iter_extra::total::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_extra::total::{closure}}::call_mut]:
    Source: 'tests/src/iter-extra.rs', lines 32:29-32:53 -/
def total.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
  (c : total.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result (Std.U32 × total.closure)
  := do
  let (a, b) := tupled_args
  let i ← lift (core.num.U32.wrapping_add a b)
  ok (i, c)

/-- [iter_extra::total::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_extra::total::{closure}}::call_once]:
    Source: 'tests/src/iter-extra.rs', lines 32:29-32:53 -/
def total.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
  (c : total.closure) (p : (Std.U32 × Std.U32)) : Result Std.U32 := do
  let (i, _) ←
    total.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut c p
  ok i

/-- Trait implementation: [iter_extra::total::{impl core::ops::function::FnOnce<(u32, u32), u32> for iter_extra::total::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 32:29-32:53 -/
@[reducible]
def total.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32 :
  core.ops.function.FnOnce total.closure (Std.U32 × Std.U32) Std.U32 := {
  call_once := total.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32.call_once
}

/-- Trait implementation: [iter_extra::total::{impl core::ops::function::FnMut<(u32, u32), u32> for iter_extra::total::{closure}}]
    Source: 'tests/src/iter-extra.rs', lines 32:29-32:53 -/
@[reducible]
def total.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 :
  core.ops.function.FnMut total.closure (Std.U32 × Std.U32) Std.U32 := {
  FnOnceInst := total.closure.Insts.CoreOpsFunctionFnOncePairU32U32U32
  call_mut := total.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32.call_mut
}

/-- [iter_extra::total]:
    Source: 'tests/src/iter-extra.rs', lines 31:0-33:1
    Visibility: public -/
def total (v : Slice Std.U32) : Result (Option Std.U32) := do
  let i ← core.slice.Slice.iter v
  let c ←
    core.iter.traits.iterator.Iterator.cloned.default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) core.clone.CloneU32
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) i
  core.iter.traits.iterator.Iterator.reduce.default
    (core.iter.adapters.cloned.Cloned.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorSliceIter Std.U32) core.clone.CloneU32)
    total.closure.Insts.CoreOpsFunctionFnMutPairU32U32U32 c ()

/-- [iter_extra::order::{impl core::ops::function::FnMut<(&'_1 usize,), (usize, usize)> for iter_extra::order::{closure}<'_0>}::call_mut]:
    Source: 'tests/src/iter-extra.rs', lines 37:22-37:39 -/
def
  order.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizePairUsizeUsize.call_mut
  (c : order.closure) (tupled_args : Std.Usize) :
  Result ((Std.Usize × Std.Usize) × order.closure)
  := do
  let i ← Slice.index_usize c tupled_args
  ok ((i, tupled_args), c)

/-- [iter_extra::order::{impl core::ops::function::FnOnce<(&'_1 usize,), (usize, usize)> for iter_extra::order::{closure}<'_0>}::call_once]:
    Source: 'tests/src/iter-extra.rs', lines 37:22-37:39 -/
def
  order.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizePairUsizeUsize.call_once
  (c : order.closure) (i : Std.Usize) : Result (Std.Usize × Std.Usize) := do
  let (p, _) ←
    order.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizePairUsizeUsize.call_mut
      c i
  ok p

/-- Trait implementation: [iter_extra::order::{impl core::ops::function::FnOnce<(&'_1 usize,), (usize, usize)> for iter_extra::order::{closure}<'_0>}]
    Source: 'tests/src/iter-extra.rs', lines 37:22-37:39 -/
@[reducible]
def order.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizePairUsizeUsize :
  core.ops.function.FnOnce order.closure Std.Usize (Std.Usize × Std.Usize)
  := {
  call_once :=
    order.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizePairUsizeUsize.call_once
}

/-- Trait implementation: [iter_extra::order::{impl core::ops::function::FnMut<(&'_1 usize,), (usize, usize)> for iter_extra::order::{closure}<'_0>}]
    Source: 'tests/src/iter-extra.rs', lines 37:22-37:39 -/
@[reducible]
def order.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizePairUsizeUsize :
  core.ops.function.FnMut order.closure Std.Usize (Std.Usize × Std.Usize) := {
  FnOnceInst :=
    order.closure.Insts.CoreOpsFunctionFnOnceTupleShared1UsizePairUsizeUsize
  call_mut :=
    order.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizePairUsizeUsize.call_mut
}

/-- [iter_extra::order]:
    Source: 'tests/src/iter-extra.rs', lines 35:0-39:1
    Visibility: public -/
def order (lens : Slice Std.Usize) : Result (alloc.vec.Vec Std.Usize) := do
  let i := Slice.len lens
  let order1 ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepUsize)
      (core.iter.traits.collect.FromIteratorVec Std.Usize)
      { start := 0#usize, «end» := i }
  let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut order1)
  let s1 ←
    alloc.slice.Slice.sort_by_key
      order.closure.Insts.CoreOpsFunctionFnMutTupleShared1UsizePairUsizeUsize
      (Pair.Insts.CoreCmpOrd core.cmp.OrdUsize core.cmp.OrdUsize) s lens
  ok (deref_mut_back s1)

end iter_extra
