-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_mut_capture_call]: function definitions
module
public import Aeneas
public import ClosureMutCaptureCall.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closure_mut_capture_call

/-- [closure_mut_capture_call::{closure_mut_capture_call::Counter}::read]:
    Source: 'tests/src/closure-mut-capture-call.rs', lines 15:4-18:5
    Visibility: public -/
def Counter.read (self : Counter) : Result (Std.U32 × Counter) := do
  let i ← lift (core.num.U32.wrapping_add self.n 1#u32)
  ok (i, { n := i })

/-- [closure_mut_capture_call::reads::{impl core::ops::function::FnMut<(u32,), u32> for closure_mut_capture_call::reads::{closure}<'_0>}::call_mut]:
    Source: 'tests/src/closure-mut-capture-call.rs', lines 22:18-22:46 -/
def reads.closure.Insts.CoreOpsFunctionFnMutTupleU32U32.call_mut
  (c : reads.closure) (tupled_args : Std.U32) :
  Result (Std.U32 × reads.closure × (reads.closure → reads.closure))
  := do
  let (i, c1) ← Counter.read c
  let i1 ← lift (core.num.U32.wrapping_add i tupled_args)
  let back := fun c2 => c2
  ok (i1, c1, back)

/-- [closure_mut_capture_call::reads::{impl core::ops::function::FnOnce<(u32,), u32> for closure_mut_capture_call::reads::{closure}<'_0>}::call_once]:
    Source: 'tests/src/closure-mut-capture-call.rs', lines 22:18-22:46 -/
def reads.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
  (c : reads.closure) (i : Std.U32) : Result (Std.U32 × reads.closure) := do
  let (i1, c1, call_mut_back) ←
    reads.closure.Insts.CoreOpsFunctionFnMutTupleU32U32.call_mut c i
  ok (i1, call_mut_back c1)

/-- Trait implementation: [closure_mut_capture_call::reads::{impl core::ops::function::FnOnce<(u32,), u32> for closure_mut_capture_call::reads::{closure}<'_0>}]
    Source: 'tests/src/closure-mut-capture-call.rs', lines 22:18-22:46 -/
@[reducible]
def reads.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32 :
  core.ops.function.FnOnce reads.closure Std.U32 Std.U32 := {
  call_once := fun _ _ => Result.fail Error.undef
}

/-- Trait implementation: [closure_mut_capture_call::reads::{impl core::ops::function::FnMut<(u32,), u32> for closure_mut_capture_call::reads::{closure}<'_0>}]
    Source: 'tests/src/closure-mut-capture-call.rs', lines 22:18-22:46 -/
@[reducible]
def reads.closure.Insts.CoreOpsFunctionFnMutTupleU32U32 :
  core.ops.function.FnMut reads.closure Std.U32 Std.U32 := {
  FnOnceInst := reads.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32
  call_mut := fun x0 x1 =>
    Bind.bind ((reads.closure.Insts.CoreOpsFunctionFnMutTupleU32U32.call_mut) x0 x1)
    (fun (out, self', e1) => ok (out, (e1 self')))
}

/-- [closure_mut_capture_call::reads]:
    Source: 'tests/src/closure-mut-capture-call.rs', lines 21:0-23:1
    Visibility: public -/
def reads (c : Counter) : Result ((alloc.vec.Vec Std.U32) × Counter) := do
  let (m, default_back) ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU32)
      reads.closure.Insts.CoreOpsFunctionFnMutTupleU32U32
      { start := 0#u32, «end» := 2#u32 } c
  let (v, m1) ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU32)
      reads.closure.Insts.CoreOpsFunctionFnMutTupleU32U32)
      (core.iter.traits.collect.FromIteratorVec Std.U32) m
  let c1 := default_back m1
  ok (v, c1)

end closure_mut_capture_call
