#!/usr/bin/env python3
"""Generates backends/lean/Aeneas/Std/Scalar/Ops/RefOps.lean: the by-reference forms of the
binary operators on integers (`&a + b`, `a + &b`, `&a + &b`, ...). Core derives them from the
by-value impls (`forward_ref_binop!`), and so does each model here.

Run from the repository root: python3 scripts/gen_ref_ops.py"""

TYPES = [
    "u8",
    "u16",
    "u32",
    "u64",
    "u128",
    "usize",
    "i8",
    "i16",
    "i32",
    "i64",
    "i128",
    "isize",
]
# (module, trait, method, Lean expression on x y)
OPS = [
    ("arith", "Add", "add", "x + y"),
    ("arith", "Sub", "sub", "x - y"),
    ("arith", "Mul", "mul", "x * y"),
    ("arith", "Div", "div", "x / y"),
    ("arith", "Rem", "rem", "x % y"),
    ("bit", "BitAnd", "bitand", "ok (x &&& y)"),
    ("bit", "BitOr", "bitor", "ok (x ||| y)"),
    ("bit", "BitXor", "bitxor", "ok (x ^^^ y)"),
]
# Already modelled elsewhere (Scalar/Ops/Add.lean)
SKIP = {("Add", "ref_val", t) for t in ["u8", "u16", "u32", "u64", "u128", "usize"]}


def lean_ty(t):
    return t[0].upper() + t[1:]


out = [
    "/- GENERATED by scripts/gen_ref_ops.py: do not edit by hand. -/",
    "module",
    "public import Aeneas.Std.Scalar.Core",
    "public import Aeneas.Std.Scalar.Ops",
    "public import Aeneas.Std.Scalar.Bitwise",
    "public section",
    "",
    "namespace Aeneas.Std",
    "",
    "open Result",
    "",
    "/-! By-reference forms of the integer operators. Core implements `&a op b`, `a op &b` and",
    "`&a op &b` by forwarding to `a op b` (`forward_ref_binop!`), so each model is the by-value",
    "operator; Aeneas erases the shared references. -/",
    "",
]
for mod, tr, m, expr in OPS:
    for t in TYPES:
        L = lean_ty(t)
        shapes = [
            (
                "ref_val",
                f"&'0 {t}, {t}, {t}",
                f"Shared0{L}.Insts.CoreOps{mod.capitalize()}{tr}{L}{L}.{m}",
            ),
            (
                "val_ref",
                f"{t}, &'0 {t}, {t}",
                f"{L}.Insts.CoreOps{mod.capitalize()}{tr}Shared0{L}{L}.{m}",
            ),
            (
                "ref_ref",
                f"&'1 {t}, &'0 {t}, {t}",
                f"Shared1{L}.Insts.CoreOps{mod.capitalize()}{tr}Shared0{L}{L}.{m}",
            ),
        ]
        for shape, args, name in shapes:
            if (tr, shape, t) in SKIP:
                continue
            out.append(
                f'@[expose, rust_fun "core::ops::{mod}::{{core::ops::{mod}::{tr}<{args}>}}::{m}"]'
            )
            out.append(f"def {name} (x y : {L}) : Result {L} := {expr}")
            out.append("")
# `x op= &y`: core forwards it to `x op= y` (`forward_ref_op_assign!`)
out.append(
    "/-! `x op= &y`, likewise forwarded to `x op= y` (`forward_ref_op_assign!`). -/"
)
out.append("")
for mod, tr, m, expr in OPS:
    for t in TYPES:
        L = lean_ty(t)
        name = f"{L}.Insts.CoreOps{mod.capitalize()}{tr}AssignShared0{L}.{m}_assign"
        out.append(
            f'@[expose, rust_fun "core::ops::{mod}::{{core::ops::{mod}::{tr}Assign<{t}, &\'0 {t}>}}::{m}_assign"]'
        )
        out.append(f"def {name} (x y : {L}) : Result {L} := {expr}")
        out.append("")
out.append("end Aeneas.Std")
with open("backends/lean/Aeneas/Std/Scalar/Ops/RefOps.lean", "w") as f:
    f.write("\n".join(out) + "\n")
