-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure_mut_capture_sibling]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace closure_mut_capture_sibling

/-- [core::mem::maybe_uninit::MaybeUninit]
    Source: '/rustc/library/core/src/mem/maybe_uninit.rs', lines 355:0-355:24
    Name pattern: [core::mem::maybe_uninit::MaybeUninit]
    Visibility: public -/
@[rust_type "core::mem::maybe_uninit::MaybeUninit"]
axiom core.mem.maybe_uninit.MaybeUninit (T : Type) : Type

/-- [core::result::{impl core::iter::traits::collect::FromIterator<core::result::Result<T, E>> for core::result::Result<V, E>}::from_iter]:
    Source: '/rustc/library/core/src/result.rs', lines 2158:4-2158:79
    Name pattern: [core::result::{core::iter::traits::collect::FromIterator<core::result::Result<@V, @E>, core::result::Result<@T, @E>>}::from_iter]
    Visibility: public -/
@[rust_fun
  "core::result::{core::iter::traits::collect::FromIterator<core::result::Result<@V, @E>, core::result::Result<@T, @E>>}::from_iter"]
axiom
  core.result.Result.Insts.CoreIterTraitsCollectFromIteratorResult.from_iter
  {T : Type} {E : Type} {V : Type} {I : Type} {Clause1_IntoIter : Type}
  (itertraitscollectFromIteratorInst : core.iter.traits.collect.FromIterator V
  T) (itertraitscollectIntoIteratorIResultClause1_IntoIterInst :
  core.iter.traits.collect.IntoIterator I (core.result.Result T E)
  Clause1_IntoIter) :
  I → Result (core.result.Result V E)

/-- Trait implementation: [core::result::{impl core::iter::traits::collect::FromIterator<core::result::Result<T, E>> for core::result::Result<V, E>}]
    Source: '/rustc/library/core/src/result.rs', lines 2114:0-2114:74
    Name pattern: [core::iter::traits::collect::FromIterator<core::result::Result<@V, @E>, core::result::Result<@T, @E>>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::collect::FromIterator<core::result::Result<@V, @E>, core::result::Result<@T, @E>>"]
def core.result.Result.Insts.CoreIterTraitsCollectFromIteratorResult {T : Type}
  (E : Type) {V : Type} (itertraitscollectFromIteratorInst :
  core.iter.traits.collect.FromIterator V T) :
  core.iter.traits.collect.FromIterator (core.result.Result V E)
  (core.result.Result T E) := {
  from_iter := fun {I : Type} {Clause0_IntoIter : Type}
    (itertraitscollectIntoIteratorPResultPInst :
    core.iter.traits.collect.IntoIterator I (core.result.Result T E)
    Clause0_IntoIter) =>
    core.result.Result.Insts.CoreIterTraitsCollectFromIteratorResult.from_iter
    itertraitscollectFromIteratorInst itertraitscollectIntoIteratorPResultPInst
}

/-- Trait declaration: [closure_mut_capture_sibling::Read]
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 8:0-10:1
    Visibility: public -/
structure Read (Self : Type) where
  read : Self → Result ((core.result.Result Std.U32 Std.U32) × Self)

/-- [closure_mut_capture_sibling::evals::{closure}]
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 16:13-16:63 -/
@[reducible]
def evals.closure (T : Type) := T × alloc.vec.Vec Std.U32

/-- [closure_mut_capture_sibling::evals::{impl core::ops::function::FnMut<(&'_2 usize,), core::result::Result<u32, u32>> for closure_mut_capture_sibling::evals::{closure}<'_0, '_1, T>}::call_mut]:
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 16:13-16:63 -/
def
  evals.closure.Insts.CoreOpsFunctionFnMutTupleShared2UsizeResultU32U32.call_mut
  {T : Type} (ReadInst : Read T) (c : evals.closure T)
  (tupled_args : Std.Usize) :
  Result ((core.result.Result Std.U32 Std.U32) × (evals.closure T) ×
    (evals.closure T → evals.closure T))
  := do
  let (t, v) := c
  if tupled_args = 0#usize
  then
    let (r, t1) ← ReadInst.read t
    let back := fun c1 => let (t2, _) := c1
                          (t2, v)
    ok (r, (t1, v), back)
  else
    let i ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v
        tupled_args
    let back := fun c1 => let (t1, _) := c1
                          (t1, v)
    ok (core.result.Result.Ok i, c, back)

/-- [closure_mut_capture_sibling::evals::{impl core::ops::function::FnOnce<(&'_2 usize,), core::result::Result<u32, u32>> for closure_mut_capture_sibling::evals::{closure}<'_0, '_1, T>}::call_once]:
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 16:13-16:63 -/
def
  evals.closure.Insts.CoreOpsFunctionFnOnceTupleShared2UsizeResultU32U32.call_once
  {T : Type} (ReadInst : Read T) (c : evals.closure T) (i : Std.Usize) :
  Result ((core.result.Result Std.U32 Std.U32) × (evals.closure T))
  := do
  let (_, v) := c
  let (r, c1, call_mut_back) ←
    evals.closure.Insts.CoreOpsFunctionFnMutTupleShared2UsizeResultU32U32.call_mut
      ReadInst c i
  let (t, _) := call_mut_back c1
  ok (r, (t, v))

/-- Trait implementation: [closure_mut_capture_sibling::evals::{impl core::ops::function::FnOnce<(&'_2 usize,), core::result::Result<u32, u32>> for closure_mut_capture_sibling::evals::{closure}<'_0, '_1, T>}]
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 16:13-16:63 -/
@[reducible]
def evals.closure.Insts.CoreOpsFunctionFnOnceTupleShared2UsizeResultU32U32 {T :
  Type} (ReadInst : Read T) : core.ops.function.FnOnce (evals.closure T)
  Std.Usize ((core.result.Result Std.U32 Std.U32) × (evals.closure T)) := {
  call_once := fun x0 x1 =>
    Bind.bind ((evals.closure.Insts.CoreOpsFunctionFnOnceTupleShared2UsizeResultU32U32.call_once
    ReadInst) x0 x1) (fun (out, b0) => ok (out, b0))
}

/-- Trait implementation: [closure_mut_capture_sibling::evals::{impl core::ops::function::FnMut<(&'_2 usize,), core::result::Result<u32, u32>> for closure_mut_capture_sibling::evals::{closure}<'_0, '_1, T>}]
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 16:13-16:63 -/
@[reducible]
def evals.closure.Insts.CoreOpsFunctionFnMutTupleShared2UsizeResultU32U32 {T :
  Type} (ReadInst : Read T) : core.ops.function.FnMut (evals.closure T)
  Std.Usize (core.result.Result Std.U32 Std.U32) := {
  FnOnceInst :=
    evals.closure.Insts.CoreOpsFunctionFnOnceTupleShared2UsizeResultU32U32
    ReadInst
  call_mut := fun _ _ => Result.fail Error.undef
}

/-- [closure_mut_capture_sibling::evals]:
    Source: 'tests/src/closure-mut-capture-sibling.rs', lines 12:0-19:1
    Visibility: public -/
def evals
  {T : Type} (ReadInst : Read T) (columns : Slice Std.Usize) (t : T) :
  Result ((core.result.Result Std.U32 Std.U32) × T)
  := do
  let y ←
    lift (Std.Array.to_slice (Array.make 3#usize [ 1#u32, 2#u32, 3#u32 ] :
      Array Std.U32 3#usize))
  let ret := alloc.slice.Slice.into_vec y
  let i ← core.slice.Slice.iter columns
  let (m, default_back) ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
      (evals.closure.Insts.CoreOpsFunctionFnMutTupleShared2UsizeResultU32U32
      ReadInst) i (t, ret)
  let (r, m1) ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.traits.iterator.IteratorSliceIter Std.Usize)
      (evals.closure.Insts.CoreOpsFunctionFnMutTupleShared2UsizeResultU32U32
      ReadInst))
      (core.result.Result.Insts.CoreIterTraitsCollectFromIteratorResult Std.U32
      (core.iter.traits.collect.FromIteratorVec Std.U32)) m
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i1 := alloc.vec.Vec.len val
    let i2 ← lift (UScalar.cast .U32 i1)
    let (t1, _) := default_back m1
    ok (core.result.Result.Ok i2, t1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
        Std.U32 (core.convert.FromSame Std.U32) residual
    let (t1, _) := default_back m1
    ok (r1, t1)

end closure_mut_capture_sibling
