-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hashmap_collect_index]: function definitions
module
public import Aeneas
public import HashmapCollectIndex.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hashmap_collect_index

/-- Trait implementation: [core::hash::impls::{impl core::hash::Hash for u32}]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 811:12-811:29
    Name pattern: [core::hash::Hash<u32>] -/
@[reducible, rust_trait_impl "core::hash::Hash<u32>"]
def U32.Insts.CoreHashHash : core.hash.Hash Std.U32 := {
  hash := fun {H : Type} (HasherInst : core.hash.Hasher H) =>
    U32.Insts.CoreHashHash.hash HasherInst
}

/-- Trait implementation: [std::collections::hash::map::{impl core::iter::traits::collect::FromIterator<(K, V)> for std::collections::hash::map::HashMap<K, V, S, alloc::alloc::Global>}]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 3004:0-3007:29
    Name pattern: [core::iter::traits::collect::FromIterator<std::collections::hash::map::HashMap<@K, @V, @S, alloc::alloc::Global>, (@K, @V)>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::collect::FromIterator<std::collections::hash::map::HashMap<@K, @V, @S, alloc::alloc::Global>, (@K, @V)>"]
def
  std.collections.hash.map.HashMapKVSGlobal.Insts.CoreIterTraitsCollectFromIteratorPair
  {K : Type} (V : Type) {S : Type} {Clause2_Hasher : Type} (corecmpEqInst :
  core.cmp.Eq K) (corehashHashInst : core.hash.Hash K) (corehashBuildHasherInst
  : core.hash.BuildHasher S Clause2_Hasher) (coredefaultDefaultInst :
  core.default.Default S) : core.iter.traits.collect.FromIterator
  (std.collections.hash.map.HashMap K V S Global) (K × V) := {
  from_iter := fun {I : Type} {Clause0_IntoIter : Type}
    (coreitertraitscollectIntoIteratorPPairPInst :
    core.iter.traits.collect.IntoIterator I (K × V) Clause0_IntoIter) =>
    std.collections.hash.map.HashMapKVSGlobal.Insts.CoreIterTraitsCollectFromIteratorPair.from_iter
    corecmpEqInst corehashHashInst corehashBuildHasherInst
    coredefaultDefaultInst coreitertraitscollectIntoIteratorPPairPInst
}

/-- Trait implementation: [std::hash::random::{impl core::hash::Hasher for std::hash::random::DefaultHasher}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 125:0-125:29
    Name pattern: [core::hash::Hasher<std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::Hasher<std::hash::random::DefaultHasher>"]
def std.hash.random.DefaultHasher.Insts.CoreHashHasher : core.hash.Hasher
  std.hash.random.DefaultHasher := {
  finish := std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  write := std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
}

/-- Trait implementation: [std::hash::random::{impl core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 80:0-80:32
    Name pattern: [core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>"]
def std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher :
  core.hash.BuildHasher std.hash.random.RandomState
  std.hash.random.DefaultHasher := {
  HasherInst := std.hash.random.DefaultHasher.Insts.CoreHashHasher
  build_hasher :=
    std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
}

/-- Trait implementation: [std::hash::random::{impl core::default::Default for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 146:0-146:28
    Name pattern: [core::default::Default<std::hash::random::RandomState>] -/
@[reducible, rust_trait_impl
  "core::default::Default<std::hash::random::RandomState>"]
def std.hash.random.RandomState.Insts.CoreDefaultDefault : core.default.Default
  std.hash.random.RandomState := {
  default := std.hash.random.RandomState.Insts.CoreDefaultDefault.default
}

/-- [hashmap_collect_index::lookup::{impl core::ops::function::FnMut<((&'_0 u32, &'_1 u32),), core::result::Result<(u32, u32), u32>> for hashmap_collect_index::lookup::{closure}}::call_mut]:
    Source: 'tests/src/hashmap-collect-index.rs', lines 13:13-13:66 -/
def
  lookup.closure.Insts.CoreOpsFunctionFnMutTuplePairShared0U32Shared1U32ResultPairU32U32U32.call_mut
  (c : lookup.closure) (tupled_args : (Std.U32 × Std.U32)) :
  Result ((core.result.Result (Std.U32 × Std.U32) Std.U32) × lookup.closure)
  := do
  let (k, v) := tupled_args
  if v = 0#u32
  then ok (core.result.Result.Err k, c)
  else ok (core.result.Result.Ok tupled_args, c)

/-- [hashmap_collect_index::lookup::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 u32),), core::result::Result<(u32, u32), u32>> for hashmap_collect_index::lookup::{closure}}::call_once]:
    Source: 'tests/src/hashmap-collect-index.rs', lines 13:13-13:66 -/
def
  lookup.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32ResultPairU32U32U32.call_once
  (c : lookup.closure) (p : (Std.U32 × Std.U32)) :
  Result (core.result.Result (Std.U32 × Std.U32) Std.U32)
  := do
  let (r, _) ←
    lookup.closure.Insts.CoreOpsFunctionFnMutTuplePairShared0U32Shared1U32ResultPairU32U32U32.call_mut
      c p
  ok r

/-- Trait implementation: [hashmap_collect_index::lookup::{impl core::ops::function::FnOnce<((&'_0 u32, &'_1 u32),), core::result::Result<(u32, u32), u32>> for hashmap_collect_index::lookup::{closure}}]
    Source: 'tests/src/hashmap-collect-index.rs', lines 13:13-13:66 -/
@[reducible]
def
  lookup.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32ResultPairU32U32U32
  : core.ops.function.FnOnce lookup.closure (Std.U32 × Std.U32)
  (core.result.Result (Std.U32 × Std.U32) Std.U32) := {
  call_once :=
    lookup.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32ResultPairU32U32U32.call_once
}

/-- Trait implementation: [hashmap_collect_index::lookup::{impl core::ops::function::FnMut<((&'_0 u32, &'_1 u32),), core::result::Result<(u32, u32), u32>> for hashmap_collect_index::lookup::{closure}}]
    Source: 'tests/src/hashmap-collect-index.rs', lines 13:13-13:66 -/
@[reducible]
def
  lookup.closure.Insts.CoreOpsFunctionFnMutTuplePairShared0U32Shared1U32ResultPairU32U32U32
  : core.ops.function.FnMut lookup.closure (Std.U32 × Std.U32)
  (core.result.Result (Std.U32 × Std.U32) Std.U32) := {
  FnOnceInst :=
    lookup.closure.Insts.CoreOpsFunctionFnOnceTuplePairShared0U32Shared1U32ResultPairU32U32U32
  call_mut :=
    lookup.closure.Insts.CoreOpsFunctionFnMutTuplePairShared0U32Shared1U32ResultPairU32U32U32.call_mut
}

/-- [hashmap_collect_index::lookup]:
    Source: 'tests/src/hashmap-collect-index.rs', lines 9:0-16:1
    Visibility: public -/
def lookup
  (keys : Slice Std.U32) (vals : Slice Std.U32) (k : Std.U32) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  let i ← core.slice.Slice.iter keys
  let i1 ← core.slice.Slice.iter vals
  let z ←
    core.iter.traits.iterator.Iterator.zip.trait_default
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.collect.IntoIterator.Blanket
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) i i1
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.iterator.IteratorSliceIter Std.U32))
      lookup.closure.Insts.CoreOpsFunctionFnMutTuplePairShared0U32Shared1U32ResultPairU32U32U32
      z ()
  let r ←
    core.iter.traits.iterator.Iterator.collect.default
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
      (core.iter.adapters.zip.Zip.Insts.CoreIterTraitsIteratorIteratorPair
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)
      (core.iter.traits.iterator.IteratorSliceIter Std.U32))
      lookup.closure.Insts.CoreOpsFunctionFnMutTuplePairShared0U32Shared1U32ResultPairU32U32U32)
      (core.result.Result.Insts.CoreIterTraitsCollectFromIteratorResult Std.U32
      (std.collections.hash.map.HashMapKVSGlobal.Insts.CoreIterTraitsCollectFromIteratorPair
      Std.U32 core.cmp.EqU32 U32.Insts.CoreHashHash
      std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
      std.hash.random.RandomState.Insts.CoreDefaultDefault)) m
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i2 ←
      std.collections.hash.map.HashMap.Insts.CoreOpsIndexIndexShared0QV.index
        core.cmp.EqU32 U32.Insts.CoreHashHash (core.borrow.Borrow.Blanket
        Std.U32) core.cmp.EqU32 U32.Insts.CoreHashHash
        std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher val
        k
    ok (core.result.Result.Ok i2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      Std.U32 (core.convert.FromSame Std.U32) residual

end hashmap_collect_index
