/- GENERATED by scripts/gen_ref_ops.py: do not edit by hand. -/
module
public import Aeneas.Std.Scalar.Core
public import Aeneas.Std.Scalar.Ops
public import Aeneas.Std.Scalar.Bitwise
public section

namespace Aeneas.Std

open Result

/-! By-reference forms of the integer operators. Core implements `&a op b`, `a op &b` and
`&a op &b` by forwarding to `a op b` (`forward_ref_binop!`), so each model is the by-value
operator; Aeneas erases the shared references. -/

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<u8, &'0 u8, u8>}::add"]
def U8.Insts.CoreOpsArithAddShared0U8U8.add (x y : U8) : Result U8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 u8, &'0 u8, u8>}::add"]
def Shared1U8.Insts.CoreOpsArithAddShared0U8U8.add (x y : U8) : Result U8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<u16, &'0 u16, u16>}::add"]
def U16.Insts.CoreOpsArithAddShared0U16U16.add (x y : U16) : Result U16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 u16, &'0 u16, u16>}::add"]
def Shared1U16.Insts.CoreOpsArithAddShared0U16U16.add (x y : U16) : Result U16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<u32, &'0 u32, u32>}::add"]
def U32.Insts.CoreOpsArithAddShared0U32U32.add (x y : U32) : Result U32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 u32, &'0 u32, u32>}::add"]
def Shared1U32.Insts.CoreOpsArithAddShared0U32U32.add (x y : U32) : Result U32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<u64, &'0 u64, u64>}::add"]
def U64.Insts.CoreOpsArithAddShared0U64U64.add (x y : U64) : Result U64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 u64, &'0 u64, u64>}::add"]
def Shared1U64.Insts.CoreOpsArithAddShared0U64U64.add (x y : U64) : Result U64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<u128, &'0 u128, u128>}::add"]
def U128.Insts.CoreOpsArithAddShared0U128U128.add (x y : U128) : Result U128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 u128, &'0 u128, u128>}::add"]
def Shared1U128.Insts.CoreOpsArithAddShared0U128U128.add (x y : U128) : Result U128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<usize, &'0 usize, usize>}::add"]
def Usize.Insts.CoreOpsArithAddShared0UsizeUsize.add (x y : Usize) : Result Usize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 usize, &'0 usize, usize>}::add"]
def Shared1Usize.Insts.CoreOpsArithAddShared0UsizeUsize.add (x y : Usize) : Result Usize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'0 i8, i8, i8>}::add"]
def Shared0I8.Insts.CoreOpsArithAddI8I8.add (x y : I8) : Result I8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<i8, &'0 i8, i8>}::add"]
def I8.Insts.CoreOpsArithAddShared0I8I8.add (x y : I8) : Result I8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 i8, &'0 i8, i8>}::add"]
def Shared1I8.Insts.CoreOpsArithAddShared0I8I8.add (x y : I8) : Result I8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'0 i16, i16, i16>}::add"]
def Shared0I16.Insts.CoreOpsArithAddI16I16.add (x y : I16) : Result I16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<i16, &'0 i16, i16>}::add"]
def I16.Insts.CoreOpsArithAddShared0I16I16.add (x y : I16) : Result I16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 i16, &'0 i16, i16>}::add"]
def Shared1I16.Insts.CoreOpsArithAddShared0I16I16.add (x y : I16) : Result I16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'0 i32, i32, i32>}::add"]
def Shared0I32.Insts.CoreOpsArithAddI32I32.add (x y : I32) : Result I32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<i32, &'0 i32, i32>}::add"]
def I32.Insts.CoreOpsArithAddShared0I32I32.add (x y : I32) : Result I32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 i32, &'0 i32, i32>}::add"]
def Shared1I32.Insts.CoreOpsArithAddShared0I32I32.add (x y : I32) : Result I32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'0 i64, i64, i64>}::add"]
def Shared0I64.Insts.CoreOpsArithAddI64I64.add (x y : I64) : Result I64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<i64, &'0 i64, i64>}::add"]
def I64.Insts.CoreOpsArithAddShared0I64I64.add (x y : I64) : Result I64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 i64, &'0 i64, i64>}::add"]
def Shared1I64.Insts.CoreOpsArithAddShared0I64I64.add (x y : I64) : Result I64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'0 i128, i128, i128>}::add"]
def Shared0I128.Insts.CoreOpsArithAddI128I128.add (x y : I128) : Result I128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<i128, &'0 i128, i128>}::add"]
def I128.Insts.CoreOpsArithAddShared0I128I128.add (x y : I128) : Result I128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 i128, &'0 i128, i128>}::add"]
def Shared1I128.Insts.CoreOpsArithAddShared0I128I128.add (x y : I128) : Result I128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'0 isize, isize, isize>}::add"]
def Shared0Isize.Insts.CoreOpsArithAddIsizeIsize.add (x y : Isize) : Result Isize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<isize, &'0 isize, isize>}::add"]
def Isize.Insts.CoreOpsArithAddShared0IsizeIsize.add (x y : Isize) : Result Isize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Add<&'1 isize, &'0 isize, isize>}::add"]
def Shared1Isize.Insts.CoreOpsArithAddShared0IsizeIsize.add (x y : Isize) : Result Isize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 u8, u8, u8>}::sub"]
def Shared0U8.Insts.CoreOpsArithSubU8U8.sub (x y : U8) : Result U8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<u8, &'0 u8, u8>}::sub"]
def U8.Insts.CoreOpsArithSubShared0U8U8.sub (x y : U8) : Result U8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 u8, &'0 u8, u8>}::sub"]
def Shared1U8.Insts.CoreOpsArithSubShared0U8U8.sub (x y : U8) : Result U8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 u16, u16, u16>}::sub"]
def Shared0U16.Insts.CoreOpsArithSubU16U16.sub (x y : U16) : Result U16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<u16, &'0 u16, u16>}::sub"]
def U16.Insts.CoreOpsArithSubShared0U16U16.sub (x y : U16) : Result U16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 u16, &'0 u16, u16>}::sub"]
def Shared1U16.Insts.CoreOpsArithSubShared0U16U16.sub (x y : U16) : Result U16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 u32, u32, u32>}::sub"]
def Shared0U32.Insts.CoreOpsArithSubU32U32.sub (x y : U32) : Result U32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<u32, &'0 u32, u32>}::sub"]
def U32.Insts.CoreOpsArithSubShared0U32U32.sub (x y : U32) : Result U32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 u32, &'0 u32, u32>}::sub"]
def Shared1U32.Insts.CoreOpsArithSubShared0U32U32.sub (x y : U32) : Result U32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 u64, u64, u64>}::sub"]
def Shared0U64.Insts.CoreOpsArithSubU64U64.sub (x y : U64) : Result U64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<u64, &'0 u64, u64>}::sub"]
def U64.Insts.CoreOpsArithSubShared0U64U64.sub (x y : U64) : Result U64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 u64, &'0 u64, u64>}::sub"]
def Shared1U64.Insts.CoreOpsArithSubShared0U64U64.sub (x y : U64) : Result U64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 u128, u128, u128>}::sub"]
def Shared0U128.Insts.CoreOpsArithSubU128U128.sub (x y : U128) : Result U128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<u128, &'0 u128, u128>}::sub"]
def U128.Insts.CoreOpsArithSubShared0U128U128.sub (x y : U128) : Result U128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 u128, &'0 u128, u128>}::sub"]
def Shared1U128.Insts.CoreOpsArithSubShared0U128U128.sub (x y : U128) : Result U128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 usize, usize, usize>}::sub"]
def Shared0Usize.Insts.CoreOpsArithSubUsizeUsize.sub (x y : Usize) : Result Usize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<usize, &'0 usize, usize>}::sub"]
def Usize.Insts.CoreOpsArithSubShared0UsizeUsize.sub (x y : Usize) : Result Usize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 usize, &'0 usize, usize>}::sub"]
def Shared1Usize.Insts.CoreOpsArithSubShared0UsizeUsize.sub (x y : Usize) : Result Usize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 i8, i8, i8>}::sub"]
def Shared0I8.Insts.CoreOpsArithSubI8I8.sub (x y : I8) : Result I8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<i8, &'0 i8, i8>}::sub"]
def I8.Insts.CoreOpsArithSubShared0I8I8.sub (x y : I8) : Result I8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 i8, &'0 i8, i8>}::sub"]
def Shared1I8.Insts.CoreOpsArithSubShared0I8I8.sub (x y : I8) : Result I8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 i16, i16, i16>}::sub"]
def Shared0I16.Insts.CoreOpsArithSubI16I16.sub (x y : I16) : Result I16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<i16, &'0 i16, i16>}::sub"]
def I16.Insts.CoreOpsArithSubShared0I16I16.sub (x y : I16) : Result I16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 i16, &'0 i16, i16>}::sub"]
def Shared1I16.Insts.CoreOpsArithSubShared0I16I16.sub (x y : I16) : Result I16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 i32, i32, i32>}::sub"]
def Shared0I32.Insts.CoreOpsArithSubI32I32.sub (x y : I32) : Result I32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<i32, &'0 i32, i32>}::sub"]
def I32.Insts.CoreOpsArithSubShared0I32I32.sub (x y : I32) : Result I32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 i32, &'0 i32, i32>}::sub"]
def Shared1I32.Insts.CoreOpsArithSubShared0I32I32.sub (x y : I32) : Result I32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 i64, i64, i64>}::sub"]
def Shared0I64.Insts.CoreOpsArithSubI64I64.sub (x y : I64) : Result I64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<i64, &'0 i64, i64>}::sub"]
def I64.Insts.CoreOpsArithSubShared0I64I64.sub (x y : I64) : Result I64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 i64, &'0 i64, i64>}::sub"]
def Shared1I64.Insts.CoreOpsArithSubShared0I64I64.sub (x y : I64) : Result I64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 i128, i128, i128>}::sub"]
def Shared0I128.Insts.CoreOpsArithSubI128I128.sub (x y : I128) : Result I128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<i128, &'0 i128, i128>}::sub"]
def I128.Insts.CoreOpsArithSubShared0I128I128.sub (x y : I128) : Result I128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 i128, &'0 i128, i128>}::sub"]
def Shared1I128.Insts.CoreOpsArithSubShared0I128I128.sub (x y : I128) : Result I128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'0 isize, isize, isize>}::sub"]
def Shared0Isize.Insts.CoreOpsArithSubIsizeIsize.sub (x y : Isize) : Result Isize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<isize, &'0 isize, isize>}::sub"]
def Isize.Insts.CoreOpsArithSubShared0IsizeIsize.sub (x y : Isize) : Result Isize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Sub<&'1 isize, &'0 isize, isize>}::sub"]
def Shared1Isize.Insts.CoreOpsArithSubShared0IsizeIsize.sub (x y : Isize) : Result Isize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 u8, u8, u8>}::mul"]
def Shared0U8.Insts.CoreOpsArithMulU8U8.mul (x y : U8) : Result U8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<u8, &'0 u8, u8>}::mul"]
def U8.Insts.CoreOpsArithMulShared0U8U8.mul (x y : U8) : Result U8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 u8, &'0 u8, u8>}::mul"]
def Shared1U8.Insts.CoreOpsArithMulShared0U8U8.mul (x y : U8) : Result U8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 u16, u16, u16>}::mul"]
def Shared0U16.Insts.CoreOpsArithMulU16U16.mul (x y : U16) : Result U16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<u16, &'0 u16, u16>}::mul"]
def U16.Insts.CoreOpsArithMulShared0U16U16.mul (x y : U16) : Result U16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 u16, &'0 u16, u16>}::mul"]
def Shared1U16.Insts.CoreOpsArithMulShared0U16U16.mul (x y : U16) : Result U16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 u32, u32, u32>}::mul"]
def Shared0U32.Insts.CoreOpsArithMulU32U32.mul (x y : U32) : Result U32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<u32, &'0 u32, u32>}::mul"]
def U32.Insts.CoreOpsArithMulShared0U32U32.mul (x y : U32) : Result U32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 u32, &'0 u32, u32>}::mul"]
def Shared1U32.Insts.CoreOpsArithMulShared0U32U32.mul (x y : U32) : Result U32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 u64, u64, u64>}::mul"]
def Shared0U64.Insts.CoreOpsArithMulU64U64.mul (x y : U64) : Result U64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<u64, &'0 u64, u64>}::mul"]
def U64.Insts.CoreOpsArithMulShared0U64U64.mul (x y : U64) : Result U64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 u64, &'0 u64, u64>}::mul"]
def Shared1U64.Insts.CoreOpsArithMulShared0U64U64.mul (x y : U64) : Result U64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 u128, u128, u128>}::mul"]
def Shared0U128.Insts.CoreOpsArithMulU128U128.mul (x y : U128) : Result U128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<u128, &'0 u128, u128>}::mul"]
def U128.Insts.CoreOpsArithMulShared0U128U128.mul (x y : U128) : Result U128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 u128, &'0 u128, u128>}::mul"]
def Shared1U128.Insts.CoreOpsArithMulShared0U128U128.mul (x y : U128) : Result U128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 usize, usize, usize>}::mul"]
def Shared0Usize.Insts.CoreOpsArithMulUsizeUsize.mul (x y : Usize) : Result Usize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<usize, &'0 usize, usize>}::mul"]
def Usize.Insts.CoreOpsArithMulShared0UsizeUsize.mul (x y : Usize) : Result Usize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 usize, &'0 usize, usize>}::mul"]
def Shared1Usize.Insts.CoreOpsArithMulShared0UsizeUsize.mul (x y : Usize) : Result Usize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 i8, i8, i8>}::mul"]
def Shared0I8.Insts.CoreOpsArithMulI8I8.mul (x y : I8) : Result I8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<i8, &'0 i8, i8>}::mul"]
def I8.Insts.CoreOpsArithMulShared0I8I8.mul (x y : I8) : Result I8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 i8, &'0 i8, i8>}::mul"]
def Shared1I8.Insts.CoreOpsArithMulShared0I8I8.mul (x y : I8) : Result I8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 i16, i16, i16>}::mul"]
def Shared0I16.Insts.CoreOpsArithMulI16I16.mul (x y : I16) : Result I16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<i16, &'0 i16, i16>}::mul"]
def I16.Insts.CoreOpsArithMulShared0I16I16.mul (x y : I16) : Result I16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 i16, &'0 i16, i16>}::mul"]
def Shared1I16.Insts.CoreOpsArithMulShared0I16I16.mul (x y : I16) : Result I16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 i32, i32, i32>}::mul"]
def Shared0I32.Insts.CoreOpsArithMulI32I32.mul (x y : I32) : Result I32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<i32, &'0 i32, i32>}::mul"]
def I32.Insts.CoreOpsArithMulShared0I32I32.mul (x y : I32) : Result I32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 i32, &'0 i32, i32>}::mul"]
def Shared1I32.Insts.CoreOpsArithMulShared0I32I32.mul (x y : I32) : Result I32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 i64, i64, i64>}::mul"]
def Shared0I64.Insts.CoreOpsArithMulI64I64.mul (x y : I64) : Result I64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<i64, &'0 i64, i64>}::mul"]
def I64.Insts.CoreOpsArithMulShared0I64I64.mul (x y : I64) : Result I64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 i64, &'0 i64, i64>}::mul"]
def Shared1I64.Insts.CoreOpsArithMulShared0I64I64.mul (x y : I64) : Result I64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 i128, i128, i128>}::mul"]
def Shared0I128.Insts.CoreOpsArithMulI128I128.mul (x y : I128) : Result I128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<i128, &'0 i128, i128>}::mul"]
def I128.Insts.CoreOpsArithMulShared0I128I128.mul (x y : I128) : Result I128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 i128, &'0 i128, i128>}::mul"]
def Shared1I128.Insts.CoreOpsArithMulShared0I128I128.mul (x y : I128) : Result I128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'0 isize, isize, isize>}::mul"]
def Shared0Isize.Insts.CoreOpsArithMulIsizeIsize.mul (x y : Isize) : Result Isize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<isize, &'0 isize, isize>}::mul"]
def Isize.Insts.CoreOpsArithMulShared0IsizeIsize.mul (x y : Isize) : Result Isize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Mul<&'1 isize, &'0 isize, isize>}::mul"]
def Shared1Isize.Insts.CoreOpsArithMulShared0IsizeIsize.mul (x y : Isize) : Result Isize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 u8, u8, u8>}::div"]
def Shared0U8.Insts.CoreOpsArithDivU8U8.div (x y : U8) : Result U8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<u8, &'0 u8, u8>}::div"]
def U8.Insts.CoreOpsArithDivShared0U8U8.div (x y : U8) : Result U8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 u8, &'0 u8, u8>}::div"]
def Shared1U8.Insts.CoreOpsArithDivShared0U8U8.div (x y : U8) : Result U8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 u16, u16, u16>}::div"]
def Shared0U16.Insts.CoreOpsArithDivU16U16.div (x y : U16) : Result U16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<u16, &'0 u16, u16>}::div"]
def U16.Insts.CoreOpsArithDivShared0U16U16.div (x y : U16) : Result U16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 u16, &'0 u16, u16>}::div"]
def Shared1U16.Insts.CoreOpsArithDivShared0U16U16.div (x y : U16) : Result U16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 u32, u32, u32>}::div"]
def Shared0U32.Insts.CoreOpsArithDivU32U32.div (x y : U32) : Result U32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<u32, &'0 u32, u32>}::div"]
def U32.Insts.CoreOpsArithDivShared0U32U32.div (x y : U32) : Result U32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 u32, &'0 u32, u32>}::div"]
def Shared1U32.Insts.CoreOpsArithDivShared0U32U32.div (x y : U32) : Result U32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 u64, u64, u64>}::div"]
def Shared0U64.Insts.CoreOpsArithDivU64U64.div (x y : U64) : Result U64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<u64, &'0 u64, u64>}::div"]
def U64.Insts.CoreOpsArithDivShared0U64U64.div (x y : U64) : Result U64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 u64, &'0 u64, u64>}::div"]
def Shared1U64.Insts.CoreOpsArithDivShared0U64U64.div (x y : U64) : Result U64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 u128, u128, u128>}::div"]
def Shared0U128.Insts.CoreOpsArithDivU128U128.div (x y : U128) : Result U128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<u128, &'0 u128, u128>}::div"]
def U128.Insts.CoreOpsArithDivShared0U128U128.div (x y : U128) : Result U128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 u128, &'0 u128, u128>}::div"]
def Shared1U128.Insts.CoreOpsArithDivShared0U128U128.div (x y : U128) : Result U128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 usize, usize, usize>}::div"]
def Shared0Usize.Insts.CoreOpsArithDivUsizeUsize.div (x y : Usize) : Result Usize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<usize, &'0 usize, usize>}::div"]
def Usize.Insts.CoreOpsArithDivShared0UsizeUsize.div (x y : Usize) : Result Usize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 usize, &'0 usize, usize>}::div"]
def Shared1Usize.Insts.CoreOpsArithDivShared0UsizeUsize.div (x y : Usize) : Result Usize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 i8, i8, i8>}::div"]
def Shared0I8.Insts.CoreOpsArithDivI8I8.div (x y : I8) : Result I8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<i8, &'0 i8, i8>}::div"]
def I8.Insts.CoreOpsArithDivShared0I8I8.div (x y : I8) : Result I8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 i8, &'0 i8, i8>}::div"]
def Shared1I8.Insts.CoreOpsArithDivShared0I8I8.div (x y : I8) : Result I8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 i16, i16, i16>}::div"]
def Shared0I16.Insts.CoreOpsArithDivI16I16.div (x y : I16) : Result I16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<i16, &'0 i16, i16>}::div"]
def I16.Insts.CoreOpsArithDivShared0I16I16.div (x y : I16) : Result I16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 i16, &'0 i16, i16>}::div"]
def Shared1I16.Insts.CoreOpsArithDivShared0I16I16.div (x y : I16) : Result I16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 i32, i32, i32>}::div"]
def Shared0I32.Insts.CoreOpsArithDivI32I32.div (x y : I32) : Result I32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<i32, &'0 i32, i32>}::div"]
def I32.Insts.CoreOpsArithDivShared0I32I32.div (x y : I32) : Result I32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 i32, &'0 i32, i32>}::div"]
def Shared1I32.Insts.CoreOpsArithDivShared0I32I32.div (x y : I32) : Result I32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 i64, i64, i64>}::div"]
def Shared0I64.Insts.CoreOpsArithDivI64I64.div (x y : I64) : Result I64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<i64, &'0 i64, i64>}::div"]
def I64.Insts.CoreOpsArithDivShared0I64I64.div (x y : I64) : Result I64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 i64, &'0 i64, i64>}::div"]
def Shared1I64.Insts.CoreOpsArithDivShared0I64I64.div (x y : I64) : Result I64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 i128, i128, i128>}::div"]
def Shared0I128.Insts.CoreOpsArithDivI128I128.div (x y : I128) : Result I128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<i128, &'0 i128, i128>}::div"]
def I128.Insts.CoreOpsArithDivShared0I128I128.div (x y : I128) : Result I128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 i128, &'0 i128, i128>}::div"]
def Shared1I128.Insts.CoreOpsArithDivShared0I128I128.div (x y : I128) : Result I128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'0 isize, isize, isize>}::div"]
def Shared0Isize.Insts.CoreOpsArithDivIsizeIsize.div (x y : Isize) : Result Isize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<isize, &'0 isize, isize>}::div"]
def Isize.Insts.CoreOpsArithDivShared0IsizeIsize.div (x y : Isize) : Result Isize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Div<&'1 isize, &'0 isize, isize>}::div"]
def Shared1Isize.Insts.CoreOpsArithDivShared0IsizeIsize.div (x y : Isize) : Result Isize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 u8, u8, u8>}::rem"]
def Shared0U8.Insts.CoreOpsArithRemU8U8.rem (x y : U8) : Result U8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<u8, &'0 u8, u8>}::rem"]
def U8.Insts.CoreOpsArithRemShared0U8U8.rem (x y : U8) : Result U8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 u8, &'0 u8, u8>}::rem"]
def Shared1U8.Insts.CoreOpsArithRemShared0U8U8.rem (x y : U8) : Result U8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 u16, u16, u16>}::rem"]
def Shared0U16.Insts.CoreOpsArithRemU16U16.rem (x y : U16) : Result U16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<u16, &'0 u16, u16>}::rem"]
def U16.Insts.CoreOpsArithRemShared0U16U16.rem (x y : U16) : Result U16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 u16, &'0 u16, u16>}::rem"]
def Shared1U16.Insts.CoreOpsArithRemShared0U16U16.rem (x y : U16) : Result U16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 u32, u32, u32>}::rem"]
def Shared0U32.Insts.CoreOpsArithRemU32U32.rem (x y : U32) : Result U32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<u32, &'0 u32, u32>}::rem"]
def U32.Insts.CoreOpsArithRemShared0U32U32.rem (x y : U32) : Result U32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 u32, &'0 u32, u32>}::rem"]
def Shared1U32.Insts.CoreOpsArithRemShared0U32U32.rem (x y : U32) : Result U32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 u64, u64, u64>}::rem"]
def Shared0U64.Insts.CoreOpsArithRemU64U64.rem (x y : U64) : Result U64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<u64, &'0 u64, u64>}::rem"]
def U64.Insts.CoreOpsArithRemShared0U64U64.rem (x y : U64) : Result U64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 u64, &'0 u64, u64>}::rem"]
def Shared1U64.Insts.CoreOpsArithRemShared0U64U64.rem (x y : U64) : Result U64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 u128, u128, u128>}::rem"]
def Shared0U128.Insts.CoreOpsArithRemU128U128.rem (x y : U128) : Result U128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<u128, &'0 u128, u128>}::rem"]
def U128.Insts.CoreOpsArithRemShared0U128U128.rem (x y : U128) : Result U128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 u128, &'0 u128, u128>}::rem"]
def Shared1U128.Insts.CoreOpsArithRemShared0U128U128.rem (x y : U128) : Result U128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 usize, usize, usize>}::rem"]
def Shared0Usize.Insts.CoreOpsArithRemUsizeUsize.rem (x y : Usize) : Result Usize := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<usize, &'0 usize, usize>}::rem"]
def Usize.Insts.CoreOpsArithRemShared0UsizeUsize.rem (x y : Usize) : Result Usize := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 usize, &'0 usize, usize>}::rem"]
def Shared1Usize.Insts.CoreOpsArithRemShared0UsizeUsize.rem (x y : Usize) : Result Usize := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 i8, i8, i8>}::rem"]
def Shared0I8.Insts.CoreOpsArithRemI8I8.rem (x y : I8) : Result I8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<i8, &'0 i8, i8>}::rem"]
def I8.Insts.CoreOpsArithRemShared0I8I8.rem (x y : I8) : Result I8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 i8, &'0 i8, i8>}::rem"]
def Shared1I8.Insts.CoreOpsArithRemShared0I8I8.rem (x y : I8) : Result I8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 i16, i16, i16>}::rem"]
def Shared0I16.Insts.CoreOpsArithRemI16I16.rem (x y : I16) : Result I16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<i16, &'0 i16, i16>}::rem"]
def I16.Insts.CoreOpsArithRemShared0I16I16.rem (x y : I16) : Result I16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 i16, &'0 i16, i16>}::rem"]
def Shared1I16.Insts.CoreOpsArithRemShared0I16I16.rem (x y : I16) : Result I16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 i32, i32, i32>}::rem"]
def Shared0I32.Insts.CoreOpsArithRemI32I32.rem (x y : I32) : Result I32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<i32, &'0 i32, i32>}::rem"]
def I32.Insts.CoreOpsArithRemShared0I32I32.rem (x y : I32) : Result I32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 i32, &'0 i32, i32>}::rem"]
def Shared1I32.Insts.CoreOpsArithRemShared0I32I32.rem (x y : I32) : Result I32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 i64, i64, i64>}::rem"]
def Shared0I64.Insts.CoreOpsArithRemI64I64.rem (x y : I64) : Result I64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<i64, &'0 i64, i64>}::rem"]
def I64.Insts.CoreOpsArithRemShared0I64I64.rem (x y : I64) : Result I64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 i64, &'0 i64, i64>}::rem"]
def Shared1I64.Insts.CoreOpsArithRemShared0I64I64.rem (x y : I64) : Result I64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 i128, i128, i128>}::rem"]
def Shared0I128.Insts.CoreOpsArithRemI128I128.rem (x y : I128) : Result I128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<i128, &'0 i128, i128>}::rem"]
def I128.Insts.CoreOpsArithRemShared0I128I128.rem (x y : I128) : Result I128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 i128, &'0 i128, i128>}::rem"]
def Shared1I128.Insts.CoreOpsArithRemShared0I128I128.rem (x y : I128) : Result I128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'0 isize, isize, isize>}::rem"]
def Shared0Isize.Insts.CoreOpsArithRemIsizeIsize.rem (x y : Isize) : Result Isize := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<isize, &'0 isize, isize>}::rem"]
def Isize.Insts.CoreOpsArithRemShared0IsizeIsize.rem (x y : Isize) : Result Isize := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::Rem<&'1 isize, &'0 isize, isize>}::rem"]
def Shared1Isize.Insts.CoreOpsArithRemShared0IsizeIsize.rem (x y : Isize) : Result Isize := x % y

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 u8, u8, u8>}::bitand"]
def Shared0U8.Insts.CoreOpsBitBitAndU8U8.bitand (x y : U8) : Result U8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<u8, &'0 u8, u8>}::bitand"]
def U8.Insts.CoreOpsBitBitAndShared0U8U8.bitand (x y : U8) : Result U8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 u8, &'0 u8, u8>}::bitand"]
def Shared1U8.Insts.CoreOpsBitBitAndShared0U8U8.bitand (x y : U8) : Result U8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 u16, u16, u16>}::bitand"]
def Shared0U16.Insts.CoreOpsBitBitAndU16U16.bitand (x y : U16) : Result U16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<u16, &'0 u16, u16>}::bitand"]
def U16.Insts.CoreOpsBitBitAndShared0U16U16.bitand (x y : U16) : Result U16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 u16, &'0 u16, u16>}::bitand"]
def Shared1U16.Insts.CoreOpsBitBitAndShared0U16U16.bitand (x y : U16) : Result U16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 u32, u32, u32>}::bitand"]
def Shared0U32.Insts.CoreOpsBitBitAndU32U32.bitand (x y : U32) : Result U32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<u32, &'0 u32, u32>}::bitand"]
def U32.Insts.CoreOpsBitBitAndShared0U32U32.bitand (x y : U32) : Result U32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 u32, &'0 u32, u32>}::bitand"]
def Shared1U32.Insts.CoreOpsBitBitAndShared0U32U32.bitand (x y : U32) : Result U32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 u64, u64, u64>}::bitand"]
def Shared0U64.Insts.CoreOpsBitBitAndU64U64.bitand (x y : U64) : Result U64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<u64, &'0 u64, u64>}::bitand"]
def U64.Insts.CoreOpsBitBitAndShared0U64U64.bitand (x y : U64) : Result U64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 u64, &'0 u64, u64>}::bitand"]
def Shared1U64.Insts.CoreOpsBitBitAndShared0U64U64.bitand (x y : U64) : Result U64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 u128, u128, u128>}::bitand"]
def Shared0U128.Insts.CoreOpsBitBitAndU128U128.bitand (x y : U128) : Result U128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<u128, &'0 u128, u128>}::bitand"]
def U128.Insts.CoreOpsBitBitAndShared0U128U128.bitand (x y : U128) : Result U128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 u128, &'0 u128, u128>}::bitand"]
def Shared1U128.Insts.CoreOpsBitBitAndShared0U128U128.bitand (x y : U128) : Result U128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 usize, usize, usize>}::bitand"]
def Shared0Usize.Insts.CoreOpsBitBitAndUsizeUsize.bitand (x y : Usize) : Result Usize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<usize, &'0 usize, usize>}::bitand"]
def Usize.Insts.CoreOpsBitBitAndShared0UsizeUsize.bitand (x y : Usize) : Result Usize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 usize, &'0 usize, usize>}::bitand"]
def Shared1Usize.Insts.CoreOpsBitBitAndShared0UsizeUsize.bitand (x y : Usize) : Result Usize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 i8, i8, i8>}::bitand"]
def Shared0I8.Insts.CoreOpsBitBitAndI8I8.bitand (x y : I8) : Result I8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<i8, &'0 i8, i8>}::bitand"]
def I8.Insts.CoreOpsBitBitAndShared0I8I8.bitand (x y : I8) : Result I8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 i8, &'0 i8, i8>}::bitand"]
def Shared1I8.Insts.CoreOpsBitBitAndShared0I8I8.bitand (x y : I8) : Result I8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 i16, i16, i16>}::bitand"]
def Shared0I16.Insts.CoreOpsBitBitAndI16I16.bitand (x y : I16) : Result I16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<i16, &'0 i16, i16>}::bitand"]
def I16.Insts.CoreOpsBitBitAndShared0I16I16.bitand (x y : I16) : Result I16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 i16, &'0 i16, i16>}::bitand"]
def Shared1I16.Insts.CoreOpsBitBitAndShared0I16I16.bitand (x y : I16) : Result I16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 i32, i32, i32>}::bitand"]
def Shared0I32.Insts.CoreOpsBitBitAndI32I32.bitand (x y : I32) : Result I32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<i32, &'0 i32, i32>}::bitand"]
def I32.Insts.CoreOpsBitBitAndShared0I32I32.bitand (x y : I32) : Result I32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 i32, &'0 i32, i32>}::bitand"]
def Shared1I32.Insts.CoreOpsBitBitAndShared0I32I32.bitand (x y : I32) : Result I32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 i64, i64, i64>}::bitand"]
def Shared0I64.Insts.CoreOpsBitBitAndI64I64.bitand (x y : I64) : Result I64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<i64, &'0 i64, i64>}::bitand"]
def I64.Insts.CoreOpsBitBitAndShared0I64I64.bitand (x y : I64) : Result I64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 i64, &'0 i64, i64>}::bitand"]
def Shared1I64.Insts.CoreOpsBitBitAndShared0I64I64.bitand (x y : I64) : Result I64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 i128, i128, i128>}::bitand"]
def Shared0I128.Insts.CoreOpsBitBitAndI128I128.bitand (x y : I128) : Result I128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<i128, &'0 i128, i128>}::bitand"]
def I128.Insts.CoreOpsBitBitAndShared0I128I128.bitand (x y : I128) : Result I128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 i128, &'0 i128, i128>}::bitand"]
def Shared1I128.Insts.CoreOpsBitBitAndShared0I128I128.bitand (x y : I128) : Result I128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 isize, isize, isize>}::bitand"]
def Shared0Isize.Insts.CoreOpsBitBitAndIsizeIsize.bitand (x y : Isize) : Result Isize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<isize, &'0 isize, isize>}::bitand"]
def Isize.Insts.CoreOpsBitBitAndShared0IsizeIsize.bitand (x y : Isize) : Result Isize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'1 isize, &'0 isize, isize>}::bitand"]
def Shared1Isize.Insts.CoreOpsBitBitAndShared0IsizeIsize.bitand (x y : Isize) : Result Isize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 u8, u8, u8>}::bitor"]
def Shared0U8.Insts.CoreOpsBitBitOrU8U8.bitor (x y : U8) : Result U8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<u8, &'0 u8, u8>}::bitor"]
def U8.Insts.CoreOpsBitBitOrShared0U8U8.bitor (x y : U8) : Result U8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 u8, &'0 u8, u8>}::bitor"]
def Shared1U8.Insts.CoreOpsBitBitOrShared0U8U8.bitor (x y : U8) : Result U8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 u16, u16, u16>}::bitor"]
def Shared0U16.Insts.CoreOpsBitBitOrU16U16.bitor (x y : U16) : Result U16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<u16, &'0 u16, u16>}::bitor"]
def U16.Insts.CoreOpsBitBitOrShared0U16U16.bitor (x y : U16) : Result U16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 u16, &'0 u16, u16>}::bitor"]
def Shared1U16.Insts.CoreOpsBitBitOrShared0U16U16.bitor (x y : U16) : Result U16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 u32, u32, u32>}::bitor"]
def Shared0U32.Insts.CoreOpsBitBitOrU32U32.bitor (x y : U32) : Result U32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<u32, &'0 u32, u32>}::bitor"]
def U32.Insts.CoreOpsBitBitOrShared0U32U32.bitor (x y : U32) : Result U32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 u32, &'0 u32, u32>}::bitor"]
def Shared1U32.Insts.CoreOpsBitBitOrShared0U32U32.bitor (x y : U32) : Result U32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 u64, u64, u64>}::bitor"]
def Shared0U64.Insts.CoreOpsBitBitOrU64U64.bitor (x y : U64) : Result U64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<u64, &'0 u64, u64>}::bitor"]
def U64.Insts.CoreOpsBitBitOrShared0U64U64.bitor (x y : U64) : Result U64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 u64, &'0 u64, u64>}::bitor"]
def Shared1U64.Insts.CoreOpsBitBitOrShared0U64U64.bitor (x y : U64) : Result U64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 u128, u128, u128>}::bitor"]
def Shared0U128.Insts.CoreOpsBitBitOrU128U128.bitor (x y : U128) : Result U128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<u128, &'0 u128, u128>}::bitor"]
def U128.Insts.CoreOpsBitBitOrShared0U128U128.bitor (x y : U128) : Result U128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 u128, &'0 u128, u128>}::bitor"]
def Shared1U128.Insts.CoreOpsBitBitOrShared0U128U128.bitor (x y : U128) : Result U128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 usize, usize, usize>}::bitor"]
def Shared0Usize.Insts.CoreOpsBitBitOrUsizeUsize.bitor (x y : Usize) : Result Usize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<usize, &'0 usize, usize>}::bitor"]
def Usize.Insts.CoreOpsBitBitOrShared0UsizeUsize.bitor (x y : Usize) : Result Usize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 usize, &'0 usize, usize>}::bitor"]
def Shared1Usize.Insts.CoreOpsBitBitOrShared0UsizeUsize.bitor (x y : Usize) : Result Usize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 i8, i8, i8>}::bitor"]
def Shared0I8.Insts.CoreOpsBitBitOrI8I8.bitor (x y : I8) : Result I8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<i8, &'0 i8, i8>}::bitor"]
def I8.Insts.CoreOpsBitBitOrShared0I8I8.bitor (x y : I8) : Result I8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 i8, &'0 i8, i8>}::bitor"]
def Shared1I8.Insts.CoreOpsBitBitOrShared0I8I8.bitor (x y : I8) : Result I8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 i16, i16, i16>}::bitor"]
def Shared0I16.Insts.CoreOpsBitBitOrI16I16.bitor (x y : I16) : Result I16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<i16, &'0 i16, i16>}::bitor"]
def I16.Insts.CoreOpsBitBitOrShared0I16I16.bitor (x y : I16) : Result I16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 i16, &'0 i16, i16>}::bitor"]
def Shared1I16.Insts.CoreOpsBitBitOrShared0I16I16.bitor (x y : I16) : Result I16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 i32, i32, i32>}::bitor"]
def Shared0I32.Insts.CoreOpsBitBitOrI32I32.bitor (x y : I32) : Result I32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<i32, &'0 i32, i32>}::bitor"]
def I32.Insts.CoreOpsBitBitOrShared0I32I32.bitor (x y : I32) : Result I32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 i32, &'0 i32, i32>}::bitor"]
def Shared1I32.Insts.CoreOpsBitBitOrShared0I32I32.bitor (x y : I32) : Result I32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 i64, i64, i64>}::bitor"]
def Shared0I64.Insts.CoreOpsBitBitOrI64I64.bitor (x y : I64) : Result I64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<i64, &'0 i64, i64>}::bitor"]
def I64.Insts.CoreOpsBitBitOrShared0I64I64.bitor (x y : I64) : Result I64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 i64, &'0 i64, i64>}::bitor"]
def Shared1I64.Insts.CoreOpsBitBitOrShared0I64I64.bitor (x y : I64) : Result I64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 i128, i128, i128>}::bitor"]
def Shared0I128.Insts.CoreOpsBitBitOrI128I128.bitor (x y : I128) : Result I128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<i128, &'0 i128, i128>}::bitor"]
def I128.Insts.CoreOpsBitBitOrShared0I128I128.bitor (x y : I128) : Result I128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 i128, &'0 i128, i128>}::bitor"]
def Shared1I128.Insts.CoreOpsBitBitOrShared0I128I128.bitor (x y : I128) : Result I128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'0 isize, isize, isize>}::bitor"]
def Shared0Isize.Insts.CoreOpsBitBitOrIsizeIsize.bitor (x y : Isize) : Result Isize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<isize, &'0 isize, isize>}::bitor"]
def Isize.Insts.CoreOpsBitBitOrShared0IsizeIsize.bitor (x y : Isize) : Result Isize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOr<&'1 isize, &'0 isize, isize>}::bitor"]
def Shared1Isize.Insts.CoreOpsBitBitOrShared0IsizeIsize.bitor (x y : Isize) : Result Isize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 u8, u8, u8>}::bitxor"]
def Shared0U8.Insts.CoreOpsBitBitXorU8U8.bitxor (x y : U8) : Result U8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<u8, &'0 u8, u8>}::bitxor"]
def U8.Insts.CoreOpsBitBitXorShared0U8U8.bitxor (x y : U8) : Result U8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 u8, &'0 u8, u8>}::bitxor"]
def Shared1U8.Insts.CoreOpsBitBitXorShared0U8U8.bitxor (x y : U8) : Result U8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 u16, u16, u16>}::bitxor"]
def Shared0U16.Insts.CoreOpsBitBitXorU16U16.bitxor (x y : U16) : Result U16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<u16, &'0 u16, u16>}::bitxor"]
def U16.Insts.CoreOpsBitBitXorShared0U16U16.bitxor (x y : U16) : Result U16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 u16, &'0 u16, u16>}::bitxor"]
def Shared1U16.Insts.CoreOpsBitBitXorShared0U16U16.bitxor (x y : U16) : Result U16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 u32, u32, u32>}::bitxor"]
def Shared0U32.Insts.CoreOpsBitBitXorU32U32.bitxor (x y : U32) : Result U32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<u32, &'0 u32, u32>}::bitxor"]
def U32.Insts.CoreOpsBitBitXorShared0U32U32.bitxor (x y : U32) : Result U32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 u32, &'0 u32, u32>}::bitxor"]
def Shared1U32.Insts.CoreOpsBitBitXorShared0U32U32.bitxor (x y : U32) : Result U32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 u64, u64, u64>}::bitxor"]
def Shared0U64.Insts.CoreOpsBitBitXorU64U64.bitxor (x y : U64) : Result U64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<u64, &'0 u64, u64>}::bitxor"]
def U64.Insts.CoreOpsBitBitXorShared0U64U64.bitxor (x y : U64) : Result U64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 u64, &'0 u64, u64>}::bitxor"]
def Shared1U64.Insts.CoreOpsBitBitXorShared0U64U64.bitxor (x y : U64) : Result U64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 u128, u128, u128>}::bitxor"]
def Shared0U128.Insts.CoreOpsBitBitXorU128U128.bitxor (x y : U128) : Result U128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<u128, &'0 u128, u128>}::bitxor"]
def U128.Insts.CoreOpsBitBitXorShared0U128U128.bitxor (x y : U128) : Result U128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 u128, &'0 u128, u128>}::bitxor"]
def Shared1U128.Insts.CoreOpsBitBitXorShared0U128U128.bitxor (x y : U128) : Result U128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 usize, usize, usize>}::bitxor"]
def Shared0Usize.Insts.CoreOpsBitBitXorUsizeUsize.bitxor (x y : Usize) : Result Usize := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<usize, &'0 usize, usize>}::bitxor"]
def Usize.Insts.CoreOpsBitBitXorShared0UsizeUsize.bitxor (x y : Usize) : Result Usize := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 usize, &'0 usize, usize>}::bitxor"]
def Shared1Usize.Insts.CoreOpsBitBitXorShared0UsizeUsize.bitxor (x y : Usize) : Result Usize := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 i8, i8, i8>}::bitxor"]
def Shared0I8.Insts.CoreOpsBitBitXorI8I8.bitxor (x y : I8) : Result I8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<i8, &'0 i8, i8>}::bitxor"]
def I8.Insts.CoreOpsBitBitXorShared0I8I8.bitxor (x y : I8) : Result I8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 i8, &'0 i8, i8>}::bitxor"]
def Shared1I8.Insts.CoreOpsBitBitXorShared0I8I8.bitxor (x y : I8) : Result I8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 i16, i16, i16>}::bitxor"]
def Shared0I16.Insts.CoreOpsBitBitXorI16I16.bitxor (x y : I16) : Result I16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<i16, &'0 i16, i16>}::bitxor"]
def I16.Insts.CoreOpsBitBitXorShared0I16I16.bitxor (x y : I16) : Result I16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 i16, &'0 i16, i16>}::bitxor"]
def Shared1I16.Insts.CoreOpsBitBitXorShared0I16I16.bitxor (x y : I16) : Result I16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 i32, i32, i32>}::bitxor"]
def Shared0I32.Insts.CoreOpsBitBitXorI32I32.bitxor (x y : I32) : Result I32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<i32, &'0 i32, i32>}::bitxor"]
def I32.Insts.CoreOpsBitBitXorShared0I32I32.bitxor (x y : I32) : Result I32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 i32, &'0 i32, i32>}::bitxor"]
def Shared1I32.Insts.CoreOpsBitBitXorShared0I32I32.bitxor (x y : I32) : Result I32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 i64, i64, i64>}::bitxor"]
def Shared0I64.Insts.CoreOpsBitBitXorI64I64.bitxor (x y : I64) : Result I64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<i64, &'0 i64, i64>}::bitxor"]
def I64.Insts.CoreOpsBitBitXorShared0I64I64.bitxor (x y : I64) : Result I64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 i64, &'0 i64, i64>}::bitxor"]
def Shared1I64.Insts.CoreOpsBitBitXorShared0I64I64.bitxor (x y : I64) : Result I64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 i128, i128, i128>}::bitxor"]
def Shared0I128.Insts.CoreOpsBitBitXorI128I128.bitxor (x y : I128) : Result I128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<i128, &'0 i128, i128>}::bitxor"]
def I128.Insts.CoreOpsBitBitXorShared0I128I128.bitxor (x y : I128) : Result I128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 i128, &'0 i128, i128>}::bitxor"]
def Shared1I128.Insts.CoreOpsBitBitXorShared0I128I128.bitxor (x y : I128) : Result I128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'0 isize, isize, isize>}::bitxor"]
def Shared0Isize.Insts.CoreOpsBitBitXorIsizeIsize.bitxor (x y : Isize) : Result Isize := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<isize, &'0 isize, isize>}::bitxor"]
def Isize.Insts.CoreOpsBitBitXorShared0IsizeIsize.bitxor (x y : Isize) : Result Isize := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXor<&'1 isize, &'0 isize, isize>}::bitxor"]
def Shared1Isize.Insts.CoreOpsBitBitXorShared0IsizeIsize.bitxor (x y : Isize) : Result Isize := ok (x ^^^ y)

/-! `x op= &y`, likewise forwarded to `x op= y` (`forward_ref_op_assign!`). -/

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<u8, &'0 u8>}::add_assign"]
def U8.Insts.CoreOpsArithAddAssignShared0U8.add_assign (x y : U8) : Result U8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<u16, &'0 u16>}::add_assign"]
def U16.Insts.CoreOpsArithAddAssignShared0U16.add_assign (x y : U16) : Result U16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<u32, &'0 u32>}::add_assign"]
def U32.Insts.CoreOpsArithAddAssignShared0U32.add_assign (x y : U32) : Result U32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<u64, &'0 u64>}::add_assign"]
def U64.Insts.CoreOpsArithAddAssignShared0U64.add_assign (x y : U64) : Result U64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<u128, &'0 u128>}::add_assign"]
def U128.Insts.CoreOpsArithAddAssignShared0U128.add_assign (x y : U128) : Result U128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<usize, &'0 usize>}::add_assign"]
def Usize.Insts.CoreOpsArithAddAssignShared0Usize.add_assign (x y : Usize) : Result Usize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<i8, &'0 i8>}::add_assign"]
def I8.Insts.CoreOpsArithAddAssignShared0I8.add_assign (x y : I8) : Result I8 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<i16, &'0 i16>}::add_assign"]
def I16.Insts.CoreOpsArithAddAssignShared0I16.add_assign (x y : I16) : Result I16 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<i32, &'0 i32>}::add_assign"]
def I32.Insts.CoreOpsArithAddAssignShared0I32.add_assign (x y : I32) : Result I32 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<i64, &'0 i64>}::add_assign"]
def I64.Insts.CoreOpsArithAddAssignShared0I64.add_assign (x y : I64) : Result I64 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<i128, &'0 i128>}::add_assign"]
def I128.Insts.CoreOpsArithAddAssignShared0I128.add_assign (x y : I128) : Result I128 := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::AddAssign<isize, &'0 isize>}::add_assign"]
def Isize.Insts.CoreOpsArithAddAssignShared0Isize.add_assign (x y : Isize) : Result Isize := x + y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<u8, &'0 u8>}::sub_assign"]
def U8.Insts.CoreOpsArithSubAssignShared0U8.sub_assign (x y : U8) : Result U8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<u16, &'0 u16>}::sub_assign"]
def U16.Insts.CoreOpsArithSubAssignShared0U16.sub_assign (x y : U16) : Result U16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<u32, &'0 u32>}::sub_assign"]
def U32.Insts.CoreOpsArithSubAssignShared0U32.sub_assign (x y : U32) : Result U32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<u64, &'0 u64>}::sub_assign"]
def U64.Insts.CoreOpsArithSubAssignShared0U64.sub_assign (x y : U64) : Result U64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<u128, &'0 u128>}::sub_assign"]
def U128.Insts.CoreOpsArithSubAssignShared0U128.sub_assign (x y : U128) : Result U128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<usize, &'0 usize>}::sub_assign"]
def Usize.Insts.CoreOpsArithSubAssignShared0Usize.sub_assign (x y : Usize) : Result Usize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<i8, &'0 i8>}::sub_assign"]
def I8.Insts.CoreOpsArithSubAssignShared0I8.sub_assign (x y : I8) : Result I8 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<i16, &'0 i16>}::sub_assign"]
def I16.Insts.CoreOpsArithSubAssignShared0I16.sub_assign (x y : I16) : Result I16 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<i32, &'0 i32>}::sub_assign"]
def I32.Insts.CoreOpsArithSubAssignShared0I32.sub_assign (x y : I32) : Result I32 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<i64, &'0 i64>}::sub_assign"]
def I64.Insts.CoreOpsArithSubAssignShared0I64.sub_assign (x y : I64) : Result I64 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<i128, &'0 i128>}::sub_assign"]
def I128.Insts.CoreOpsArithSubAssignShared0I128.sub_assign (x y : I128) : Result I128 := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::SubAssign<isize, &'0 isize>}::sub_assign"]
def Isize.Insts.CoreOpsArithSubAssignShared0Isize.sub_assign (x y : Isize) : Result Isize := x - y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<u8, &'0 u8>}::mul_assign"]
def U8.Insts.CoreOpsArithMulAssignShared0U8.mul_assign (x y : U8) : Result U8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<u16, &'0 u16>}::mul_assign"]
def U16.Insts.CoreOpsArithMulAssignShared0U16.mul_assign (x y : U16) : Result U16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<u32, &'0 u32>}::mul_assign"]
def U32.Insts.CoreOpsArithMulAssignShared0U32.mul_assign (x y : U32) : Result U32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<u64, &'0 u64>}::mul_assign"]
def U64.Insts.CoreOpsArithMulAssignShared0U64.mul_assign (x y : U64) : Result U64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<u128, &'0 u128>}::mul_assign"]
def U128.Insts.CoreOpsArithMulAssignShared0U128.mul_assign (x y : U128) : Result U128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<usize, &'0 usize>}::mul_assign"]
def Usize.Insts.CoreOpsArithMulAssignShared0Usize.mul_assign (x y : Usize) : Result Usize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<i8, &'0 i8>}::mul_assign"]
def I8.Insts.CoreOpsArithMulAssignShared0I8.mul_assign (x y : I8) : Result I8 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<i16, &'0 i16>}::mul_assign"]
def I16.Insts.CoreOpsArithMulAssignShared0I16.mul_assign (x y : I16) : Result I16 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<i32, &'0 i32>}::mul_assign"]
def I32.Insts.CoreOpsArithMulAssignShared0I32.mul_assign (x y : I32) : Result I32 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<i64, &'0 i64>}::mul_assign"]
def I64.Insts.CoreOpsArithMulAssignShared0I64.mul_assign (x y : I64) : Result I64 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<i128, &'0 i128>}::mul_assign"]
def I128.Insts.CoreOpsArithMulAssignShared0I128.mul_assign (x y : I128) : Result I128 := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::MulAssign<isize, &'0 isize>}::mul_assign"]
def Isize.Insts.CoreOpsArithMulAssignShared0Isize.mul_assign (x y : Isize) : Result Isize := x * y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<u8, &'0 u8>}::div_assign"]
def U8.Insts.CoreOpsArithDivAssignShared0U8.div_assign (x y : U8) : Result U8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<u16, &'0 u16>}::div_assign"]
def U16.Insts.CoreOpsArithDivAssignShared0U16.div_assign (x y : U16) : Result U16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<u32, &'0 u32>}::div_assign"]
def U32.Insts.CoreOpsArithDivAssignShared0U32.div_assign (x y : U32) : Result U32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<u64, &'0 u64>}::div_assign"]
def U64.Insts.CoreOpsArithDivAssignShared0U64.div_assign (x y : U64) : Result U64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<u128, &'0 u128>}::div_assign"]
def U128.Insts.CoreOpsArithDivAssignShared0U128.div_assign (x y : U128) : Result U128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<usize, &'0 usize>}::div_assign"]
def Usize.Insts.CoreOpsArithDivAssignShared0Usize.div_assign (x y : Usize) : Result Usize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<i8, &'0 i8>}::div_assign"]
def I8.Insts.CoreOpsArithDivAssignShared0I8.div_assign (x y : I8) : Result I8 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<i16, &'0 i16>}::div_assign"]
def I16.Insts.CoreOpsArithDivAssignShared0I16.div_assign (x y : I16) : Result I16 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<i32, &'0 i32>}::div_assign"]
def I32.Insts.CoreOpsArithDivAssignShared0I32.div_assign (x y : I32) : Result I32 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<i64, &'0 i64>}::div_assign"]
def I64.Insts.CoreOpsArithDivAssignShared0I64.div_assign (x y : I64) : Result I64 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<i128, &'0 i128>}::div_assign"]
def I128.Insts.CoreOpsArithDivAssignShared0I128.div_assign (x y : I128) : Result I128 := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::DivAssign<isize, &'0 isize>}::div_assign"]
def Isize.Insts.CoreOpsArithDivAssignShared0Isize.div_assign (x y : Isize) : Result Isize := x / y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<u8, &'0 u8>}::rem_assign"]
def U8.Insts.CoreOpsArithRemAssignShared0U8.rem_assign (x y : U8) : Result U8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<u16, &'0 u16>}::rem_assign"]
def U16.Insts.CoreOpsArithRemAssignShared0U16.rem_assign (x y : U16) : Result U16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<u32, &'0 u32>}::rem_assign"]
def U32.Insts.CoreOpsArithRemAssignShared0U32.rem_assign (x y : U32) : Result U32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<u64, &'0 u64>}::rem_assign"]
def U64.Insts.CoreOpsArithRemAssignShared0U64.rem_assign (x y : U64) : Result U64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<u128, &'0 u128>}::rem_assign"]
def U128.Insts.CoreOpsArithRemAssignShared0U128.rem_assign (x y : U128) : Result U128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<usize, &'0 usize>}::rem_assign"]
def Usize.Insts.CoreOpsArithRemAssignShared0Usize.rem_assign (x y : Usize) : Result Usize := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<i8, &'0 i8>}::rem_assign"]
def I8.Insts.CoreOpsArithRemAssignShared0I8.rem_assign (x y : I8) : Result I8 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<i16, &'0 i16>}::rem_assign"]
def I16.Insts.CoreOpsArithRemAssignShared0I16.rem_assign (x y : I16) : Result I16 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<i32, &'0 i32>}::rem_assign"]
def I32.Insts.CoreOpsArithRemAssignShared0I32.rem_assign (x y : I32) : Result I32 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<i64, &'0 i64>}::rem_assign"]
def I64.Insts.CoreOpsArithRemAssignShared0I64.rem_assign (x y : I64) : Result I64 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<i128, &'0 i128>}::rem_assign"]
def I128.Insts.CoreOpsArithRemAssignShared0I128.rem_assign (x y : I128) : Result I128 := x % y

@[expose, rust_fun "core::ops::arith::{core::ops::arith::RemAssign<isize, &'0 isize>}::rem_assign"]
def Isize.Insts.CoreOpsArithRemAssignShared0Isize.rem_assign (x y : Isize) : Result Isize := x % y

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<u8, &'0 u8>}::bitand_assign"]
def U8.Insts.CoreOpsBitBitAndAssignShared0U8.bitand_assign (x y : U8) : Result U8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<u16, &'0 u16>}::bitand_assign"]
def U16.Insts.CoreOpsBitBitAndAssignShared0U16.bitand_assign (x y : U16) : Result U16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<u32, &'0 u32>}::bitand_assign"]
def U32.Insts.CoreOpsBitBitAndAssignShared0U32.bitand_assign (x y : U32) : Result U32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<u64, &'0 u64>}::bitand_assign"]
def U64.Insts.CoreOpsBitBitAndAssignShared0U64.bitand_assign (x y : U64) : Result U64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<u128, &'0 u128>}::bitand_assign"]
def U128.Insts.CoreOpsBitBitAndAssignShared0U128.bitand_assign (x y : U128) : Result U128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<usize, &'0 usize>}::bitand_assign"]
def Usize.Insts.CoreOpsBitBitAndAssignShared0Usize.bitand_assign (x y : Usize) : Result Usize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<i8, &'0 i8>}::bitand_assign"]
def I8.Insts.CoreOpsBitBitAndAssignShared0I8.bitand_assign (x y : I8) : Result I8 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<i16, &'0 i16>}::bitand_assign"]
def I16.Insts.CoreOpsBitBitAndAssignShared0I16.bitand_assign (x y : I16) : Result I16 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<i32, &'0 i32>}::bitand_assign"]
def I32.Insts.CoreOpsBitBitAndAssignShared0I32.bitand_assign (x y : I32) : Result I32 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<i64, &'0 i64>}::bitand_assign"]
def I64.Insts.CoreOpsBitBitAndAssignShared0I64.bitand_assign (x y : I64) : Result I64 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<i128, &'0 i128>}::bitand_assign"]
def I128.Insts.CoreOpsBitBitAndAssignShared0I128.bitand_assign (x y : I128) : Result I128 := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitAndAssign<isize, &'0 isize>}::bitand_assign"]
def Isize.Insts.CoreOpsBitBitAndAssignShared0Isize.bitand_assign (x y : Isize) : Result Isize := ok (x &&& y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<u8, &'0 u8>}::bitor_assign"]
def U8.Insts.CoreOpsBitBitOrAssignShared0U8.bitor_assign (x y : U8) : Result U8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<u16, &'0 u16>}::bitor_assign"]
def U16.Insts.CoreOpsBitBitOrAssignShared0U16.bitor_assign (x y : U16) : Result U16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<u32, &'0 u32>}::bitor_assign"]
def U32.Insts.CoreOpsBitBitOrAssignShared0U32.bitor_assign (x y : U32) : Result U32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<u64, &'0 u64>}::bitor_assign"]
def U64.Insts.CoreOpsBitBitOrAssignShared0U64.bitor_assign (x y : U64) : Result U64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<u128, &'0 u128>}::bitor_assign"]
def U128.Insts.CoreOpsBitBitOrAssignShared0U128.bitor_assign (x y : U128) : Result U128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<usize, &'0 usize>}::bitor_assign"]
def Usize.Insts.CoreOpsBitBitOrAssignShared0Usize.bitor_assign (x y : Usize) : Result Usize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<i8, &'0 i8>}::bitor_assign"]
def I8.Insts.CoreOpsBitBitOrAssignShared0I8.bitor_assign (x y : I8) : Result I8 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<i16, &'0 i16>}::bitor_assign"]
def I16.Insts.CoreOpsBitBitOrAssignShared0I16.bitor_assign (x y : I16) : Result I16 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<i32, &'0 i32>}::bitor_assign"]
def I32.Insts.CoreOpsBitBitOrAssignShared0I32.bitor_assign (x y : I32) : Result I32 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<i64, &'0 i64>}::bitor_assign"]
def I64.Insts.CoreOpsBitBitOrAssignShared0I64.bitor_assign (x y : I64) : Result I64 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<i128, &'0 i128>}::bitor_assign"]
def I128.Insts.CoreOpsBitBitOrAssignShared0I128.bitor_assign (x y : I128) : Result I128 := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitOrAssign<isize, &'0 isize>}::bitor_assign"]
def Isize.Insts.CoreOpsBitBitOrAssignShared0Isize.bitor_assign (x y : Isize) : Result Isize := ok (x ||| y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<u8, &'0 u8>}::bitxor_assign"]
def U8.Insts.CoreOpsBitBitXorAssignShared0U8.bitxor_assign (x y : U8) : Result U8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<u16, &'0 u16>}::bitxor_assign"]
def U16.Insts.CoreOpsBitBitXorAssignShared0U16.bitxor_assign (x y : U16) : Result U16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<u32, &'0 u32>}::bitxor_assign"]
def U32.Insts.CoreOpsBitBitXorAssignShared0U32.bitxor_assign (x y : U32) : Result U32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<u64, &'0 u64>}::bitxor_assign"]
def U64.Insts.CoreOpsBitBitXorAssignShared0U64.bitxor_assign (x y : U64) : Result U64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<u128, &'0 u128>}::bitxor_assign"]
def U128.Insts.CoreOpsBitBitXorAssignShared0U128.bitxor_assign (x y : U128) : Result U128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<usize, &'0 usize>}::bitxor_assign"]
def Usize.Insts.CoreOpsBitBitXorAssignShared0Usize.bitxor_assign (x y : Usize) : Result Usize := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<i8, &'0 i8>}::bitxor_assign"]
def I8.Insts.CoreOpsBitBitXorAssignShared0I8.bitxor_assign (x y : I8) : Result I8 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<i16, &'0 i16>}::bitxor_assign"]
def I16.Insts.CoreOpsBitBitXorAssignShared0I16.bitxor_assign (x y : I16) : Result I16 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<i32, &'0 i32>}::bitxor_assign"]
def I32.Insts.CoreOpsBitBitXorAssignShared0I32.bitxor_assign (x y : I32) : Result I32 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<i64, &'0 i64>}::bitxor_assign"]
def I64.Insts.CoreOpsBitBitXorAssignShared0I64.bitxor_assign (x y : I64) : Result I64 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<i128, &'0 i128>}::bitxor_assign"]
def I128.Insts.CoreOpsBitBitXorAssignShared0I128.bitxor_assign (x y : I128) : Result I128 := ok (x ^^^ y)

@[expose, rust_fun "core::ops::bit::{core::ops::bit::BitXorAssign<isize, &'0 isize>}::bitxor_assign"]
def Isize.Insts.CoreOpsBitBitXorAssignShared0Isize.bitxor_assign (x y : Isize) : Result Isize := ok (x ^^^ y)

end Aeneas.Std
